// Auto-generated file from a2-localizations_es.csv

export const localization_es: Map<string, string> = new Map<string, string>([
  ['AUTH.GREETINGS', '¡Saludos, Honkler!'],
  ['AUTH.SIGN_IN.JOKE', 'Quizás necesitemos volver a'],
  ['AUTH.NO_ACCOUNT_SIGN_UP', '¿No tienes una cuenta? ¡Regístrate ahora!'],
  ['AUTH.HAS_ACCOUNT_SIGN_IN', '¿Ya tienes una cuenta? ¡Inicia sesión ahora!'],
  ['COMMON.FIX_ERROR_BEFORE_CONTINUE', 'Por favor, corrige el error antes de continuar.'],
  ['COMMON.WE_ARE_HONKING', '¡Estamos honking desde 2024!'],
  ['COMMON.BUTTON.OK', 'OK'],
  ['COMMON.BUTTON.CANCEL', 'Cancelar'],
  ['COMMON.BUTTON.PROCEED', 'Continuar'],
  ['COMMON.BUTTON.SAVE', 'Guardar'],
  ['COMMON.BUTTON.UPDATE', 'Actualizar'],
  ['COMMON.BUTTON.HONK', 'Honk'],
  ['COMMON.BUTTON.ADD', 'Añadir'],
  ['COMMON.BUTTON.REMOVE', 'Eliminar'],
  ['COMMON.BUTTON.EDIT', 'Editar'],
  ['COMMON.BUTTON.CREATE', 'Crear'],
  ['COMMON.BUTTON.RESET', 'Restablecer'],
  ['AUTH.SIGN_IN.LOGIN_OR_EMAIL', 'Usuario o correo electrónico'],
  ['COMMON.PASSWORD', 'Contraseña'],
  ['AUTH.SIGN_IN.REMEMBER_ME', 'Recordarme'],
  ['AUTH.FORGOT', '¿Olvidado?'],
  ['AUTH.SIGN_IN.SIGN_IN', 'Iniciar sesión'],
  ['COMMON.EMAIL', 'Correo electrónico'],
  ['COMMON.LOGIN', 'Usuario'],
  ['AUTH.SIGN_UP.WELCOME', '¡Bienvenido a la comunidad Honkler!'],
  ['COMMON.FIRST_NAME', 'Nombre'],
  ['COMMON.LAST_NAME', 'Apellido'],
  ['COMMON.CONFIRM_EMAIL', 'Confirmar correo electrónico'],
  ['COMMON.CONFIRM_PASSWORD', 'Confirmar contraseña'],
  ['COMMON.NO_COMPLAINTS', 'Sin quejas'],
  ['COMMON.SIGN_UP', 'Registrarse'],
  ['PROFILE.EDUCATION.FIELD_OF_STUDY', 'Campo de estudio'],
  ['PROFILE.EDUCATION.INSTITUTION', 'Institución'],
  ['COMMON.DO_NOT_STORE_ANY_SENSITIVE_DATA', 'No almacenes datos sensibles'],
  ['COMMON.START_DATE', 'Fecha de inicio'],
  ['COMMON.END_DATE', 'Fecha de finalización'],
  ['COMMON.ISSUE_DATE', 'Fecha de emisión'],
  ['COMMON.EXPIRATION_DATE', 'Fecha de vencimiento'],
  ['PROFILE.CERTIFICATION.CERTIFICATION', 'Certificación'],
  ['PROFILE.CERTIFICATION.ISSUER', 'Emisor'],
  ['PROFILE.PROJECT.PROJECT', 'Proyecto'],
  ['PROFILE.COMPANY.COMPANY', 'Empresa'],
  ['PROFILE.ACHIEVEMENT.ACHIEVEMENT', 'Logro'],
  ['COMMON.POSITION', 'Cargo'],
  ['COMMON.LOCATION', 'Ubicación'],
  ['COMMON.COUNTRY', 'País'],
  ['JOB_TYPE.JOB_TYPE', 'Tipo de trabajo'],
  ['JOB_TYPE.FULL_TIME', 'Tiempo completo'],
  ['JOB_TYPE.PART_TIME', 'Tiempo parcial'],
  ['JOB_TYPE.CONTRACT', 'Contrato'],
  ['JOB_TYPE.TEMPORARY', 'Temporal'],
  ['JOB_TYPE.INTERN', 'Prácticas'],
  ['JOB_TYPE.VOLUNTEER', 'Voluntario'],
  ['JOB_TYPE.FREELANCE', 'Freelance'],
  ['JOB_TYPE.STARTUP', 'Startup'],
  ['JOB_TYPE.OTHER', 'Otro'],
  ['JOB_TYPE.DISTANCE', 'A distancia'],
  ['JOB_TYPE.EVENING', 'Nocturno'],
  ['JOB_TYPE.ONLINE', 'En línea'],
  ['JOB_TYPE.MIXED', 'Mixto'],
  ['JOB_TYPE.EXCHANGE', 'Intercambio'],
  ['JOB_TYPE.SELF_PACED', 'A tu ritmo'],
  ['JOB_TYPE.IN_PERSON', 'Presencial'],
  ['JOB_TYPE.HYBRID', 'Híbrido'],
  ['JOB_TYPE.PROCTORED_ONLINE', 'En línea supervisado'],
  ['JOB_TYPE.UNPROCTORED', 'Sin supervisión'],
  ['WORK_ARRANGEMENT.WORK_ARRANGEMENT', 'Modalidad de trabajo'],
  ['WORK_ARRANGEMENT.ON_SITE', 'Presencial'],
  ['WORK_ARRANGEMENT.REMOTE', 'Remoto'],
  ['WORK_ARRANGEMENT.HYBRID', 'Híbrido'],
  ['WORK_ARRANGEMENT.FLEXIBLE', 'Flexible'],
  ['WORK_ARRANGEMENT.TRAVEL_REQUIRED', 'Requiere viajes'],
  ['WORK_ARRANGEMENT.SHIFT_BASED', 'Por turnos'],
  ['COMMON.DESCRIPTION', 'Descripción'],
  ['COMMON.SALARY_RANGE', 'Rango salarial'],
  ['COMMON.FROM', 'Desde'],
  ['COMMON.TO', 'Hasta'],
  ['COMMON.SKILLS', 'Habilidades'],
  ['COMMON.SKILL', 'Habilidad'],
  ['EXPERIENCE_LEVEL.EXPERIENCE_LEVEL', 'Nivel de experiencia'],
  ['EXPERIENCE_LEVEL.INTERNSHIP', 'Prácticas'],
  ['EXPERIENCE_LEVEL.ENTRY_LEVEL', 'Nivel inicial'],
  ['EXPERIENCE_LEVEL.JUNIOR', 'Junior'],
  ['EXPERIENCE_LEVEL.MID_LEVEL', 'Nivel medio'],
  ['EXPERIENCE_LEVEL.SENIOR', 'Senior'],
  ['EXPERIENCE_LEVEL.LEADER', 'Líder'],
  ['EXPERIENCE_LEVEL.EXECUTIVE', 'Ejecutivo'],
  ['EXPERIENCE_LEVEL.PRINCIPAL', 'Principal'],
  ['EXPERIENCE_LEVEL.STAFF', 'Personal'],
  ['EXPERIENCE_LEVEL.OTHER', 'Otro'],
  ['EXPERIENCE_LEVEL.TIER_1', 'Nivel 1'],
  ['EXPERIENCE_LEVEL.TIER_2', 'Nivel 2'],
  ['EXPERIENCE_LEVEL.TIER_3', 'Nivel 3'],
  ['EXPERIENCE_LEVEL.TIER_4', 'Nivel 4'],
  ['EXPERIENCE_LEVEL.TIER_5', 'Nivel 5'],
  ['EXPERIENCE_LEVEL.TIER_6', 'Nivel 6'],
  ['EXPERIENCE_LEVEL.TIER_7', 'Nivel 7'],
  ['COMMON.LANGUAGES', 'Idiomas'],
  ['COMMON.LANGUAGE', 'Idioma'],
  ['LANGUAGE_LEVEL.LANGUAGE_LEVEL', 'Nivel de idioma'],
  ['LANGUAGE_LEVEL.BEGINNER', 'Principiante'],
  ['LANGUAGE_LEVEL.ELEMENTARY', 'Elemental'],
  ['LANGUAGE_LEVEL.INTERMEDIATE', 'Intermedio'],
  ['LANGUAGE_LEVEL.UPPER_INTERMEDIATE', 'Intermedio alto'],
  ['LANGUAGE_LEVEL.ADVANCED', 'Avanzado'],
  ['LANGUAGE_LEVEL.PROFICIENT', 'Competente'],
  ['LANGUAGE_LEVEL.NATIVE', 'Nativo'],
  ['PROFILE.SECTION.PRIMARY_INFO', 'Información principal'],
  ['PROFILE.SECTION.AUTH_SECTION', 'Sección de autenticación'],
  ['PROFILE.HEADLINE', 'Título'],
  ['PROFILE.SECTION.SECONDARY_INFO', 'Información secundaria'],
  ['COMMON.CURRENCY', 'Moneda'],
  ['COMMON.TIME_ZONE', 'Zona horaria'],
  ['COMMON.PHONE', 'Teléfono'],
  ['PROFILE.LINKS', 'Enlaces'],
  ['PROFILE.SECTION.AI', 'IA'],
  ['PROFILE.APPLICATION.AI_TEXTAREA', 'Área de texto de IA para solicitudes'],
  ['THEME.DARK', 'Tema oscuro'],
  ['THEME.LIGHT', 'Tema claro'],
  ['MENU.HOME', 'Inicio'],
  ['MENU.JOBS', 'Empleos'],
  ['MENU.COMPANIES', 'Empresas'],
  ['MENU.KARMA', 'Karma'],
  ['IN_DEVELOPMENT.OOPS_PAGE', '¡Ups! Página en construcción.'],
  ['COMMON.GO_HOME', 'Ir al inicio'],
  ['COMMON.BACK_TO_SIGN_IN', 'Volver a iniciar sesión'],
  ['NOT_FOUND.PAGE_NOT_FOUND', '¡Ups! La página que buscas no existe.'],
  ['MENU.ACTIVE_APPLICATIONS', 'Solicitudes activas'],
  ['MENU.TODOS', 'Tareas pendientes'],
  ['MENU.RESPONSE_RATE', 'Tasa de respuesta'],
  ['MENU.UPCOMING_INTERVIEWS', 'Entrevistas próximas'],
  ['STATS.NEW_JOB_LISTINGS_PER_DAY', 'Nuevas ofertas por día'],
  ['STATS.JOB_APPLICATIONS_TREND', 'Tendencia de solicitudes'],
  ['COMMON.JOB.NEW_APPLICATION', 'Solicitud de empleo'],
  ['COMMON.JOB.NEW_APPLICATIONS', 'Solicitudes de empleo'],
  ['STATS.TOP_COMPANIES', 'Empresas principales'],
  ['STATS.APPLICATION_STATUS_DISTRIBUTION', 'Distribución del estado de solicitudes'],
  ['JOB_STATUS.APPLIED', 'Aplicado'],
  ['JOB_STATUS.IN_REVIEW', 'En revisión'],
  ['JOB_STATUS.INTERVIEW', 'Entrevista'],
  ['JOB_STATUS.OFFER', 'Oferta'],
  ['JOB_STATUS.REJECTED', 'Rechazado'],
  ['COMMON.WELCOME_BACK', '¡Bienvenido de nuevo!'],
  ['PROFILE.SECTION.WORK_EXPERIENCE', 'Experiencia laboral'],
  ['PROFILE.SECTION.EDUCATION', 'Educación'],
  ['PROFILE.SECTION.PROJECTS', 'Proyectos'],
  ['PROFILE.SECTION.ACHIEVEMENTS', 'Logros'],
  ['PROFILE.SECTION.CERTIFICATIONS', 'Certificaciones'],
  ['COMMON.EMPTY_SECTION', 'Sección vacía'],
  ['PROFILE.USER_PREFERENCES', 'Preferencias del usuario'],
  ['ERROR.NOT_FOUND', 'No encontrado'],
  ['ERROR.ENTITY_NOT_FOUND', 'Entidad no encontrada'],
  ['ERROR.ENTITY_WITH_ID_NOT_FOUND', 'Entidad con ID no encontrada'],
  ['ERROR.ENTITY_WITH_EMAIL_ALREADY_EXISTS', 'Entidad con correo electrónico ya existe'],
  ['ERROR.ENTITY_WITH_LOGIN_ALREADY_EXISTS', 'Entidad con usuario ya existe'],
  ['ERROR.VALIDATION_ERROR', 'Error de validación'],
  ['ERROR.ENTITY_ALREADY_EXISTS', 'Entidad ya existe'],
  ['ERROR.ALREADY_EXISTS', 'Ya existe'],
  ['ERROR.INTERNAL_SERVER_ERROR', 'Error interno del servidor'],
  ['ERROR.BLOCKED', 'Bloqueado'],
  ['ERROR.RESOURCE_NOT_FOUND', 'Recurso no encontrado'],
  ['ERROR.ENTITY_BLOCKED', 'Entidad bloqueada'],
  ['ERROR.ENTITY_PESSIMISTIC_LOCKED', 'Entidad bloqueada'],
  ['ERROR.WRONG_AUTH', 'Autenticación incorrecta'],
  ['ERROR.FORBIDDEN', 'Prohibido'],
  ['ERROR.USER_BLOCKED', 'Usuario bloqueado'],
  ['ERROR.POTENTIAL_HARMFUL_CONTENT', 'Contenido potencialmente dañino'],
  ['ERROR.JWT_MIN_LENGTH', 'Longitud mínima de JWT'],
  ['ERROR.JWT_INVALID_FORMAT', 'Formato de JWT inválido'],
  ['ERROR.JWT_USER_CLAIM_NOT_FOUND', 'Reclamación de usuario JWT no encontrada'],
  ['ERROR.JWT_USER_CLAIM_INVALID_CONVERSION', 'Conversión inválida de reclamación de usuario JWT'],
  ['ERROR.FORGOT_PASSWORD_REQUEST_TOO_SOON', 'Solicitud de contraseña olvidada demasiado pronto'],
  ['ERROR.RESTORE_PASSWORD_PROCESSING_ISSUE', 'Problema al procesar la restauración de contraseña'],
  ['ERROR.VERSION_NOT_SPECIFIED', 'Versión no especificada'],
  ['ERROR.VERSION_NOT_SUPPORTED', 'Versión no soportada'],
  ['ERROR.UPDATE_ONLY_OWN_SETTINGS', 'Actualizar solo configuraciones propias'],
  ['ERROR.INVALID_URL', 'URL inválida'],
  ['ERROR.URL_NOT_HTTPS', 'URL no es HTTPS'],
  ['ERROR.UNKNOWN_URL_TYPE', 'Tipo de URL desconocido'],
  ['ENTITY.STATUS.NEW', 'Nuevo'],
  ['ENTITY.STATUS.ACTIVE', 'Activo'],
  ['ENTITY.STATUS.INACTIVE', 'Inactivo'],
  ['ENTITY.STATUS.BLOCKED', 'Bloqueado'],
  ['ENTITY.STATUS.DELETED', 'Eliminado'],
  ['ENTITY.STATUS.PENDING', 'Pendiente'],
  ['ENTITY.STATUS.APPROVED', 'Aprobado'],
  ['ENTITY.STATUS.REJECTED', 'Rechazado'],
  ['ENTITY.STATUS.COMPLETED', 'Completado'],
  ['ENTITY.STATUS.CANCELLED', 'Cancelado'],
  ['ENTITY.STATUS.ARCHIVED', 'Archivado'],
  ['MESSAGES.CHANGES_SUCCESSFULLY_SAVED', 'Cambios guardados exitosamente'],
  ['DATES.JANUARY_SHORT', 'Ene'],
  ['DATES.FEBRUARY_SHORT', 'Feb'],
  ['DATES.MARCH_SHORT', 'Mar'],
  ['DATES.APRIL_SHORT', 'Abr'],
  ['DATES.MAY_SHORT', 'May'],
  ['DATES.JUNE_SHORT', 'Jun'],
  ['DATES.JULY_SHORT', 'Jul'],
  ['DATES.AUGUST_SHORT', 'Ago'],
  ['DATES.SEPTEMBER_SHORT', 'Sep'],
  ['DATES.OCTOBER_SHORT', 'Oct'],
  ['DATES.NOVEMBER_SHORT', 'Nov'],
  ['DATES.DECEMBER_SHORT', 'Dic'],
  ['DATES.MONDAY_SHORT', 'Lun'],
  ['DATES.TUESDAY_SHORT', 'Mar'],
  ['DATES.WEDNESDAY_SHORT', 'Mié'],
  ['DATES.THURSDAY_SHORT', 'Jue'],
  ['DATES.FRIDAY_SHORT', 'Vie'],
  ['DATES.SATURDAY_SHORT', 'Sáb'],
  ['DATES.SUNDAY_SHORT', 'Dom'],
  ['INPUT.TOO_MANY_ITEMS_START_TYPING', 'Demasiados elementos, comienza a escribir...'],
  ['ERROR.FIELD_REQUIRED', 'El campo es requerido'],
  ['ERROR.CHECK_CHECKBOX', 'Marcar casilla'],
  ['ERROR.INVALID_EMAIL', 'Correo electrónico inválido'],
  ['JOB_SOURCE.JOB_BOARD', 'Tablero de empleos'],
  ['JOB_SOURCE.COMPANY_WEBSITE', 'Sitio web de la empresa'],
  ['JOB_SOURCE.RECOMMENDATION', 'Recomendación'],
  ['JOB_SOURCE.SOCIAL_MEDIA', 'Redes sociales'],
  ['JOB_SOURCE.OTHER', 'Otro'],
  ['ROLE.ROLE', 'Rol'],
  ['ROLE.USER', 'Usuario'],
  ['ROLE.TECHNICAL_SUPPORT', 'Soporte técnico'],
  ['ROLE.ADMIN', 'Administrador'],
  ['ROLE.SUPER_ADMIN', 'Super administrador'],
  ['COMMON.JOB_TITLE', 'Título del trabajo'],
  ['COMMON.SOURCE', 'Fuente'],
  ['COMMON.POSTED_DATE', 'Fecha de publicación'],
  ['COMMON.DEADLINE', 'Fecha límite'],
  ['COMMON.CONTACT_EMAIL', 'Email de contacto'],
  ['APPLICATION.APPLICATION_LINK', 'Enlace de la solicitud'],
  ['COMMON.NOTES', 'Notas'],
  ['SKILL_LEVEL.SKILL_LEVEL', 'Nivel de habilidad'],
  ['SKILL_LEVEL.BEGINNER', 'Principiante'],
  ['SKILL_LEVEL.BASIC', 'Básico'],
  ['SKILL_LEVEL.INTERMEDIATE', 'Intermedio'],
  ['SKILL_LEVEL.ADVANCED', 'Avanzado'],
  ['SKILL_LEVEL.EXPERT', 'Experto'],
  ['SKILL_LEVEL.MASTER', 'Maestro'],
  ['SKILL_LEVEL.WORLD_CLASS', 'Clase mundial'],
  ['PROFILE.SHOW_CURRENT_POSITION', 'Mostrar posición actual'],
  ['PROFILE.SHOW_HIGHEST_EDUCATION', 'Mostrar educación más alta'],
]);
