// Auto-generated file from a6-localizations_de.csv

export const localization_de: Map<string, string> = new Map<string, string>([
  ['AUTH.GREETINGS', 'Hallo, lieber Honkler!'],
  ['AUTH.SIGN_IN.JOKE', 'Vielleicht müssen wir zurück zu'],
  ['AUTH.NO_ACCOUNT_SIGN_UP', 'Kein Konto? Jetzt registrieren!'],
  ['AUTH.HAS_ACCOUNT_SIGN_IN', 'Bereits ein Konto? Jetzt anmelden!'],
  ['COMMON.FIX_ERROR_BEFORE_CONTINUE', 'Bitte beheben Sie den Fehler, bevor Sie fortfahren.'],
  ['COMMON.WE_ARE_HONKING', 'Wir honken seit 2025!'],
  ['COMMON.BUTTON.OK', 'OK'],
  ['COMMON.BUTTON.CANCEL', 'Abbrechen'],
  ['COMMON.BUTTON.PROCEED', 'Fortfahren'],
  ['COMMON.BUTTON.SAVE', 'Speichern'],
  ['COMMON.BUTTON.UPDATE', 'Aktualisieren'],
  ['COMMON.BUTTON.HONK', 'Honk'],
  ['COMMON.BUTTON.ADD', 'Hinzufügen'],
  ['COMMON.BUTTON.REMOVE', 'Entfernen'],
  ['COMMON.BUTTON.EDIT', 'Bearbeiten'],
  ['COMMON.BUTTON.CREATE', 'Erstellen'],
  ['COMMON.BUTTON.RESET', 'Zurücksetzen'],
  ['AUTH.SIGN_IN.LOGIN_OR_EMAIL', 'Benutzername oder E-Mail'],
  ['COMMON.PASSWORD', 'Passwort'],
  ['AUTH.SIGN_IN.REMEMBER_ME', 'Angemeldet bleiben'],
  ['AUTH.FORGOT', 'Vergessen?'],
  ['AUTH.SIGN_IN.SIGN_IN', 'Anmelden'],
  ['COMMON.EMAIL', 'E-Mail'],
  ['COMMON.LOGIN', 'Benutzername'],
  ['AUTH.SIGN_UP.WELCOME', 'Willkommen in der Honkler-Community!'],
  ['COMMON.FIRST_NAME', 'Vorname'],
  ['COMMON.LAST_NAME', 'Nachname'],
  ['COMMON.CONFIRM_EMAIL', 'E-Mail bestätigen'],
  ['COMMON.CONFIRM_PASSWORD', 'Passwort bestätigen'],
  ['COMMON.NO_COMPLAINTS', 'Keine Beschwerden'],
  ['COMMON.SIGN_UP', 'Registrieren'],
  ['PROFILE.EDUCATION.FIELD_OF_STUDY', 'Studienfach'],
  ['PROFILE.EDUCATION.INSTITUTION', 'Bildungseinrichtung'],
  ['COMMON.DO_NOT_STORE_ANY_SENSITIVE_DATA', 'Speichern Sie keine sensiblen Daten'],
  ['COMMON.START_DATE', 'Startdatum'],
  ['COMMON.END_DATE', 'Enddatum'],
  ['COMMON.ISSUE_DATE', 'Ausstellungsdatum'],
  ['COMMON.EXPIRATION_DATE', 'Ablaufdatum'],
  ['PROFILE.CERTIFICATION.CERTIFICATION', 'Zertifizierung'],
  ['PROFILE.CERTIFICATION.ISSUER', 'Aussteller'],
  ['PROFILE.PROJECT.PROJECT', 'Projekt'],
  ['PROFILE.COMPANY.COMPANY', 'Unternehmen'],
  ['PROFILE.ACHIEVEMENT.ACHIEVEMENT', 'Leistung'],
  ['COMMON.POSITION', 'Position'],
  ['COMMON.LOCATION', 'Standort'],
  ['COMMON.COUNTRY', 'Land'],
  ['JOB_TYPE.JOB_TYPE', 'Anstellungsart'],
  ['JOB_TYPE.FULL_TIME', 'Vollzeit'],
  ['JOB_TYPE.PART_TIME', 'Teilzeit'],
  ['JOB_TYPE.CONTRACT', 'Vertrag'],
  ['JOB_TYPE.TEMPORARY', 'Befristet'],
  ['JOB_TYPE.INTERN', 'Praktikum'],
  ['JOB_TYPE.VOLUNTEER', 'Ehrenamtlich'],
  ['JOB_TYPE.FREELANCE', 'Freiberuflich'],
  ['JOB_TYPE.STARTUP', 'Startup'],
  ['JOB_TYPE.OTHER', 'Sonstiges'],
  ['JOB_TYPE.DISTANCE', 'Fernarbeit'],
  ['JOB_TYPE.EVENING', 'Abend'],
  ['JOB_TYPE.ONLINE', 'Online'],
  ['JOB_TYPE.MIXED', 'Gemischt'],
  ['JOB_TYPE.EXCHANGE', 'Austausch'],
  ['JOB_TYPE.SELF_PACED', 'Eigenes Tempo'],
  ['JOB_TYPE.IN_PERSON', 'Präsenz'],
  ['JOB_TYPE.HYBRID', 'Hybrid'],
  ['JOB_TYPE.PROCTORED_ONLINE', 'Online mit Aufsicht'],
  ['JOB_TYPE.UNPROCTORED', 'Ohne Aufsicht'],
  ['WORK_ARRANGEMENT.WORK_ARRANGEMENT', 'Arbeitsmodell'],
  ['WORK_ARRANGEMENT.ON_SITE', 'Vor Ort'],
  ['WORK_ARRANGEMENT.REMOTE', 'Remote'],
  ['WORK_ARRANGEMENT.HYBRID', 'Hybrid'],
  ['WORK_ARRANGEMENT.FLEXIBLE', 'Flexibel'],
  ['WORK_ARRANGEMENT.TRAVEL_REQUIRED', 'Reisen erforderlich'],
  ['WORK_ARRANGEMENT.SHIFT_BASED', 'Schichtarbeit'],
  ['COMMON.DESCRIPTION', 'Beschreibung'],
  ['COMMON.SALARY_RANGE', 'Gehaltsbereich'],
  ['COMMON.FROM', 'Von'],
  ['COMMON.TO', 'Bis'],
  ['COMMON.SKILLS', 'Fähigkeiten'],
  ['COMMON.SKILL', 'Fähigkeit'],
  ['EXPERIENCE_LEVEL.EXPERIENCE_LEVEL', 'Erfahrungsstufe'],
  ['EXPERIENCE_LEVEL.INTERNSHIP', 'Praktikum'],
  ['EXPERIENCE_LEVEL.ENTRY_LEVEL', 'Einsteiger'],
  ['EXPERIENCE_LEVEL.JUNIOR', 'Junior'],
  ['EXPERIENCE_LEVEL.MID_LEVEL', 'Mittelstufe'],
  ['EXPERIENCE_LEVEL.SENIOR', 'Senior'],
  ['EXPERIENCE_LEVEL.LEADER', 'Leitung'],
  ['EXPERIENCE_LEVEL.EXECUTIVE', 'Führungskraft'],
  ['EXPERIENCE_LEVEL.PRINCIPAL', 'Hauptverantwortlicher'],
  ['EXPERIENCE_LEVEL.STAFF', 'Mitarbeiter'],
  ['EXPERIENCE_LEVEL.OTHER', 'Sonstiges'],
  ['EXPERIENCE_LEVEL.TIER_1', 'Stufe 1'],
  ['EXPERIENCE_LEVEL.TIER_2', 'Stufe 2'],
  ['EXPERIENCE_LEVEL.TIER_3', 'Stufe 3'],
  ['EXPERIENCE_LEVEL.TIER_4', 'Stufe 4'],
  ['EXPERIENCE_LEVEL.TIER_5', 'Stufe 5'],
  ['EXPERIENCE_LEVEL.TIER_6', 'Stufe 6'],
  ['EXPERIENCE_LEVEL.TIER_7', 'Stufe 7'],
  ['COMMON.LANGUAGES', 'Sprachen'],
  ['COMMON.LANGUAGE', 'Sprache'],
  ['LANGUAGE_LEVEL.LANGUAGE_LEVEL', 'Sprachniveau'],
  ['LANGUAGE_LEVEL.BEGINNER', 'Anfänger'],
  ['LANGUAGE_LEVEL.ELEMENTARY', 'Grundstufe'],
  ['LANGUAGE_LEVEL.INTERMEDIATE', 'Mittelstufe'],
  ['LANGUAGE_LEVEL.UPPER_INTERMEDIATE', 'Obere Mittelstufe'],
  ['LANGUAGE_LEVEL.ADVANCED', 'Fortgeschritten'],
  ['LANGUAGE_LEVEL.PROFICIENT', 'Fließend'],
  ['LANGUAGE_LEVEL.NATIVE', 'Muttersprache'],
  ['PROFILE.SECTION.PRIMARY_INFO', 'Hauptinformationen'],
  ['PROFILE.SECTION.AUTH_SECTION', 'Authentifizierungsbereich'],
  ['PROFILE.HEADLINE', 'Überschrift'],
  ['PROFILE.SECTION.SECONDARY_INFO', 'Zusätzliche Informationen'],
  ['COMMON.CURRENCY', 'Währung'],
  ['COMMON.TIME_ZONE', 'Zeitzone'],
  ['COMMON.PHONE', 'Telefon'],
  ['PROFILE.LINKS', 'Links'],
  ['PROFILE.SECTION.AI', 'KI'],
  ['PROFILE.APPLICATION.AI_TEXTAREA', 'KI-Textfeld für Bewerbung'],
  ['THEME.DARK', 'Dunkles Design'],
  ['THEME.LIGHT', 'Helles Design'],
  ['MENU.HOME', 'Startseite'],
  ['MENU.JOBS', 'Stellen'],
  ['MENU.COMPANIES', 'Unternehmen'],
  ['MENU.KARMA', 'Karma'],
  ['IN_DEVELOPMENT.OOPS_PAGE', 'Ups! Seite im Aufbau.'],
  ['COMMON.GO_HOME', 'Zur Startseite'],
  ['COMMON.BACK_TO_SIGN_IN', 'Zurück zur Anmeldung'],
  ['NOT_FOUND.PAGE_NOT_FOUND', 'Ups! Die gesuchte Seite existiert nicht.'],
  ['MENU.ACTIVE_APPLICATIONS', 'Aktive Bewerbungen'],
  ['MENU.TODOS', 'Aufgaben'],
  ['MENU.RESPONSE_RATE', 'Antwortrate'],
  ['MENU.UPCOMING_INTERVIEWS', 'Kommende Vorstellungsgespräche'],
  ['STATS.NEW_JOB_LISTINGS_PER_DAY', 'Neue Stellenangebote pro Tag'],
  ['STATS.JOB_APPLICATIONS_TREND', 'Trend der Bewerbungen'],
  ['COMMON.JOB.NEW_APPLICATION', 'Stellenbewerbung'],
  ['COMMON.JOB.NEW_APPLICATIONS', 'Stellenbewerbungen'],
  ['STATS.TOP_COMPANIES', 'Top-Unternehmen'],
  ['STATS.APPLICATION_STATUS_DISTRIBUTION', 'Verteilung der Bewerbungsstatus'],
  ['JOB_STATUS.APPLIED', 'Beworben'],
  ['JOB_STATUS.IN_REVIEW', 'In Prüfung'],
  ['JOB_STATUS.INTERVIEW', 'Vorstellungsgespräch'],
  ['JOB_STATUS.OFFER', 'Angebot'],
  ['JOB_STATUS.REJECTED', 'Abgelehnt'],
  ['COMMON.WELCOME_BACK', 'Willkommen zurück'],
  ['PROFILE.SECTION.WORK_EXPERIENCE', 'Berufserfahrung'],
  ['PROFILE.SECTION.EDUCATION', 'Bildung'],
  ['PROFILE.SECTION.PROJECTS', 'Projekte'],
  ['PROFILE.SECTION.ACHIEVEMENTS', 'Erfolge'],
  ['PROFILE.SECTION.CERTIFICATIONS', 'Zertifizierungen'],
  ['COMMON.EMPTY_SECTION', 'Leerer Bereich'],
  ['PROFILE.USER_PREFERENCES', 'Benutzereinstellungen'],
  ['ERROR.NOT_FOUND', 'Nicht gefunden'],
  ['ERROR.ENTITY_NOT_FOUND', 'Objekt nicht gefunden'],
  ['ERROR.ENTITY_WITH_ID_NOT_FOUND', 'Objekt mit ID nicht gefunden'],
  ['ERROR.ENTITY_WITH_EMAIL_ALREADY_EXISTS', 'Objekt mit dieser E-Mail existiert bereits'],
  ['ERROR.ENTITY_WITH_LOGIN_ALREADY_EXISTS', 'Objekt mit diesem Benutzernamen existiert bereits'],
  ['ERROR.VALIDATION_ERROR', 'Validierungsfehler'],
  ['ERROR.ENTITY_ALREADY_EXISTS', 'Objekt existiert bereits'],
  ['ERROR.ALREADY_EXISTS', 'Bereits vorhanden'],
  ['ERROR.INTERNAL_SERVER_ERROR', 'Interner Serverfehler'],
  ['ERROR.BLOCKED', 'Gesperrt'],
  ['ERROR.RESOURCE_NOT_FOUND', 'Ressource nicht gefunden'],
  ['ERROR.ENTITY_BLOCKED', 'Objekt gesperrt'],
  ['ERROR.ENTITY_PESSIMISTIC_LOCKED', 'Objekt ist gesperrt'],
  ['ERROR.WRONG_AUTH', 'Falsche Authentifizierung'],
  ['ERROR.FORBIDDEN', 'Verboten'],
  ['ERROR.USER_BLOCKED', 'Benutzer gesperrt'],
  ['ERROR.POTENTIAL_HARMFUL_CONTENT', 'Potentiell schädlicher Inhalt'],
  ['ERROR.JWT_MIN_LENGTH', 'Minimale JWT-Länge'],
  ['ERROR.JWT_INVALID_FORMAT', 'Ungültiges JWT-Format'],
  ['ERROR.JWT_USER_CLAIM_NOT_FOUND', 'JWT-Benutzeranspruch nicht gefunden'],
  ['ERROR.JWT_USER_CLAIM_INVALID_CONVERSION', 'Ungültige Konvertierung des JWT-Benutzeranspruchs'],
  ['ERROR.FORGOT_PASSWORD_REQUEST_TOO_SOON', 'Passwort vergessen-Anfrage zu früh'],
  ['ERROR.RESTORE_PASSWORD_PROCESSING_ISSUE', 'Problem bei der Passwortwiederherstellung'],
  ['ERROR.VERSION_NOT_SPECIFIED', 'Version nicht angegeben'],
  ['ERROR.VERSION_NOT_SUPPORTED', 'Version nicht unterstützt'],
  ['ERROR.UPDATE_ONLY_OWN_SETTINGS', 'Nur eigene Einstellungen aktualisieren'],
  ['ERROR.INVALID_URL', 'Ungültige URL'],
  ['ERROR.URL_NOT_HTTPS', 'URL nicht HTTPS'],
  ['ERROR.UNKNOWN_URL_TYPE', 'Unbekannter URL-Typ'],
  ['ENTITY.STATUS.NEW', 'Neu'],
  ['ENTITY.STATUS.ACTIVE', 'Aktiv'],
  ['ENTITY.STATUS.INACTIVE', 'Inaktiv'],
  ['ENTITY.STATUS.BLOCKED', 'Gesperrt'],
  ['ENTITY.STATUS.DELETED', 'Gelöscht'],
  ['ENTITY.STATUS.PENDING', 'Ausstehend'],
  ['ENTITY.STATUS.APPROVED', 'Genehmigt'],
  ['ENTITY.STATUS.REJECTED', 'Abgelehnt'],
  ['ENTITY.STATUS.COMPLETED', 'Abgeschlossen'],
  ['ENTITY.STATUS.CANCELLED', 'Abgebrochen'],
  ['ENTITY.STATUS.ARCHIVED', 'Archiviert'],
  ['MESSAGES.CHANGES_SUCCESSFULLY_SAVED', 'Änderungen erfolgreich gespeichert'],
  ['DATES.JANUARY_SHORT', 'Jan'],
  ['DATES.FEBRUARY_SHORT', 'Feb'],
  ['DATES.MARCH_SHORT', 'Mär'],
  ['DATES.APRIL_SHORT', 'Apr'],
  ['DATES.MAY_SHORT', 'Mai'],
  ['DATES.JUNE_SHORT', 'Jun'],
  ['DATES.JULY_SHORT', 'Jul'],
  ['DATES.AUGUST_SHORT', 'Aug'],
  ['DATES.SEPTEMBER_SHORT', 'Sep'],
  ['DATES.OCTOBER_SHORT', 'Okt'],
  ['DATES.NOVEMBER_SHORT', 'Nov'],
  ['DATES.DECEMBER_SHORT', 'Dez'],
  ['DATES.MONDAY_SHORT', 'Mo'],
  ['DATES.TUESDAY_SHORT', 'Di'],
  ['DATES.WEDNESDAY_SHORT', 'Mi'],
  ['DATES.THURSDAY_SHORT', 'Do'],
  ['DATES.FRIDAY_SHORT', 'Fr'],
  ['DATES.SATURDAY_SHORT', 'Sa'],
  ['DATES.SUNDAY_SHORT', 'So'],
  ['INPUT.TOO_MANY_ITEMS_START_TYPING', 'Zu viele Elemente, beginnen Sie zu tippen...'],
  ['ERROR.FIELD_REQUIRED', 'Feld ist erforderlich'],
  ['ERROR.CHECK_CHECKBOX', 'Kontrollkästchen aktivieren'],
  ['ERROR.INVALID_EMAIL', 'Ungültige E-Mail'],
  ['JOB_SOURCE.JOB_BOARD', 'Stellenbörse'],
  ['JOB_SOURCE.COMPANY_WEBSITE', 'Unternehmenswebsite'],
  ['JOB_SOURCE.RECOMMENDATION', 'Empfehlung'],
  ['JOB_SOURCE.SOCIAL_MEDIA', 'Soziale Medien'],
  ['JOB_SOURCE.OTHER', 'Andere'],
  ['ROLE.ROLE', 'Rolle'],
  ['ROLE.USER', 'Benutzer'],
  ['ROLE.TECHNICAL_SUPPORT', 'Technischer Support'],
  ['ROLE.ADMIN', 'Administrator'],
  ['ROLE.SUPER_ADMIN', 'Super Administrator'],
]);
