// Auto-generated file from a5-localizations_ru.csv

export const localization_ru: Map<string, string> = new Map<string, string>([
  [`AUTH.GREETINGS`, `Приветствую тебя, Хонклер!`],
  [`AUTH.SIGN_IN.JOKE`, `Может быть, нам нужно вернуться к`],
  [`COMMON.LOGIN_OR_EMAIL`, `Логин или электронная почта`],
  [`COMMON.PASSWORD`, `Пароль`],
  [`COMMON.CONFIRM_PASSWORD`, `Пароль`],
  [`COMMON.REMEMBER_ME`, `Запомнить меня`],
  [`COMMON.FORGOT`, `Забыли`],
  [`COMMON.SIGN_IN`, `Войти`],
  [`COMMON.SIGN_UP`, `Зарегистрироваться`],
  [`AUTH.NO_ACCOUNT.SIGN_UP`, `У вас нет учетной записи? Зарегистрироваться`],
  [`AUTH.HAS_ACCOUNT.SIGN_IN`, `У вас уже есть аккаунт? Войти`],
  [`COMMON.LOGIN`, `Вход`],
  [`COMMON.EMAIL`, `Электронная почта`],
  [`COMMON.CONFIRM_EMAIL`, `Подтвердить электронную почту`],
  [`COMMON.PROCEED`, `Пройдите по ссылке`],
  [`COMMON.FIRST_NAME`, `Имя`],
  [`COMMON.LAST_NAME`, `Последнее имя`],
  [`COMMON.NO_COMPLAINTS`, `Нет жалоб`],
  [`COMMON.WE_ARE_HONKING`, `Мы хонкаем с 2024 года!`],
  [`COMMON.DO_NOT_STORE_SENS_DATA`, `НЕ ХРАНИТЕ ЗДЕСЬ КОНФИДЕНЦИАЛЬНЫЕ ДАННЫЕ!`],
  [`COMMON.LIGHT_THEME`, `Светлая тема`],
  [`COMMON.DARK_THEME`, `Темная тема`],
  [`ERROR.PASSWORDS_DO_NOT_MATCH`, `Пароли не совпадают`],
  [`ERROR.EMAILS_DO_NOT_MATCH`, `Электронная почта не совпадает`],
  [`ERROR.FIELD_REQUIRED`, `Это поле обязательно для заполнения!`],
  [`ERROR.CHECK_CHECKBOX`, `Пожалуйста, отметьте это поле!`],
  [`ERROR.INVALID_EMAIL`, `Неверный формат электронной почты!`],
  [`MENU.HOME`, `Главная`],
  [`MENU.JOBS`, `Вакансии`],
  [`MENU.COMPANIES`, `Компании`],
  [`MENU.KARMA`, `Карма`],
  [`COMMON.WELCOME_BACK`, `Добро пожаловать обратно`],
  [`MENU.ACTIVE_APPLICATIONS`, `Активные приложения`],
  [`MENU.TODOS`, `TODOs`],
  [`MENU.RESPONSE_RATE`, `Скорость реакции`],
  [`MENU.UPCOMING_INTERVIEWS`, `Предстоящие собеседования`],
  [`COMMON.NEW_APPLICATION`, `Новые заявки`],
  [`STATS.JOB_APPLICATIONS_TREND`, `Тренд по количеству заявок на работу`],
  [`STATS.TOP_COMPANIES`, `Лучшие компании (заявки)`],
  [`STATS.NEW_JOB_LISTINGS_PER_DAY`, `Новые объявления о вакансиях в день`],
  [`STATS.APPLICATION_STATUS_DISTRIBUTION`, `Распределение статусов заявок`],
  [`STATUS.APPLIED`, `Подано`],
  [`STATUS.REJECTED`, `Отклонено`],
  [`STATUS.OFFER`, `Предложение`],
  [`STATUS.INTERVIEW`, `Собеседование`],
  [`STATUS.IN_REVIEW`, `На рассмотрении`],
  [`COMMON.CREATE`, `Создать`],
  [`COMMON.EDIT`, `Редактировать`],
  [`COMMON.APPLICATION_LINK`, `Ссылка на приложение`],
  [`COMMON.JOB_TITLE`, `Название вакансии`],
  [`COMMON.COMPANY`, `Компания`],
  [`COMMON.LOCATION`, `Месторасположение`],
  [`COMMON.EXPERIENCE_LEVEL`, `Уровень опыта`],
  [`COMMON.JOB_TYPE`, `Тип работы`],
  [`COMMON.SOURCE`, `Источник`],
  [`COMMON.SALARY_RANGE`, `Диапазон заработной платы`],
  [`COMMON.FROM`, `От`],
  [`COMMON.TO`, `До`],
  [`COMMON.CURRENCY`, `Валюта`],
  [`COMMON.POSTED_DATE`, `Дата публикации`],
  [`COMMON.APPLICATION_DEADLINE`, `Крайний срок подачи заявки`],
  [`COMMON.Contact_EMAIL`, `Контактный Email`],
  [`COMMON.DESCRIPTION`, `Описание`],
  [`COMMON.NOTES`, `Примечания`],
  [`COMMON.CANCEL`, `Отменить`],
  [`COMMON.UPDATE`, `Обновить`],
  [`COMMON.EDIT_PROFILE`, `Редактировать профиль`],
  [`COMMON.EDIT_SKILLS`, `Редактировать навыки`],
  [`COMMON.ADD_EXPERIENCE`, `Добавить опыт`],
  [`COMMON.SKILLS`, `Навыки`],
  [`COMMON.EXPERIENCE`, `Опыт работы`],
  [`COMMON.EDUCATION`, `Образование`],
  [`COMMON.CERTIFICATIONS`, `Сертификаты`],
  [`ROLE.USER`, `Пользователь`],
  [`ROLE.TECHNICAL_SUPPORT`, `Техническая поддержка`],
  [`ROLE.ADMIN`, `Администратор`],
  [`ROLE.SUPER_ADMIN`, `Супер Администратор`],
  [`JOB_TYPE.FULL_TIME`, `Полная занятость`],
  [`JOB_TYPE.PART_TIME`, `Неполный рабочий день`],
  [`JOB_TYPE.CONTRACT`, `Контракт`],
  [`JOB_TYPE.TEMPORARY`, `Временно`],
  [`JOB_TYPE.INTERN`, `Стажер`],
  [`JOB_TYPE.VOLUNTEER`, `Волонтер`],
  [`JOB_TYPE.FREELANCE`, `Фриланс`],
  [`JOB_TYPE.STARTUP`, `Стартап`],
  [`JOB_TYPE.OTHER`, `Другое`],
  [`JOB_SOURCE.JOB_BOARD`, `Доска объявлений о работе`],
  [`JOB_SOURCE.COMPANY_WEBSITE`, `Сайт компании`],
  [`JOB_SOURCE.RECOMMENDATION`, `Рекомендация`],
  [`JOB_SOURCE.OTHER`, `Другие`],
  [`EXPERIENCE_LEVEL.INTERNSHIP`, `Стажировка`],
  [`EXPERIENCE_LEVEL.ENTRY_LEVEL`, `Начальный уровень`],
  [`EXPERIENCE_LEVEL.JUNIOR`, `Младший`],
  [`EXPERIENCE_LEVEL.MID_LEVEL`, `Средний уровень`],
  [`EXPERIENCE_LEVEL.SENIOR`, `Старший`],
  [`EXPERIENCE_LEVEL.EXECUTIVE`, `Руководитель`],
  [`COMMON.APPLICATIONS`, `Приложения`],
  [`DATES.JANUARY_SHORT`, `Янв`],
  [`DATES.FEBRUARY_SHORT`, `Фев`],
  [`DATES.MARCH_SHORT`, `Мар`],
  [`DATES.APRIL_SHORT`, `Апр`],
  [`DATES.MAY_SHORT`, `Май`],
  [`DATES.JUNE_SHORT`, `Июн`],
  [`DATES.JULY_SHORT`, `Июл`],
  [`DATES.AUGUST_SHORT`, `Авг`],
  [`DATES.SEPTEMBER_SHORT`, `Сен`],
  [`DATES.OCTOBER_SHORT`, `Окт`],
  [`DATES.NOVEMBER_SHORT`, `Ноя`],
  [`DATES.DECEMBER_SHORT`, `Дек`],
  [`DATES.MONDAY_SHORT`, `Пн`],
  [`DATES.TUESDAY_SHORT`, `Вт`],
  [`DATES.WEDNESDAY_SHORT`, `Ср`],
  [`DATES.THURSDAY_SHORT`, `Чт`],
  [`DATES.FRIDAY_SHORT`, `Пт`],
  [`DATES.SATURDAY_SHORT`, `Сб`],
  [`DATES.SUNDAY_SHORT`, `Вс`],
  [`ERROR.USER_NOT_FOUND`, `Пользователь не найден`],
  [`COMMON.OK`, `Ок`],
  [`COMMON.USER_PREFERENCES`, `Предпочтения пользователя`],
  [`ERROR.UPDATE_ONLY_OWN_SETTINGS`, `Пользователь может обновлять только собственные настройки`],
  [`COMMON.FIRST_NAME`, `Имя`],
  [`COMMON.LAST_NAME`, `Последнее имя`],
  [`COMMON.LANGUAGE`, `Язык`],
  [`COMMON.TIME_ZONE`, `Часовой пояс`],
  [`COMMON.COUNTRY`, `Страна`],
  [`COMMON.APPLICATION_AI_TEXTAREA`, `Текстовая область приложения AI`],
  [`MESSAGES.CHANGES_SUCCESSFULLY_SAVED`, `Изменения успешно сохранены`],
  [`INPUT.TO_MANY_ITEMS.START_TYPING`, `Слишком много элементов. Пожалуйста, начните вводить`],
  [`ERROR.INVALID_URL`, `Неверный формат URL`],
  [`ERROR.URL_NOT_HTTPS`, `URL не использует HTTPS`],
  [`ERROR.UNKNOWN_URL_TYPE`, `URL безопасен, но не соответствует известному шаблону имени пользователя`],
  [`COMMON.PHONE`, `Телефон`],
  [`SKILL_LEVEL.BEGINNER`, `Новичок`],
  [`SKILL_LEVEL.BASIC`, `Базовый`],
  [`SKILL_LEVEL.INTERMEDIATE`, `Промежуточный`],
  [`SKILL_LEVEL.ADVANCED`, `Продвинутый`],
  [`SKILL_LEVEL.EXPERT`, `Эксперт`],
  [`SKILL_LEVEL.MASTER`, `Мастер`],
  [`SKILL_LEVEL.WORLD_CLASS`, `Мировой класс`],
  [`WORK_ARRANGEMENT.ON_SITE`, `На месте`],
  [`WORK_ARRANGEMENT.REMOTE`, `Удаленный`],
  [`WORK_ARRANGEMENT.HYBRID`, `Гибрид`],
  [`WORK_ARRANGEMENT.FLEXIBLE`, `Гибкий`],
  [`WORK_ARRANGEMENT.TRAVEL_REQUIRED`, `Требуются командировки`],
  [`WORK_ARRANGEMENT.SHIFT_BASED`, `По сменам`],
  [`COMMON.ADD`, `Добавить`],
  [`COMMON.REMOVE`, `Удалить`],
  [`COMMON.ALREADY_EXISTS`, `Уже существует`],
  [`COMMON.LANGUAGE_LEVEL`, `Уровень языка`],
  [`COMMON.LANGUAGES`, `Языки`],
  [`COMMON.EDIT_LANGUAGES`, `Редактировать языки`],
  [`ERROR.COMMON_ERROR`, `Произошла непредвиденная ошибка.`],
  [`ERROR.NOT_FOUND`, `Не найдено`],
  [`ERROR.ENTITY_NOT_FOUND`, `Сущность не найдена`],
  [`ERROR.ENTITY_WITH_ID_NOT_FOUND`, `Сущность с таким идентификатором не найдена`],
  [`ERROR.ENTITY_WITH_EMAIL_ALREADY_EXISTS`, `Сущность с таким электронным адресом уже существует`],
  [`ERROR.ENTITY_WITH_LOGIN_ALREADY_EXISTS`, `Сущность с таким логином уже существует`],
  [`ERROR.VALIDATION_ERROR`, `Ошибка валидации`],
  [`ERROR.ENTITY_ALREADY_EXISTS`, `Сущность уже существует`],
  [`ERROR.INTERNAL_SERVER_ERROR`, `Внутренняя ошибка сервера`],
  [`ERROR.BLOCKED`, `Заблокирован`],
  [`ERROR.RESOURCE_NOT_FOUND`, `Ресурс не найден`],
  [`ERROR.ENTITY_BLOCKED`, `Сущность заблокирована`],
  [`ERROR.ENTITY_PESSIMISTIC_LOCKED`, `Сущность пессимистично заблокирована`],
  [`ERROR.WRONG_AUTH`, `Неправильные учетные данные`],
  [`ERROR.FORBIDDEN`, `Доступ запрещен`],
  [`ERROR.USER_BLOCKED`, `Пользователь заблокирован`],
  [`ERROR.POTENTIAL_HARMFUL_CONTENT`, `Обнаружен потенциально опасный контент`],
  [`ERROR.JWT_MIN_LENGTH`, `JWT-токен слишком короткий`],
  [`ERROR.JWT_INVALID_FORMAT`, `Неверный формат JWT`],
  [`ERROR.JWT_USER_CLAIM_NOT_FOUND`, `Пользовательское требование не найдено в JWT`],
  [`ERROR.JWT_USER_CLAIM_INVALID_CONVERSION`, `Невозможно преобразовать утверждение пользователя в JWT`],
  [`ERROR.FORGOT_PASSWORD_REQUEST_TOO_SOON`, `Забытый пароль запрашивается слишком рано`],
  [`ERROR.RESTORE_PASSWORD_PROCESSING_ISSUE`, `Возникла проблема при восстановлении пароля`],
  [`ERROR.VERSION_NOT_SPECIFIED`, `Версия не указана`],
  [`ERROR.USER_PROJECT_LIMIT_EXCEEDED`, `Пользователь превысил лимит проекта`],
  [`ERROR.ROLE_NOT_SUPPORTED`, `Эта роль не поддерживается`],
  [`STATUS.NEW`, `Новый`],
  [`STATUS.ACTIVE`, `Активный`],
  [`STATUS.INACTIVE`, `Неактивный`],
  [`STATUS.BLOCKED`, `Заблокирован`],
  [`STATUS.DELETED`, `Удалено`],
  [`STATUS.PENDING`, `В ожидании`],
  [`STATUS.APPROVED`, `Одобрено`],
  [`STATUS.COMPLETED`, `Завершено`],
  [`STATUS.CANCELLED`, `Отменено`],
]);
