// Auto-generated file from a5-localizations_ru.csv

export const localization_ru: Map<string, string> = new Map<string, string>([
  [`AUTH.GREETINGS`, `Привет, Хонклер!`],
  [`AUTH.SIGN_IN.JOKE`, `Возможно, нам нужно вернуться к`],
  [`COMMON.LOGIN_OR_EMAIL`, `Логин или Email`],
  [`COMMON.PASSWORD`, `Пароль`],
  [`COMMON.CONFIRM_PASSWORD`, `Подтвердите пароль`],
  [`COMMON.REMEMBER_ME`, `Запомнить меня`],
  [`COMMON.FORGOT`, `Забыли пароль`],
  [`COMMON.SIGN_IN`, `Войти`],
  [`COMMON.SIGN_UP`, `Зарегистрироваться`],
  [`AUTH.NO_ACCOUNT.SIGN_UP`, `Нет учетной записи? Зарегистрируйтесь`],
  [`AUTH.HAS_ACCOUNT.SIGN_IN`, `Уже есть учетная запись? Войти`],
  [`COMMON.LOGIN`, `Логин`],
  [`COMMON.EMAIL`, `Электронная почта`],
  [`COMMON.CONFIRM_EMAIL`, `Подтвердите электронную почту`],
  [`COMMON.PROCEED`, `Продолжить`],
  [`COMMON.FIRST_NAME`, `Имя`],
  [`COMMON.LAST_NAME`, `Фамилия`],
  [`COMMON.NO_COMPLAINTS`, `Нет жалоб`],
  [`COMMON.WE_ARE_HONKING`, `Мы сигналим с 2024 года!`],
  [`COMMON.DO_NOT_STORE_SENS_DATA`, `НЕ СОХРАНЯЙТЕ КОНФИДЕНЦИАЛЬНЫЕ ДАННЫЕ!`],
  [`COMMON.LIGHT_THEME`, `Светлая тема`],
  [`COMMON.DARK_THEME`, `Темная тема`],
  [`ERROR.PASSWORDS_DO_NOT_MATCH`, `Пароли не совпадают`],
  [`ERROR.EMAILS_DO_NOT_MATCH`, `Электронные адреса не совпадают`],
  [`ERROR.FIELD_REQUIRED`, `Поле обязательно для заполнения!`],
  [`ERROR.CHECK_CHECKBOX`, `Пожалуйста, установите флажок!`],
  [`ERROR.INVALID_EMAIL`, `Неверный формат электронной почты!`],
  [`MENU.HOME`, `Главная`],
  [`MENU.JOBS`, `Вакансии`],
  [`MENU.COMPANIES`, `Компании`],
  [`MENU.KARMA`, `Карма`],
  [`COMMON.WELCOME_BACK`, `Добро пожаловать`],
  [`MENU.ACTIVE_APPLICATIONS`, `Активные заявки`],
  [`MENU.TODOS`, `Задачи`],
  [`MENU.RESPONSE_RATE`, `Уровень отклика`],
  [`MENU.UPCOMING_INTERVIEWS`, `Предстоящие интервью`],
  [`COMMON.NEW_APPLICATION`, `Новая заявка`],
  [`STATS.JOB_APPLICATIONS_TREND`, `Тренд заявок на работу`],
  [`STATS.TOP_COMPANIES`, `Топ компаний (заявки)`],
  [`STATS.NEW_JOB_LISTINGS_PER_DAY`, `Новые вакансии за день`],
  [`STATS.APPLICATION_STATUS_DISTRIBUTION`, `Распределение статуса заявок`],
  [`STATUS.APPLIED`, `Подано`],
  [`STATUS.REJECTED`, `Отклонено`],
  [`STATUS.OFFER`, `Предложение`],
  [`STATUS.INTERVIEW`, `Собеседование`],
  [`STATUS.IN_REVIEW`, `На рассмотрении`],
  [`COMMON.CREATE`, `Создать`],
  [`COMMON.EDIT`, `Редактировать`],
  [`COMMON.APPLICATION_LINK`, `Ссылка на заявку`],
  [`COMMON.JOB_TITLE`, `Название вакансии`],
  [`COMMON.COMPANY`, `Компания`],
  [`COMMON.LOCATION`, `Местоположение`],
  [`COMMON.EXPERIENCE_LEVEL`, `Уровень опыта`],
  [`COMMON.JOB_TYPE`, `Тип работы`],
  [`COMMON.SOURCE`, `Источник`],
  [`COMMON.SALARY_RANGE`, `Диапазон зарплаты`],
  [`COMMON.FROM`, `От`],
  [`COMMON.TO`, `До`],
  [`COMMON.CURRENCY`, `Валюта`],
  [`COMMON.POSTED_DATE`, `Дата публикации`],
  [`COMMON.APPLICATION_DEADLINE`, `Крайний срок подачи заявки`],
  [`COMMON.Contact_EMAIL`, `Контактный Email`],
  [`COMMON.DESCRIPTION`, `Описание`],
  [`COMMON.NOTES`, `Заметки`],
  [`COMMON.CANCEL`, `Отмена`],
  [`COMMON.UPDATE`, `Обновить`],
  [`COMMON.EDIT_PROFILE`, `Редактировать профиль`],
  [`COMMON.EDIT_SKILLS`, `Редактировать навыки`],
  [`COMMON.ADD_EXPERIENCE`, `Добавить опыт`],
  [`COMMON.SKILLS`, `Навыки`],
  [`COMMON.EXPERIENCE`, `Опыт`],
  [`COMMON.EDUCATION`, `Образование`],
  [`COMMON.CERTIFICATIONS`, `Сертификаты`],
  [`ROLE.USER`, `Пользователь`],
  [`ROLE.TECHNICAL_SUPPORT`, `Техническая поддержка`],
  [`ROLE.ADMIN`, `Администратор`],
  [`ROLE.SUPER_ADMIN`, `Супер Администратор`],
  [`JOB_TYPE.FULL_TIME`, `Полная занятость`],
  [`JOB_TYPE.PART_TIME`, `Частичная занятость`],
  [`JOB_TYPE.CONTRACT`, `Контракт`],
  [`JOB_TYPE.TEMPORARY`, `Временная работа`],
  [`JOB_TYPE.INTERN`, `Стажировка`],
  [`JOB_TYPE.VOLUNTEER`, `Волонтерство`],
  [`JOB_TYPE.FREELANCE`, `Фриланс`],
  [`JOB_TYPE.STARTUP`, `Стартап`],
  [`JOB_TYPE.OTHER`, `Другое`],
  [`JOB_SOURCE.JOB_BOARD`, `Доска вакансий`],
  [`JOB_SOURCE.COMPANY_WEBSITE`, `Сайт компании`],
  [`JOB_SOURCE.RECOMMENDATION`, `Рекомендация`],
  [`JOB_SOURCE.OTHER`, `Другое`],
  [`EXPERIENCE_LEVEL.INTERNSHIP`, `Стажировка`],
  [`EXPERIENCE_LEVEL.ENTRY_LEVEL`, `Начальный уровень`],
  [`EXPERIENCE_LEVEL.JUNIOR`, `Младший`],
  [`EXPERIENCE_LEVEL.MID_LEVEL`, `Средний уровень`],
  [`EXPERIENCE_LEVEL.SENIOR`, `Старший`],
  [`EXPERIENCE_LEVEL.EXECUTIVE`, `Руководитель`],
  [`COMMON.APPLICATIONS`, `Апликации`],
  [`DATES.JANUARY_SHORT`, `Янв`],
  [`DATES.FEBRUARY_SHORT`, `Фев`],
  [`DATES.MARCH_SHORT`, `Мар`],
  [`DATES.APRIL_SHORT`, `Апр`],
  [`DATES.MAY_SHORT`, `Май`],
  [`DATES.JUNE_SHORT`, `Июн`],
  [`DATES.JULY_SHORT`, `Июл`],
  [`DATES.AUGUST_SHORT`, `Авг`],
  [`DATES.SEPTEMBER_SHORT`, `Сен`],
  [`DATES.OCTOBER_SHORT`, `Окт`],
  [`DATES.NOVEMBER_SHORT`, `Ноя`],
  [`DATES.DECEMBER_SHORT`, `Дек`],
  [`DATES.MONDAY_SHORT`, `Пн`],
  [`DATES.TUESDAY_SHORT`, `Вт`],
  [`DATES.WEDNESDAY_SHORT`, `Ср`],
  [`DATES.THURSDAY_SHORT`, `Чт`],
  [`DATES.FRIDAY_SHORT`, `Пт`],
  [`DATES.SATURDAY_SHORT`, `Сб`],
  [`DATES.SUNDAY_SHORT`, `Вс`],
  [`ERROR.USER_NOT_FOUND`, `Пользователь не найден`],
  [`COMMON.OK`, `Ок`],
  [`COMMON.USER_PREFERENCES`, `Настройки пользователя`],
  [`ERROR.UPDATE_ONLY_OWN_SETTINGS`, `Пользователь может изменять только свои настройки`],
  [`COMMON.FIRST_NAME`, `Имя`],
  [`COMMON.LAST_NAME`, `Фамилия`],
  [`COMMON.LANGUAGE`, `Язык`],
  [`COMMON.TIME_ZONE`, `Часовой пояс`],
  [`COMMON.COUNTRY`, `Страна`],
  [`COMMON.APPLICATION_AI_TEXTAREA`, `Текстовое поле AI приложения`],
  [`MESSAGES.CHANGES_SUCCESSFULLY_SAVED`, `Изменения успешно сохранены`],
  [`INPUT.TO_MANY_ITEMS.START_TYPING`, `Слишком много элементов. Начните вводить текст`],
  [`ERROR.INVALID_URL`, `Неверный формат URL`],
  [`ERROR.URL_NOT_HTTPS`, `URL не использует HTTPS`],
  [`ERROR.UNKNOWN_URL_TYPE`, `URL безопасен, но не соответствует известному шаблону имени пользователя`],
  [`COMMON.PHONE`, `Телефон`],
  [`SKILL_LEVEL.BEGINNER`, `Новичок`],
  [`SKILL_LEVEL.BASIC`, `Базовый`],
  [`SKILL_LEVEL.INTERMEDIATE`, `Средний`],
  [`SKILL_LEVEL.ADVANCED`, `Продвинутый`],
  [`SKILL_LEVEL.EXPERT`, `Эксперт`],
  [`SKILL_LEVEL.MASTER`, `Мастер`],
  [`SKILL_LEVEL.WORLD_CLASS`, `Мирового уровня`],
  [`WORK_ARRANGEMENT.ON_SITE`, `На месте`],
  [`WORK_ARRANGEMENT.REMOTE`, `Удаленно`],
  [`WORK_ARRANGEMENT.HYBRID`, `Гибридный`],
  [`WORK_ARRANGEMENT.FLEXIBLE`, `Гибкий`],
  [`WORK_ARRANGEMENT.TRAVEL_REQUIRED`, `Требуются поездки`],
  [`WORK_ARRANGEMENT.SHIFT_BASED`, `Посменный график`],
]);
