// Auto-generated file from a2-localizations_es.csv

export const localization_es: Map<string, string> = new Map<string, string>([
  ['AUTH.GREETINGS', '¡Saludos, compañero Honkler!'],
  ['AUTH.SIGN_IN.JOKE', 'Quizás necesitemos volver a'],
  ['COMMON.AUTH.LOGIN_OR_EMAIL', 'Usuario o Correo'],
  ['COMMON.AUTH.PASSWORD', 'Contraseña'],
  ['COMMON.AUTH.CONFIRM_PASSWORD', 'Contraseña'],
  ['COMMON.AUTH.REMEMBER_ME', 'Recordarme'],
  ['COMMON.AUTH.FORGOT', 'Olvidé'],
  ['COMMON.AUTH.SIGN_IN', 'Iniciar Sesión'],
  ['COMMON.AUTH.SIGN_UP', 'Registrarse'],
  ['AUTH.NO_ACCOUNT.SIGN_UP', '¿No tienes una cuenta? Regístrate'],
  ['AUTH.HAS_ACCOUNT.SIGN_IN', '¿Ya tienes una cuenta? Inicia Sesión'],
  ['COMMON.AUTH.LOGIN', 'Usuario'],
  ['COMMON.AUTH.EMAIL', 'Correo'],
  ['COMMON.AUTH.CONFIRM_EMAIL', 'Confirmar correo'],
  ['COMMON.AUTH.PROCEED', 'Continuar'],
  ['COMMON.SYSTEM.NO_COMPLAINTS', 'Sin quejas'],
  ['COMMON.SYSTEM.WE_ARE_HONKING', '¡Estamos honking desde 2024!'],
  ['COMMON.SYSTEM.DO_NOT_STORE_SENS_DATA', '¡NO ALMACENES DATOS SENSIBLES AQUÍ!'],
  ['COMMON.UI.LIGHT_THEME', 'Tema claro'],
  ['COMMON.UI.DARK_THEME', 'Tema oscuro'],
  ['ERROR.VALIDATION.PASSWORDS_DO_NOT_MATCH', 'Las contraseñas no coinciden'],
  ['ERROR.VALIDATION.EMAILS_DO_NOT_MATCH', 'Los correos no coinciden'],
  ['ERROR.VALIDATION.FIELD_REQUIRED', '¡El campo es obligatorio!'],
  ['ERROR.VALIDATION.CHECK_CHECKBOX', '¡Por favor marca la casilla!'],
  ['ERROR.VALIDATION.INVALID_EMAIL', '¡Formato de correo inválido!'],
  ['MENU.HOME', 'Inicio'],
  ['MENU.JOBS', 'Empleos'],
  ['MENU.COMPANIES', 'Empresas'],
  ['MENU.KARMA', 'Karma'],
  ['COMMON.UI.WELCOME_BACK', 'Bienvenido de nuevo'],
  ['MENU.ACTIVE_APPLICATIONS', 'Solicitudes Activas'],
  ['MENU.TODOS', 'TAREAS'],
  ['MENU.RESPONSE_RATE', 'Tasa de Respuesta'],
  ['MENU.UPCOMING_INTERVIEWS', 'Entrevistas Próximas'],
  ['COMMON.UI.NEW_APPLICATION', 'Nueva Solicitud'],
  ['STATS.JOB_APPLICATIONS_TREND', 'Tendencia de Solicitudes'],
  ['STATS.TOP_COMPANIES', 'Empresas Principales (Solicitudes)'],
  ['STATS.NEW_JOB_LISTINGS_PER_DAY', 'Nuevas Ofertas por Día'],
  ['STATS.APPLICATION_STATUS_DISTRIBUTION', 'Distribución de Estados'],
  ['STATUS.APPLIED', 'Aplicado'],
  ['STATUS.REJECTED', 'Rechazado'],
  ['STATUS.OFFER', 'Oferta'],
  ['STATUS.INTERVIEW', 'Entrevista'],
  ['STATUS.IN_REVIEW', 'En Revisión'],
  ['COMMON.UI.CREATE', 'Crear'],
  ['COMMON.UI.EDIT', 'Editar'],
  ['COMMON.JOB.APPLICATION_LINK', 'Enlace de Solicitud'],
  ['COMMON.JOB.TITLE', 'Título del Empleo'],
  ['COMMON.JOB.COMPANY', 'Empresa'],
  ['COMMON.JOB.LOCATION', 'Ubicación'],
  ['COMMON.JOB.EXPERIENCE_LEVEL', 'Nivel de Experiencia'],
  ['COMMON.JOB.TYPE', 'Tipo de Empleo'],
  ['COMMON.JOB.SOURCE', 'Fuente'],
  ['COMMON.JOB.SALARY_RANGE', 'Rango Salarial'],
  ['COMMON.FORM.FROM', 'Desde'],
  ['COMMON.FORM.TO', 'Hasta'],
  ['COMMON.FORM.CURRENCY', 'Moneda'],
  ['COMMON.JOB.POSTED_DATE', 'Fecha de Publicación'],
  ['COMMON.JOB.APPLICATION_DEADLINE', 'Fecha Límite'],
  ['COMMON.JOB.CONTACT_EMAIL', 'Correo de Contacto'],
  ['COMMON.JOB.DESCRIPTION', 'Descripción'],
  ['COMMON.JOB.NOTES', 'Notas'],
  ['COMMON.UI.CANCEL', 'Cancelar'],
  ['COMMON.UI.UPDATE', 'Actualizar'],
  ['COMMON.USER.EDIT_PROFILE', 'Editar perfil'],
  ['COMMON.USER.EDIT_SKILLS', 'Editar habilidades'],
  ['COMMON.USER.ADD_EXPERIENCE', 'Añadir experiencia'],
  ['COMMON.SKILLS.SKILLS', 'Habilidades'],
  ['COMMON.SKILLS.EXPERIENCE', 'Experiencia'],
  ['COMMON.SKILLS.EDUCATION', 'Educación'],
  ['COMMON.SKILLS.CERTIFICATIONS', 'Certificaciones'],
  ['ROLE.USER', 'Usuario'],
  ['ROLE.TECHNICAL_SUPPORT', 'Soporte Técnico'],
  ['ROLE.ADMIN', 'Administrador'],
  ['ROLE.SUPER_ADMIN', 'Super Administrador'],
  ['JOB_TYPE.FULL_TIME', 'Tiempo completo'],
  ['JOB_TYPE.PART_TIME', 'Medio tiempo'],
  ['JOB_TYPE.CONTRACT', 'Contrato'],
  ['JOB_TYPE.TEMPORARY', 'Temporal'],
  ['JOB_TYPE.INTERN', 'Prácticas'],
  ['JOB_TYPE.VOLUNTEER', 'Voluntario'],
  ['JOB_TYPE.FREELANCE', 'Freelance'],
  ['JOB_TYPE.STARTUP', 'Startup'],
  ['JOB_TYPE.OTHER', 'Otro'],
  ['JOB_SOURCE.JOB_BOARD', 'Bolsa de Trabajo'],
  ['JOB_SOURCE.COMPANY_WEBSITE', 'Sitio Web de la Empresa'],
  ['JOB_SOURCE.RECOMMENDATION', 'Recomendación'],
  ['JOB_SOURCE.OTHER', 'Otro'],
  ['EXPERIENCE_LEVEL.INTERNSHIP', 'Prácticas'],
  ['EXPERIENCE_LEVEL.ENTRY_LEVEL', 'Nivel Inicial'],
  ['EXPERIENCE_LEVEL.JUNIOR', 'Junior'],
  ['EXPERIENCE_LEVEL.MID_LEVEL', 'Nivel Medio'],
  ['EXPERIENCE_LEVEL.SENIOR', 'Senior'],
  ['EXPERIENCE_LEVEL.EXECUTIVE', 'Ejecutivo'],
  ['COMMON.JOB.APPLICATIONS', 'Solicitudes'],
  ['DATES.JANUARY_SHORT', 'Ene'],
  ['DATES.FEBRUARY_SHORT', 'Feb'],
  ['DATES.MARCH_SHORT', 'Mar'],
  ['DATES.APRIL_SHORT', 'Abr'],
  ['DATES.MAY_SHORT', 'May'],
  ['DATES.JUNE_SHORT', 'Jun'],
  ['DATES.JULY_SHORT', 'Jul'],
  ['DATES.AUGUST_SHORT', 'Ago'],
  ['DATES.SEPTEMBER_SHORT', 'Sep'],
  ['DATES.OCTOBER_SHORT', 'Oct'],
  ['DATES.NOVEMBER_SHORT', 'Nov'],
  ['DATES.DECEMBER_SHORT', 'Dic'],
  ['DATES.MONDAY_SHORT', 'Lun'],
  ['DATES.TUESDAY_SHORT', 'Mar'],
  ['DATES.WEDNESDAY_SHORT', 'Mié'],
  ['DATES.THURSDAY_SHORT', 'Jue'],
  ['DATES.FRIDAY_SHORT', 'Vie'],
  ['DATES.SATURDAY_SHORT', 'Sáb'],
  ['DATES.SUNDAY_SHORT', 'Dom'],
  ['ERROR.ENTITY.USER_NOT_FOUND', 'Usuario no encontrado'],
  ['COMMON.UI.OK', 'Ok'],
  ['COMMON.USER.PREFERENCES', 'Preferencias de usuario'],
  ['ERROR.ENTITY.UPDATE_ONLY_OWN_SETTINGS', 'El usuario solo puede actualizar sus propias configuraciones'],
  ['COMMON.USER.FIRST_NAME', 'Nombre'],
  ['COMMON.USER.LAST_NAME', 'Apellido'],
  ['COMMON.USER.LANGUAGE', 'Idioma'],
  ['COMMON.USER.TIME_ZONE', 'Zona Horaria'],
  ['COMMON.USER.COUNTRY', 'País'],
  ['COMMON.FORM.AI_TEXTAREA', 'Área de texto IA para solicitudes'],
  ['MESSAGES.CHANGES_SUCCESSFULLY_SAVED', 'Los cambios se han guardado correctamente'],
  ['COMMON.FORM.TOO_MANY_ITEMS', 'Demasiados elementos. Por favor, comienza a escribir'],
  ['ERROR.VALIDATION.INVALID_URL', 'Formato de URL inválido'],
  ['ERROR.VALIDATION.URL_NOT_HTTPS', 'La URL no usa HTTPS'],
  ['ERROR.VALIDATION.UNKNOWN_URL_TYPE', 'La URL es segura pero no coincide con un patrón de nombre de usuario conocido'],
  ['COMMON.USER.PHONE', 'Teléfono'],
  ['SKILL_LEVEL.BEGINNER', 'Principiante'],
  ['SKILL_LEVEL.BASIC', 'Básico'],
  ['SKILL_LEVEL.INTERMEDIATE', 'Intermedio'],
  ['SKILL_LEVEL.ADVANCED', 'Avanzado'],
  ['SKILL_LEVEL.EXPERT', 'Experto'],
  ['SKILL_LEVEL.MASTER', 'Maestro'],
  ['SKILL_LEVEL.WORLD_CLASS', 'Clase Mundial'],
  ['WORK_ARRANGEMENT.ON_SITE', 'Presencial'],
  ['WORK_ARRANGEMENT.REMOTE', 'Remoto'],
  ['WORK_ARRANGEMENT.HYBRID', 'Híbrido'],
  ['WORK_ARRANGEMENT.FLEXIBLE', 'Flexible'],
  ['WORK_ARRANGEMENT.TRAVEL_REQUIRED', 'Requiere Viajes'],
  ['WORK_ARRANGEMENT.SHIFT_BASED', 'Por Turnos'],
  ['COMMON.UI.ADD', 'Añadir'],
  ['COMMON.UI.REMOVE', 'Eliminar'],
  ['COMMON.FORM.ALREADY_EXISTS', 'Ya existe'],
  ['COMMON.SKILLS.LANGUAGE_LEVEL', 'Nivel de Idioma'],
  ['COMMON.SKILLS.LANGUAGES', 'Idiomas'],
  ['COMMON.SKILLS.EDIT_LANGUAGES', 'Editar idiomas'],
  ['ERROR.SYSTEM.COMMON_ERROR', 'Ha ocurrido un error inesperado.'],
  ['ERROR.ENTITY.NOT_FOUND', 'No encontrado'],
  ['ERROR.ENTITY.ENTITY_NOT_FOUND', 'Entidad no encontrada'],
  ['ERROR.ENTITY.ENTITY_WITH_ID_NOT_FOUND', 'Entidad con este ID no encontrada'],
  ['ERROR.ENTITY.ENTITY_WITH_EMAIL_ALREADY_EXISTS', 'Ya existe una entidad con este correo'],
  ['ERROR.ENTITY.ENTITY_WITH_LOGIN_ALREADY_EXISTS', 'Ya existe una entidad con este usuario'],
  ['ERROR.VALIDATION.VALIDATION_ERROR', 'Error de validación'],
  ['ERROR.ENTITY.ENTITY_ALREADY_EXISTS', 'La entidad ya existe'],
  ['ERROR.SYSTEM.INTERNAL_SERVER_ERROR', 'Error interno del servidor'],
  ['ERROR.ENTITY.BLOCKED', 'Bloqueado'],
  ['ERROR.ENTITY.RESOURCE_NOT_FOUND', 'Recurso no encontrado'],
  ['ERROR.ENTITY.ENTITY_BLOCKED', 'La entidad está bloqueada'],
  ['ERROR.ENTITY.ENTITY_PESSIMISTIC_LOCKED', 'La entidad está bloqueada pesimistamente'],
  ['ERROR.AUTH.WRONG_CREDENTIALS', 'Credenciales incorrectas'],
  ['ERROR.AUTH.FORBIDDEN', 'Acceso denegado'],
  ['ERROR.ENTITY.USER_BLOCKED', 'El usuario está bloqueado'],
  ['ERROR.SYSTEM.POTENTIAL_HARMFUL_CONTENT', 'Contenido potencialmente dañino detectado'],
  ['ERROR.AUTH.JWT_MIN_LENGTH', 'El token JWT es demasiado corto'],
  ['ERROR.AUTH.JWT_INVALID_FORMAT', 'Formato de JWT inválido'],
  ['ERROR.AUTH.JWT_USER_CLAIM_NOT_FOUND', 'No se encontró el claim de usuario en el JWT'],
  ['ERROR.AUTH.JWT_USER_CLAIM_INVALID_CONVERSION', 'No se puede convertir el claim de usuario en el JWT'],
  ['ERROR.AUTH.FORGOT_PASSWORD_REQUEST_TOO_SOON', 'Solicitud de contraseña olvidada demasiado pronto'],
  ['ERROR.AUTH.RESTORE_PASSWORD_PROCESSING_ISSUE', 'Ocurrió un problema durante la restauración de la contraseña'],
  ['ERROR.SYSTEM.VERSION_NOT_SPECIFIED', 'Versión no especificada'],
  ['ERROR.ENTITY.USER_PROJECT_LIMIT_EXCEEDED', 'El usuario ha excedido el límite de proyectos'],
  ['ERROR.ENTITY.ROLE_NOT_SUPPORTED', 'Este rol no está soportado'],
  ['STATUS.NEW', 'Nuevo'],
  ['STATUS.ACTIVE', 'Activo'],
  ['STATUS.INACTIVE', 'Inactivo'],
  ['STATUS.BLOCKED', 'Bloqueado'],
  ['STATUS.DELETED', 'Eliminado'],
  ['STATUS.PENDING', 'Pendiente'],
  ['STATUS.APPROVED', 'Aprobado'],
  ['STATUS.COMPLETED', 'Completado'],
  ['STATUS.CANCELLED', 'Cancelado'],
  ['KARMA.TITLE', 'Tu Karma'],
  ['KARMA.POINTS', 'puntos de karma'],
  ['KARMA.STATS.ACTIVITY', 'Actividad'],
  ['KARMA.STATS.ACTIVITY_DESC', 'Nivel de participación en la comunidad'],
  ['KARMA.STATS.HELP', 'Ayuda'],
  ['KARMA.STATS.HELP_DESC', 'Ayudó a otros usuarios'],
  ['KARMA.STATS.ACHIEVEMENTS', 'Logros'],
  ['KARMA.STATS.ACHIEVEMENTS_DESC', 'Recibió premios'],
  ['KARMA.HISTORY.TITLE', 'Historial de Karma'],
  ['KARMA.HISTORY.DATE', 'Fecha'],
  ['KARMA.HISTORY.EVENT', 'Evento'],
  ['KARMA.HISTORY.CHANGE', 'Cambio'],
  ['KARMA.HISTORY.EVENTS.TASK_HELP', 'Ayudó a resolver una tarea'],
  ['KARMA.HISTORY.EVENTS.DISCUSSION', 'Participación activa en la discusión'],
  ['KARMA.HISTORY.EVENTS.MATERIAL', 'Publicó material útil'],
]);
