// Auto-generated file from a2-localizations_es.csv

export const localization_es: Map<string, string> = new Map<string, string>([
  [`AUTH.GREETINGS`, `¡Saludos, Honkler!`],
  [`AUTH.SIGN_IN.JOKE`, `Quizás necesitemos volver a`],
  [`COMMON.LOGIN_OR_EMAIL`, `Correo o nombre de usuario`],
  [`COMMON.PASSWORD`, `Contraseña`],
  [`COMMON.CONFIRM_PASSWORD`, `Confirmar contraseña`],
  [`COMMON.REMEMBER_ME`, `Recuérdame`],
  [`COMMON.FORGOT`, `Olvidé mi contraseña`],
  [`COMMON.SIGN_IN`, `Iniciar sesión`],
  [`COMMON.SIGN_UP`, `Registrarse`],
  [`AUTH.NO_ACCOUNT.SIGN_UP`, `¿No tienes una cuenta? Regístrate`],
  [`AUTH.HAS_ACCOUNT.SIGN_IN`, `¿Ya tienes una cuenta? Inicia Sesión`],
  [`COMMON.LOGIN`, `Iniciar sesión`],
  [`COMMON.EMAIL`, `Correo electrónico`],
  [`COMMON.CONFIRM_EMAIL`, `Confirmar correo electrónico`],
  [`COMMON.PROCEED`, `Continuar`],
  [`COMMON.FIRST_NAME`, `Nombre`],
  [`COMMON.LAST_NAME`, `Apellido`],
  [`COMMON.NO_COMPLAINTS`, `Sin quejas`],
  [`COMMON.WE_ARE_HONKING`, `¡Estamos tocando la bocina desde 2024!`],
  [`COMMON.DO_NOT_STORE_SENS_DATA`, `¡NO ALMACENES NINGÚN DATO SENSIBLE AQUÍ!`],
  [`COMMON.LIGHT_THEME`, `Tema claro`],
  [`COMMON.DARK_THEME`, `Tema oscuro`],
  [`ERROR.PASSWORDS_DO_NOT_MATCH`, `Las contraseñas no coinciden`],
  [`ERROR.EMAILS_DO_NOT_MATCH`, `Los correos electrónicos no coinciden`],
  [`ERROR.FIELD_REQUIRED`, `¡El campo es obligatorio!`],
  [`ERROR.CHECK_CHECKBOX`, `¡Por favor marque la casilla!`],
  [`ERROR.INVALID_EMAIL`, `¡Formato de correo electrónico no válido!`],
  [`MENU.HOME`, `Inicio`],
  [`MENU.JOBS`, `Empleos`],
  [`MENU.COMPANIES`, `Empresas`],
  [`MENU.KARMA`, `Karma`],
  [`COMMON.WELCOME_BACK`, `Bienvenido de nuevo`],
  [`MENU.ACTIVE_APPLICATIONS`, `Aplicaciones activas`],
  [`MENU.TODOS`, `Tareas`],
  [`MENU.RESPONSE_RATE`, `Tasa de respuesta`],
  [`MENU.UPCOMING_INTERVIEWS`, `Próximas entrevistas`],
  [`COMMON.NEW_APPLICATION`, `Nueva aplicación`],
  [`STATS.JOB_APPLICATIONS_TREND`, `Tendencia de aplicaciones`],
  [`STATS.TOP_COMPANIES`, `Empresas principales (Aplicaciones)`],
  [`STATS.NEW_JOB_LISTINGS_PER_DAY`, `Nuevas ofertas de empleo por día`],
  [`STATS.APPLICATION_STATUS_DISTRIBUTION`, `Distribución del estado de la aplicación`],
  [`STATUS.APPLIED`, `Aplicado`],
  [`STATUS.REJECTED`, `Rechazado`],
  [`STATUS.OFFER`, `Oferta`],
  [`STATUS.INTERVIEW`, `Entrevista`],
  [`STATUS.IN_REVIEW`, `En revisión`],
  [`COMMON.CREATE`, `Crear`],
  [`COMMON.EDIT`, `Editar`],
  [`COMMON.APPLICATION_LINK`, `Enlace de aplicación`],
  [`COMMON.JOB_TITLE`, `Título del trabajo`],
  [`COMMON.COMPANY`, `Empresa`],
  [`COMMON.LOCATION`, `Ubicación`],
  [`COMMON.EXPERIENCE_LEVEL`, `Nivel de experiencia`],
  [`COMMON.JOB_TYPE`, `Tipo de empleo`],
  [`COMMON.SOURCE`, `Fuente`],
  [`COMMON.SALARY_RANGE`, `Rango salarial`],
  [`COMMON.FROM`, `Desde`],
  [`COMMON.TO`, `Hasta`],
  [`COMMON.CURRENCY`, `Moneda`],
  [`COMMON.POSTED_DATE`, `Fecha de publicación`],
  [`COMMON.APPLICATION_DEADLINE`, `Fecha límite de aplicación`],
  [`COMMON.Contact_EMAIL`, `Correo de contacto`],
  [`COMMON.DESCRIPTION`, `Descripción`],
  [`COMMON.NOTES`, `Notas`],
  [`COMMON.CANCEL`, `Cancelar`],
  [`COMMON.UPDATE`, `Actualizar`],
  [`COMMON.EDIT_PROFILE`, `Editar perfil`],
  [`COMMON.EDIT_SKILLS`, `Editar habilidades`],
  [`COMMON.ADD_EXPERIENCE`, `Agregar experiencia`],
  [`COMMON.SKILLS`, `Habilidades`],
  [`COMMON.EXPERIENCE`, `Experiencia`],
  [`COMMON.EDUCATION`, `Educación`],
  [`COMMON.CERTIFICATIONS`, `Certificaciones`],
  [`ROLE.USER`, `Usuario`],
  [`ROLE.TECHNICAL_SUPPORT`, `Soporte técnico`],
  [`ROLE.ADMIN`, `Administrador`],
  [`ROLE.SUPER_ADMIN`, `Super Administrador`],
  [`JOB_TYPE.FULL_TIME`, `Tiempo completo`],
  [`JOB_TYPE.PART_TIME`, `Medio tiempo`],
  [`JOB_TYPE.CONTRACT`, `Contrato`],
  [`JOB_TYPE.TEMPORARY`, `Temporal`],
  [`JOB_TYPE.INTERN`, `Prácticas`],
  [`JOB_TYPE.VOLUNTEER`, `Voluntario`],
  [`JOB_TYPE.FREELANCE`, `Freelance`],
  [`JOB_TYPE.STARTUP`, `Startup`],
  [`JOB_TYPE.OTHER`, `Otro`],
  [`JOB_SOURCE.JOB_BOARD`, `Bolsa de trabajo`],
  [`JOB_SOURCE.COMPANY_WEBSITE`, `Sitio web de la empresa`],
  [`JOB_SOURCE.RECOMMENDATION`, `Recomendación`],
  [`JOB_SOURCE.OTHER`, `Otro`],
  [`EXPERIENCE_LEVEL.INTERNSHIP`, `Prácticas`],
  [`EXPERIENCE_LEVEL.ENTRY_LEVEL`, `Nivel de entrada`],
  [`EXPERIENCE_LEVEL.JUNIOR`, `Junior`],
  [`EXPERIENCE_LEVEL.MID_LEVEL`, `Nivel intermedio`],
  [`EXPERIENCE_LEVEL.SENIOR`, `Senior`],
  [`EXPERIENCE_LEVEL.EXECUTIVE`, `Ejecutivo`],
  [`COMMON.APPLICATIONS`, `Aplicaciones`],
  [`DATES.JANUARY_SHORT`, `Ene`],
  [`DATES.FEBRUARY_SHORT`, `Feb`],
  [`DATES.MARCH_SHORT`, `Mar`],
  [`DATES.APRIL_SHORT`, `Abr`],
  [`DATES.MAY_SHORT`, `May`],
  [`DATES.JUNE_SHORT`, `Jun`],
  [`DATES.JULY_SHORT`, `Jul`],
  [`DATES.AUGUST_SHORT`, `Ago`],
  [`DATES.SEPTEMBER_SHORT`, `Sep`],
  [`DATES.OCTOBER_SHORT`, `Oct`],
  [`DATES.NOVEMBER_SHORT`, `Nov`],
  [`DATES.DECEMBER_SHORT`, `Dic`],
  [`DATES.MONDAY_SHORT`, `Lun`],
  [`DATES.TUESDAY_SHORT`, `Mar`],
  [`DATES.WEDNESDAY_SHORT`, `Mié`],
  [`DATES.THURSDAY_SHORT`, `Jue`],
  [`DATES.FRIDAY_SHORT`, `Vie`],
  [`DATES.SATURDAY_SHORT`, `Sáb`],
  [`DATES.SUNDAY_SHORT`, `Dom`],
  [`ERROR.USER_NOT_FOUND`, `Usuario no encontrado`],
  [`COMMON.OK`, `Aceptar`],
  [`COMMON.USER_PREFERENCES`, `Preferencias del usuario`],
  [`ERROR.UPDATE_ONLY_OWN_SETTINGS`, `El usuario solo puede actualizar sus propias configuraciones`],
  [`COMMON.FIRST_NAME`, `Nombre`],
  [`COMMON.LAST_NAME`, `Apellido`],
  [`COMMON.LANGUAGE`, `Idioma`],
  [`COMMON.TIME_ZONE`, `Zona horaria`],
  [`COMMON.COUNTRY`, `País`],
  [`COMMON.APPLICATION_AI_TEXTAREA`, `Área de texto de IA de la aplicación`],
  [`MESSAGES.CHANGES_SUCCESSFULLY_SAVED`, `Los cambios se han guardado con éxito`],
  [`INPUT.TO_MANY_ITEMS.START_TYPING`, `Demasiados elementos. Por favor, comience a escribir`],
  [`ERROR.INVALID_URL`, `Formato de URL no válido`],
  [`ERROR.URL_NOT_HTTPS`, `La URL no usa HTTPS`],
  [`ERROR.UNKNOWN_URL_TYPE`, `La URL es segura pero no coincide con un patrón de nombre de usuario conocido`],
  [`COMMON.PHONE`, `Teléfono`],
  [`SKILL_LEVEL.BEGINNER`, `Principiante`],
  [`SKILL_LEVEL.BASIC`, `Básico`],
  [`SKILL_LEVEL.INTERMEDIATE`, `Intermedio`],
  [`SKILL_LEVEL.ADVANCED`, `Avanzado`],
  [`SKILL_LEVEL.EXPERT`, `Experto`],
  [`SKILL_LEVEL.MASTER`, `Maestro`],
  [`SKILL_LEVEL.WORLD_CLASS`, `Clase mundial`],
  [`WORK_ARRANGEMENT.ON_SITE`, `Presencial`],
  [`WORK_ARRANGEMENT.REMOTE`, `Remoto`],
  [`WORK_ARRANGEMENT.HYBRID`, `Híbrido`],
  [`WORK_ARRANGEMENT.FLEXIBLE`, `Flexible`],
  [`WORK_ARRANGEMENT.TRAVEL_REQUIRED`, `Se requiere viajar`],
]);
