// Auto-generated TypeScript file for static localizations
// Auto-generated TypeScript file with a1-localizations_en.csv data
// Auto-generated TypeScript file with a2-localizations_es.csv data
// Auto-generated TypeScript file with a3-localizations_fr.csv data
// Auto-generated TypeScript file with a4-localizations_ua.csv data
// Auto-generated TypeScript file with a5-localizations_ru.csv data
// Auto-generated TypeScript file with a6-localizations_de.csv data
// Auto-generated TypeScript file with a7-localizations_it.csv data

import {LocalizationItemResponse, LocalizationResponse, LocalizationsResponse} from '@amarty/models';

export const LocalizationsData: LocalizationsResponse = {
  data: [
    {
      locale: 'en',
      items: [
          { key: `AUTH.GREETINGS`, value: `Greetings fellow, Honkler!`} as LocalizationItemResponse,
          { key: `AUTH.SIGN_IN.JOKE`, value: `Maybe we need back to`} as LocalizationItemResponse,
          { key: `COMMON.LOGIN_OR_EMAIL`, value: `Login or Email`} as LocalizationItemResponse,
          { key: `COMMON.PASSWORD`, value: `Password`} as LocalizationItemResponse,
          { key: `COMMON.CONFIRM_PASSWORD`, value: `Password`} as LocalizationItemResponse,
          { key: `COMMON.REMEMBER_ME`, value: `Remember me`} as LocalizationItemResponse,
          { key: `COMMON.FORGOT`, value: `Forgot`} as LocalizationItemResponse,
          { key: `COMMON.SIGN_IN`, value: `Sign In`} as LocalizationItemResponse,
          { key: `COMMON.SIGN_UP`, value: `Sign Up`} as LocalizationItemResponse,
          { key: `AUTH.NO_ACCOUNT.SIGN_UP`, value: `Don''t have an account? Sign Up`} as LocalizationItemResponse,
          { key: `AUTH.HAS_ACCOUNT.SIGN_IN`, value: `Already have an account? Sign In`} as LocalizationItemResponse,
          { key: `COMMON.LOGIN`, value: `Login`} as LocalizationItemResponse,
          { key: `COMMON.EMAIL`, value: `Email`} as LocalizationItemResponse,
          { key: `COMMON.CONFIRM_EMAIL`, value: `Confirm email`} as LocalizationItemResponse,
          { key: `COMMON.PROCEED`, value: `Proceed`} as LocalizationItemResponse,
          { key: `COMMON.FIRST_NAME`, value: `First Name`} as LocalizationItemResponse,
          { key: `COMMON.LAST_NAME`, value: `Last Name`} as LocalizationItemResponse,
          { key: `COMMON.NO_COMPLAINTS`, value: `No complaints`} as LocalizationItemResponse,
          { key: `COMMON.WE_ARE_HONKING`, value: `We are honking since 2024!`} as LocalizationItemResponse,
          { key: `COMMON.DO_NOT_STORE_SENS_DATA`, value: `DO NOT STORE ANY SENSITIVE DATA HERE!`} as LocalizationItemResponse,
          { key: `COMMON.LIGHT_THEME`, value: `Light theme`} as LocalizationItemResponse,
          { key: `COMMON.DARK_THEME`, value: `Dark theme`} as LocalizationItemResponse,
          { key: `ERROR.PASSWORDS_DO_NOT_MATCH`, value: `Passwords do not match`} as LocalizationItemResponse,
          { key: `ERROR.EMAILS_DO_NOT_MATCH`, value: `Emails do not match`} as LocalizationItemResponse,
          { key: `ERROR.FIELD_REQUIRED`, value: `The field is required!`} as LocalizationItemResponse,
          { key: `ERROR.CHECK_CHECKBOX`, value: `Please check the box!`} as LocalizationItemResponse,
          { key: `ERROR.INVALID_EMAIL`, value: `Invalid email format!`} as LocalizationItemResponse,
          { key: `MENU.HOME`, value: `Home`} as LocalizationItemResponse,
          { key: `MENU.JOBS`, value: `Jobs`} as LocalizationItemResponse,
          { key: `MENU.COMPANIES`, value: `Companies`} as LocalizationItemResponse,
          { key: `MENU.KARMA`, value: `Karma`} as LocalizationItemResponse,
          { key: `COMMON.WELCOME_BACK`, value: `Welcome back`} as LocalizationItemResponse,
          { key: `MENU.ACTIVE_APPLICATIONS`, value: `Active Applications`} as LocalizationItemResponse,
          { key: `MENU.TODOS`, value: `TODOs`} as LocalizationItemResponse,
          { key: `MENU.RESPONSE_RATE`, value: `Response Rate`} as LocalizationItemResponse,
          { key: `MENU.UPCOMING_INTERVIEWS`, value: `Upcoming Interviews`} as LocalizationItemResponse,
          { key: `COMMON.NEW_APPLICATION`, value: `New Application`} as LocalizationItemResponse,
          { key: `STATS.JOB_APPLICATIONS_TREND`, value: `Job Applications Trend`} as LocalizationItemResponse,
          { key: `STATS.TOP_COMPANIES`, value: `Top Companies (Applications)`} as LocalizationItemResponse,
          { key: `STATS.NEW_JOB_LISTINGS_PER_DAY`, value: `New Job Listings per Day`} as LocalizationItemResponse,
          { key: `STATS.APPLICATION_STATUS_DISTRIBUTION`, value: `Application Status Distribution`} as LocalizationItemResponse,
          { key: `STATUS.APPLIED`, value: `Applied`} as LocalizationItemResponse,
          { key: `STATUS.REJECTED`, value: `Rejected`} as LocalizationItemResponse,
          { key: `STATUS.OFFER`, value: `Offer`} as LocalizationItemResponse,
          { key: `STATUS.INTERVIEW`, value: `Interview`} as LocalizationItemResponse,
          { key: `STATUS.IN_REVIEW`, value: `In Review`} as LocalizationItemResponse,
          { key: `COMMON.CREATE`, value: `Create`} as LocalizationItemResponse,
          { key: `COMMON.EDIT`, value: `Edit`} as LocalizationItemResponse,
          { key: `COMMON.APPLICATION_LINK`, value: `Application Link`} as LocalizationItemResponse,
          { key: `COMMON.JOB_TITLE`, value: `Job Title`} as LocalizationItemResponse,
          { key: `COMMON.COMPANY`, value: `Company`} as LocalizationItemResponse,
          { key: `COMMON.LOCATION`, value: `Location`} as LocalizationItemResponse,
          { key: `COMMON.EXPERIENCE_LEVEL`, value: `Experience Level`} as LocalizationItemResponse,
          { key: `COMMON.JOB_TYPE`, value: `Job Type`} as LocalizationItemResponse,
          { key: `COMMON.SOURCE`, value: `Source`} as LocalizationItemResponse,
          { key: `COMMON.SALARY_RANGE`, value: `Salary range`} as LocalizationItemResponse,
          { key: `COMMON.FROM`, value: `From`} as LocalizationItemResponse,
          { key: `COMMON.TO`, value: `To`} as LocalizationItemResponse,
          { key: `COMMON.CURRENCY`, value: `Currency`} as LocalizationItemResponse,
          { key: `COMMON.POSTED_DATE`, value: `Posted Date`} as LocalizationItemResponse,
          { key: `COMMON.APPLICATION_DEADLINE`, value: `Application Deadline`} as LocalizationItemResponse,
          { key: `COMMON.Contact_EMAIL`, value: `Contact Email`} as LocalizationItemResponse,
          { key: `COMMON.DESCRIPTION`, value: `Description`} as LocalizationItemResponse,
          { key: `COMMON.NOTES`, value: `Notes`} as LocalizationItemResponse,
          { key: `COMMON.CANCEL`, value: `Cancel`} as LocalizationItemResponse,
          { key: `COMMON.UPDATE`, value: `Update`} as LocalizationItemResponse,
          { key: `COMMON.EDIT_PROFILE`, value: `Edit profile`} as LocalizationItemResponse,
          { key: `COMMON.EDIT_SKILLS`, value: `Edit skills`} as LocalizationItemResponse,
          { key: `COMMON.ADD_EXPERIENCE`, value: `Add experience`} as LocalizationItemResponse,
          { key: `COMMON.SKILLS`, value: `Skills`} as LocalizationItemResponse,
          { key: `COMMON.EXPERIENCE`, value: `Experience`} as LocalizationItemResponse,
          { key: `COMMON.EDUCATION`, value: `Education`} as LocalizationItemResponse,
          { key: `COMMON.CERTIFICATIONS`, value: `Certifications`} as LocalizationItemResponse,
          { key: `ROLE.USER`, value: `User`} as LocalizationItemResponse,
          { key: `ROLE.TECHNICAL_SUPPORT`, value: `Technical Support`} as LocalizationItemResponse,
          { key: `ROLE.ADMIN`, value: `Admin`} as LocalizationItemResponse,
          { key: `ROLE.SUPER_ADMIN`, value: `Super Admin`} as LocalizationItemResponse,
          { key: `JOB_TYPE.FULL_TIME`, value: `Full-time`} as LocalizationItemResponse,
          { key: `JOB_TYPE.PART_TIME`, value: `Part-time`} as LocalizationItemResponse,
          { key: `JOB_TYPE.CONTRACT`, value: `Contract`} as LocalizationItemResponse,
          { key: `JOB_TYPE.TEMPORARY`, value: `Temporary`} as LocalizationItemResponse,
          { key: `JOB_TYPE.INTERN`, value: `Intern`} as LocalizationItemResponse,
          { key: `JOB_TYPE.VOLUNTEER`, value: `Volunteer`} as LocalizationItemResponse,
          { key: `JOB_TYPE.FREELANCE`, value: `Freelance`} as LocalizationItemResponse,
          { key: `JOB_TYPE.STARTUP`, value: `Startup`} as LocalizationItemResponse,
          { key: `JOB_TYPE.OTHER`, value: `Other`} as LocalizationItemResponse,
          { key: `JOB_SOURCE.JOB_BOARD`, value: `Job Board`} as LocalizationItemResponse,
          { key: `JOB_SOURCE.COMPANY_WEBSITE`, value: `Company Website`} as LocalizationItemResponse,
          { key: `JOB_SOURCE.RECOMMENDATION`, value: `Recommendation`} as LocalizationItemResponse,
          { key: `JOB_SOURCE.OTHER`, value: `Other`} as LocalizationItemResponse,
          { key: `EXPERIENCE_LEVEL.INTERNSHIP`, value: `Internship`} as LocalizationItemResponse,
          { key: `EXPERIENCE_LEVEL.ENTRY_LEVEL`, value: `Entry Level`} as LocalizationItemResponse,
          { key: `EXPERIENCE_LEVEL.JUNIOR`, value: `Junior`} as LocalizationItemResponse,
          { key: `EXPERIENCE_LEVEL.MID_LEVEL`, value: `Mid Level`} as LocalizationItemResponse,
          { key: `EXPERIENCE_LEVEL.SENIOR`, value: `Senior`} as LocalizationItemResponse,
          { key: `EXPERIENCE_LEVEL.EXECUTIVE`, value: `Executive`} as LocalizationItemResponse,
          { key: `COMMON.APPLICATIONS`, value: `Applications`} as LocalizationItemResponse,
          { key: `DATES.JANUARY_SHORT`, value: `Jan`} as LocalizationItemResponse,
          { key: `DATES.FEBRUARY_SHORT`, value: `Feb`} as LocalizationItemResponse,
          { key: `DATES.MARCH_SHORT`, value: `Mar`} as LocalizationItemResponse,
          { key: `DATES.APRIL_SHORT`, value: `Apr`} as LocalizationItemResponse,
          { key: `DATES.MAY_SHORT`, value: `May`} as LocalizationItemResponse,
          { key: `DATES.JUNE_SHORT`, value: `Jun`} as LocalizationItemResponse,
          { key: `DATES.JULY_SHORT`, value: `Jul`} as LocalizationItemResponse,
          { key: `DATES.AUGUST_SHORT`, value: `Aug`} as LocalizationItemResponse,
          { key: `DATES.SEPTEMBER_SHORT`, value: `Sep`} as LocalizationItemResponse,
          { key: `DATES.OCTOBER_SHORT`, value: `Oct`} as LocalizationItemResponse,
          { key: `DATES.NOVEMBER_SHORT`, value: `Nov`} as LocalizationItemResponse,
          { key: `DATES.DECEMBER_SHORT`, value: `Dec`} as LocalizationItemResponse,
          { key: `DATES.MONDAY_SHORT`, value: `Mon`} as LocalizationItemResponse,
          { key: `DATES.TUESDAY_SHORT`, value: `Tue`} as LocalizationItemResponse,
          { key: `DATES.WEDNESDAY_SHORT`, value: `Wed`} as LocalizationItemResponse,
          { key: `DATES.THURSDAY_SHORT`, value: `Thu`} as LocalizationItemResponse,
          { key: `DATES.FRIDAY_SHORT`, value: `Fri`} as LocalizationItemResponse,
          { key: `DATES.SATURDAY_SHORT`, value: `Sat`} as LocalizationItemResponse,
          { key: `DATES.SUNDAY_SHORT`, value: `Sun`} as LocalizationItemResponse,
          { key: `ERROR.USER_NOT_FOUND`, value: `User not found`} as LocalizationItemResponse,
          { key: `COMMON.OK`, value: `Ok`} as LocalizationItemResponse,
          { key: `COMMON.USER_PREFERENCES`, value: `User preferences`} as LocalizationItemResponse,
          { key: `ERROR.UPDATE_ONLY_OWN_SETTINGS`, value: `User can update only own settings`} as LocalizationItemResponse,
          { key: `COMMON.FIRST_NAME`, value: `First Name`} as LocalizationItemResponse,
          { key: `COMMON.LAST_NAME`, value: `Last Name`} as LocalizationItemResponse,
          { key: `COMMON.LANGUAGE`, value: `Language`} as LocalizationItemResponse,
          { key: `COMMON.TIME_ZONE`, value: `Time Zone`} as LocalizationItemResponse,
          { key: `COMMON.COUNTRY`, value: `Country`} as LocalizationItemResponse,
          { key: `COMMON.APPLICATION_AI_TEXTAREA`, value: `Application AI textarea`} as LocalizationItemResponse,
          { key: `MESSAGES.CHANGES_SUCCESSFULLY_SAVED`, value: `Changes have been saved successfully`} as LocalizationItemResponse,
          { key: `INPUT.TO_MANY_ITEMS.START_TYPING`, value: `Too many items. Please start typing`} as LocalizationItemResponse,
          { key: `ERROR.INVALID_URL`, value: `Invalid URL format`} as LocalizationItemResponse,
          { key: `ERROR.URL_NOT_HTTPS`, value: `URL is not using HTTPS`} as LocalizationItemResponse,
          { key: `ERROR.UNKNOWN_URL_TYPE`, value: `URL is safe but does not match a known username pattern`} as LocalizationItemResponse,
          { key: `COMMON.PHONE`, value: `Phone`} as LocalizationItemResponse,
          { key: `SKILL_LEVEL.BEGINNER`, value: `Beginner`} as LocalizationItemResponse,
          { key: `SKILL_LEVEL.BASIC`, value: `Basic`} as LocalizationItemResponse,
          { key: `SKILL_LEVEL.INTERMEDIATE`, value: `Intermediate`} as LocalizationItemResponse,
          { key: `SKILL_LEVEL.ADVANCED`, value: `Advanced`} as LocalizationItemResponse,
          { key: `SKILL_LEVEL.EXPERT`, value: `Expert`} as LocalizationItemResponse,
          { key: `SKILL_LEVEL.MASTER`, value: `Master`} as LocalizationItemResponse,
          { key: `SKILL_LEVEL.WORLD_CLASS`, value: `World-Class`} as LocalizationItemResponse,
          { key: `WORK_ARRANGEMENT.ON_SITE`, value: `On-site`} as LocalizationItemResponse,
          { key: `WORK_ARRANGEMENT.REMOTE`, value: `Remote`} as LocalizationItemResponse,
          { key: `WORK_ARRANGEMENT.HYBRID`, value: `Hybrid`} as LocalizationItemResponse,
          { key: `WORK_ARRANGEMENT.FLEXIBLE`, value: `Flexible`} as LocalizationItemResponse,
          { key: `WORK_ARRANGEMENT.TRAVEL_REQUIRED`, value: `Travel Required`} as LocalizationItemResponse,
          { key: `WORK_ARRANGEMENT.SHIFT_BASED`, value: `Shift-based`} as LocalizationItemResponse,
      ]
    } as LocalizationResponse,
    {
      locale: 'es',
      items: [
          { key: `AUTH.GREETINGS`, value: `¡Saludos, Honkler!`} as LocalizationItemResponse,
          { key: `AUTH.SIGN_IN.JOKE`, value: `Quizás necesitemos volver a`} as LocalizationItemResponse,
          { key: `COMMON.LOGIN_OR_EMAIL`, value: `Correo o nombre de usuario`} as LocalizationItemResponse,
          { key: `COMMON.PASSWORD`, value: `Contraseña`} as LocalizationItemResponse,
          { key: `COMMON.CONFIRM_PASSWORD`, value: `Confirmar contraseña`} as LocalizationItemResponse,
          { key: `COMMON.REMEMBER_ME`, value: `Recuérdame`} as LocalizationItemResponse,
          { key: `COMMON.FORGOT`, value: `Olvidé mi contraseña`} as LocalizationItemResponse,
          { key: `COMMON.SIGN_IN`, value: `Iniciar sesión`} as LocalizationItemResponse,
          { key: `COMMON.SIGN_UP`, value: `Registrarse`} as LocalizationItemResponse,
          { key: `AUTH.NO_ACCOUNT.SIGN_UP`, value: `¿No tienes una cuenta? Regístrate`} as LocalizationItemResponse,
          { key: `AUTH.HAS_ACCOUNT.SIGN_IN`, value: `¿Ya tienes una cuenta? Inicia Sesión`} as LocalizationItemResponse,
          { key: `COMMON.LOGIN`, value: `Iniciar sesión`} as LocalizationItemResponse,
          { key: `COMMON.EMAIL`, value: `Correo electrónico`} as LocalizationItemResponse,
          { key: `COMMON.CONFIRM_EMAIL`, value: `Confirmar correo electrónico`} as LocalizationItemResponse,
          { key: `COMMON.PROCEED`, value: `Continuar`} as LocalizationItemResponse,
          { key: `COMMON.FIRST_NAME`, value: `Nombre`} as LocalizationItemResponse,
          { key: `COMMON.LAST_NAME`, value: `Apellido`} as LocalizationItemResponse,
          { key: `COMMON.NO_COMPLAINTS`, value: `Sin quejas`} as LocalizationItemResponse,
          { key: `COMMON.WE_ARE_HONKING`, value: `¡Estamos tocando la bocina desde 2024!`} as LocalizationItemResponse,
          { key: `COMMON.DO_NOT_STORE_SENS_DATA`, value: `¡NO ALMACENES NINGÚN DATO SENSIBLE AQUÍ!`} as LocalizationItemResponse,
          { key: `COMMON.LIGHT_THEME`, value: `Tema claro`} as LocalizationItemResponse,
          { key: `COMMON.DARK_THEME`, value: `Tema oscuro`} as LocalizationItemResponse,
          { key: `ERROR.PASSWORDS_DO_NOT_MATCH`, value: `Las contraseñas no coinciden`} as LocalizationItemResponse,
          { key: `ERROR.EMAILS_DO_NOT_MATCH`, value: `Los correos electrónicos no coinciden`} as LocalizationItemResponse,
          { key: `ERROR.FIELD_REQUIRED`, value: `¡El campo es obligatorio!`} as LocalizationItemResponse,
          { key: `ERROR.CHECK_CHECKBOX`, value: `¡Por favor marque la casilla!`} as LocalizationItemResponse,
          { key: `ERROR.INVALID_EMAIL`, value: `¡Formato de correo electrónico no válido!`} as LocalizationItemResponse,
          { key: `MENU.HOME`, value: `Inicio`} as LocalizationItemResponse,
          { key: `MENU.JOBS`, value: `Empleos`} as LocalizationItemResponse,
          { key: `MENU.COMPANIES`, value: `Empresas`} as LocalizationItemResponse,
          { key: `MENU.KARMA`, value: `Karma`} as LocalizationItemResponse,
          { key: `COMMON.WELCOME_BACK`, value: `Bienvenido de nuevo`} as LocalizationItemResponse,
          { key: `MENU.ACTIVE_APPLICATIONS`, value: `Aplicaciones activas`} as LocalizationItemResponse,
          { key: `MENU.TODOS`, value: `Tareas`} as LocalizationItemResponse,
          { key: `MENU.RESPONSE_RATE`, value: `Tasa de respuesta`} as LocalizationItemResponse,
          { key: `MENU.UPCOMING_INTERVIEWS`, value: `Próximas entrevistas`} as LocalizationItemResponse,
          { key: `COMMON.NEW_APPLICATION`, value: `Nueva aplicación`} as LocalizationItemResponse,
          { key: `STATS.JOB_APPLICATIONS_TREND`, value: `Tendencia de aplicaciones`} as LocalizationItemResponse,
          { key: `STATS.TOP_COMPANIES`, value: `Empresas principales (Aplicaciones)`} as LocalizationItemResponse,
          { key: `STATS.NEW_JOB_LISTINGS_PER_DAY`, value: `Nuevas ofertas de empleo por día`} as LocalizationItemResponse,
          { key: `STATS.APPLICATION_STATUS_DISTRIBUTION`, value: `Distribución del estado de la aplicación`} as LocalizationItemResponse,
          { key: `STATUS.APPLIED`, value: `Aplicado`} as LocalizationItemResponse,
          { key: `STATUS.REJECTED`, value: `Rechazado`} as LocalizationItemResponse,
          { key: `STATUS.OFFER`, value: `Oferta`} as LocalizationItemResponse,
          { key: `STATUS.INTERVIEW`, value: `Entrevista`} as LocalizationItemResponse,
          { key: `STATUS.IN_REVIEW`, value: `En revisión`} as LocalizationItemResponse,
          { key: `COMMON.CREATE`, value: `Crear`} as LocalizationItemResponse,
          { key: `COMMON.EDIT`, value: `Editar`} as LocalizationItemResponse,
          { key: `COMMON.APPLICATION_LINK`, value: `Enlace de aplicación`} as LocalizationItemResponse,
          { key: `COMMON.JOB_TITLE`, value: `Título del trabajo`} as LocalizationItemResponse,
          { key: `COMMON.COMPANY`, value: `Empresa`} as LocalizationItemResponse,
          { key: `COMMON.LOCATION`, value: `Ubicación`} as LocalizationItemResponse,
          { key: `COMMON.EXPERIENCE_LEVEL`, value: `Nivel de experiencia`} as LocalizationItemResponse,
          { key: `COMMON.JOB_TYPE`, value: `Tipo de empleo`} as LocalizationItemResponse,
          { key: `COMMON.SOURCE`, value: `Fuente`} as LocalizationItemResponse,
          { key: `COMMON.SALARY_RANGE`, value: `Rango salarial`} as LocalizationItemResponse,
          { key: `COMMON.FROM`, value: `Desde`} as LocalizationItemResponse,
          { key: `COMMON.TO`, value: `Hasta`} as LocalizationItemResponse,
          { key: `COMMON.CURRENCY`, value: `Moneda`} as LocalizationItemResponse,
          { key: `COMMON.POSTED_DATE`, value: `Fecha de publicación`} as LocalizationItemResponse,
          { key: `COMMON.APPLICATION_DEADLINE`, value: `Fecha límite de aplicación`} as LocalizationItemResponse,
          { key: `COMMON.Contact_EMAIL`, value: `Correo de contacto`} as LocalizationItemResponse,
          { key: `COMMON.DESCRIPTION`, value: `Descripción`} as LocalizationItemResponse,
          { key: `COMMON.NOTES`, value: `Notas`} as LocalizationItemResponse,
          { key: `COMMON.CANCEL`, value: `Cancelar`} as LocalizationItemResponse,
          { key: `COMMON.UPDATE`, value: `Actualizar`} as LocalizationItemResponse,
          { key: `COMMON.EDIT_PROFILE`, value: `Editar perfil`} as LocalizationItemResponse,
          { key: `COMMON.EDIT_SKILLS`, value: `Editar habilidades`} as LocalizationItemResponse,
          { key: `COMMON.ADD_EXPERIENCE`, value: `Agregar experiencia`} as LocalizationItemResponse,
          { key: `COMMON.SKILLS`, value: `Habilidades`} as LocalizationItemResponse,
          { key: `COMMON.EXPERIENCE`, value: `Experiencia`} as LocalizationItemResponse,
          { key: `COMMON.EDUCATION`, value: `Educación`} as LocalizationItemResponse,
          { key: `COMMON.CERTIFICATIONS`, value: `Certificaciones`} as LocalizationItemResponse,
          { key: `ROLE.USER`, value: `Usuario`} as LocalizationItemResponse,
          { key: `ROLE.TECHNICAL_SUPPORT`, value: `Soporte técnico`} as LocalizationItemResponse,
          { key: `ROLE.ADMIN`, value: `Administrador`} as LocalizationItemResponse,
          { key: `ROLE.SUPER_ADMIN`, value: `Super Administrador`} as LocalizationItemResponse,
          { key: `JOB_TYPE.FULL_TIME`, value: `Tiempo completo`} as LocalizationItemResponse,
          { key: `JOB_TYPE.PART_TIME`, value: `Medio tiempo`} as LocalizationItemResponse,
          { key: `JOB_TYPE.CONTRACT`, value: `Contrato`} as LocalizationItemResponse,
          { key: `JOB_TYPE.TEMPORARY`, value: `Temporal`} as LocalizationItemResponse,
          { key: `JOB_TYPE.INTERN`, value: `Prácticas`} as LocalizationItemResponse,
          { key: `JOB_TYPE.VOLUNTEER`, value: `Voluntario`} as LocalizationItemResponse,
          { key: `JOB_TYPE.FREELANCE`, value: `Freelance`} as LocalizationItemResponse,
          { key: `JOB_TYPE.STARTUP`, value: `Startup`} as LocalizationItemResponse,
          { key: `JOB_TYPE.OTHER`, value: `Otro`} as LocalizationItemResponse,
          { key: `JOB_SOURCE.JOB_BOARD`, value: `Bolsa de trabajo`} as LocalizationItemResponse,
          { key: `JOB_SOURCE.COMPANY_WEBSITE`, value: `Sitio web de la empresa`} as LocalizationItemResponse,
          { key: `JOB_SOURCE.RECOMMENDATION`, value: `Recomendación`} as LocalizationItemResponse,
          { key: `JOB_SOURCE.OTHER`, value: `Otro`} as LocalizationItemResponse,
          { key: `EXPERIENCE_LEVEL.INTERNSHIP`, value: `Prácticas`} as LocalizationItemResponse,
          { key: `EXPERIENCE_LEVEL.ENTRY_LEVEL`, value: `Nivel de entrada`} as LocalizationItemResponse,
          { key: `EXPERIENCE_LEVEL.JUNIOR`, value: `Junior`} as LocalizationItemResponse,
          { key: `EXPERIENCE_LEVEL.MID_LEVEL`, value: `Nivel intermedio`} as LocalizationItemResponse,
          { key: `EXPERIENCE_LEVEL.SENIOR`, value: `Senior`} as LocalizationItemResponse,
          { key: `EXPERIENCE_LEVEL.EXECUTIVE`, value: `Ejecutivo`} as LocalizationItemResponse,
          { key: `COMMON.APPLICATIONS`, value: `Aplicaciones`} as LocalizationItemResponse,
          { key: `DATES.JANUARY_SHORT`, value: `Ene`} as LocalizationItemResponse,
          { key: `DATES.FEBRUARY_SHORT`, value: `Feb`} as LocalizationItemResponse,
          { key: `DATES.MARCH_SHORT`, value: `Mar`} as LocalizationItemResponse,
          { key: `DATES.APRIL_SHORT`, value: `Abr`} as LocalizationItemResponse,
          { key: `DATES.MAY_SHORT`, value: `May`} as LocalizationItemResponse,
          { key: `DATES.JUNE_SHORT`, value: `Jun`} as LocalizationItemResponse,
          { key: `DATES.JULY_SHORT`, value: `Jul`} as LocalizationItemResponse,
          { key: `DATES.AUGUST_SHORT`, value: `Ago`} as LocalizationItemResponse,
          { key: `DATES.SEPTEMBER_SHORT`, value: `Sep`} as LocalizationItemResponse,
          { key: `DATES.OCTOBER_SHORT`, value: `Oct`} as LocalizationItemResponse,
          { key: `DATES.NOVEMBER_SHORT`, value: `Nov`} as LocalizationItemResponse,
          { key: `DATES.DECEMBER_SHORT`, value: `Dic`} as LocalizationItemResponse,
          { key: `DATES.MONDAY_SHORT`, value: `Lun`} as LocalizationItemResponse,
          { key: `DATES.TUESDAY_SHORT`, value: `Mar`} as LocalizationItemResponse,
          { key: `DATES.WEDNESDAY_SHORT`, value: `Mié`} as LocalizationItemResponse,
          { key: `DATES.THURSDAY_SHORT`, value: `Jue`} as LocalizationItemResponse,
          { key: `DATES.FRIDAY_SHORT`, value: `Vie`} as LocalizationItemResponse,
          { key: `DATES.SATURDAY_SHORT`, value: `Sáb`} as LocalizationItemResponse,
          { key: `DATES.SUNDAY_SHORT`, value: `Dom`} as LocalizationItemResponse,
          { key: `ERROR.USER_NOT_FOUND`, value: `Usuario no encontrado`} as LocalizationItemResponse,
          { key: `COMMON.OK`, value: `Aceptar`} as LocalizationItemResponse,
          { key: `COMMON.USER_PREFERENCES`, value: `Preferencias del usuario`} as LocalizationItemResponse,
          { key: `ERROR.UPDATE_ONLY_OWN_SETTINGS`, value: `El usuario solo puede actualizar sus propias configuraciones`} as LocalizationItemResponse,
          { key: `COMMON.FIRST_NAME`, value: `Nombre`} as LocalizationItemResponse,
          { key: `COMMON.LAST_NAME`, value: `Apellido`} as LocalizationItemResponse,
          { key: `COMMON.LANGUAGE`, value: `Idioma`} as LocalizationItemResponse,
          { key: `COMMON.TIME_ZONE`, value: `Zona horaria`} as LocalizationItemResponse,
          { key: `COMMON.COUNTRY`, value: `País`} as LocalizationItemResponse,
          { key: `COMMON.APPLICATION_AI_TEXTAREA`, value: `Área de texto de IA de la aplicación`} as LocalizationItemResponse,
          { key: `MESSAGES.CHANGES_SUCCESSFULLY_SAVED`, value: `Los cambios se han guardado con éxito`} as LocalizationItemResponse,
          { key: `INPUT.TO_MANY_ITEMS.START_TYPING`, value: `Demasiados elementos. Por favor, comience a escribir`} as LocalizationItemResponse,
          { key: `ERROR.INVALID_URL`, value: `Formato de URL no válido`} as LocalizationItemResponse,
          { key: `ERROR.URL_NOT_HTTPS`, value: `La URL no usa HTTPS`} as LocalizationItemResponse,
          { key: `ERROR.UNKNOWN_URL_TYPE`, value: `La URL es segura pero no coincide con un patrón de nombre de usuario conocido`} as LocalizationItemResponse,
          { key: `COMMON.PHONE`, value: `Teléfono`} as LocalizationItemResponse,
          { key: `SKILL_LEVEL.BEGINNER`, value: `Principiante`} as LocalizationItemResponse,
          { key: `SKILL_LEVEL.BASIC`, value: `Básico`} as LocalizationItemResponse,
          { key: `SKILL_LEVEL.INTERMEDIATE`, value: `Intermedio`} as LocalizationItemResponse,
          { key: `SKILL_LEVEL.ADVANCED`, value: `Avanzado`} as LocalizationItemResponse,
          { key: `SKILL_LEVEL.EXPERT`, value: `Experto`} as LocalizationItemResponse,
          { key: `SKILL_LEVEL.MASTER`, value: `Maestro`} as LocalizationItemResponse,
          { key: `SKILL_LEVEL.WORLD_CLASS`, value: `Clase mundial`} as LocalizationItemResponse,
          { key: `WORK_ARRANGEMENT.ON_SITE`, value: `Presencial`} as LocalizationItemResponse,
          { key: `WORK_ARRANGEMENT.REMOTE`, value: `Remoto`} as LocalizationItemResponse,
          { key: `WORK_ARRANGEMENT.HYBRID`, value: `Híbrido`} as LocalizationItemResponse,
          { key: `WORK_ARRANGEMENT.FLEXIBLE`, value: `Flexible`} as LocalizationItemResponse,
          { key: `WORK_ARRANGEMENT.TRAVEL_REQUIRED`, value: `Se requiere viajar`} as LocalizationItemResponse,
      ]
    } as LocalizationResponse,
    {
      locale: 'fr',
      items: [
          { key: `AUTH.GREETINGS`, value: `Salutations, Honkler!`} as LocalizationItemResponse,
          { key: `AUTH.SIGN_IN.JOKE`, value: `Peut-être devons-nous revenir à`} as LocalizationItemResponse,
          { key: `COMMON.LOGIN_OR_EMAIL`, value: `Connexion ou Email`} as LocalizationItemResponse,
          { key: `COMMON.PASSWORD`, value: `Mot de passe`} as LocalizationItemResponse,
          { key: `COMMON.CONFIRM_PASSWORD`, value: `Confirmer le mot de passe`} as LocalizationItemResponse,
          { key: `COMMON.REMEMBER_ME`, value: `Se souvenir de moi`} as LocalizationItemResponse,
          { key: `COMMON.FORGOT`, value: `Mot de passe oublié`} as LocalizationItemResponse,
          { key: `COMMON.SIGN_IN`, value: `Se connecter`} as LocalizationItemResponse,
          { key: `COMMON.SIGN_UP`, value: `Sinscrire`} as LocalizationItemResponse,
          { key: `AUTH.NO_ACCOUNT.SIGN_UP`, value: `Vous n'avez pas de compte? Inscrivez-vous`} as LocalizationItemResponse,
          { key: `AUTH.HAS_ACCOUNT.SIGN_IN`, value: `Vous avez déjà un compte? Connectez-vous`} as LocalizationItemResponse,
          { key: `COMMON.LOGIN`, value: `Connexion`} as LocalizationItemResponse,
          { key: `COMMON.EMAIL`, value: `E-mail`} as LocalizationItemResponse,
          { key: `COMMON.CONFIRM_EMAIL`, value: `Confirmer l'e-mail`} as LocalizationItemResponse,
          { key: `COMMON.PROCEED`, value: `Continuer`} as LocalizationItemResponse,
          { key: `COMMON.FIRST_NAME`, value: `Prénom`} as LocalizationItemResponse,
          { key: `COMMON.LAST_NAME`, value: `Nom de famille`} as LocalizationItemResponse,
          { key: `COMMON.NO_COMPLAINTS`, value: `Aucune plainte`} as LocalizationItemResponse,
          { key: `COMMON.WE_ARE_HONKING`, value: `Nous klaxonnons depuis 2024!`} as LocalizationItemResponse,
          { key: `COMMON.DO_NOT_STORE_SENS_DATA`, value: `NE STOCKEZ AUCUNE DONNÉE SENSIBLE ICI!`} as LocalizationItemResponse,
          { key: `COMMON.LIGHT_THEME`, value: `Thème clair`} as LocalizationItemResponse,
          { key: `COMMON.DARK_THEME`, value: `Thème sombre`} as LocalizationItemResponse,
          { key: `ERROR.PASSWORDS_DO_NOT_MATCH`, value: `Les mots de passe ne correspondent pas`} as LocalizationItemResponse,
          { key: `ERROR.EMAILS_DO_NOT_MATCH`, value: `Les e-mails ne correspondent pas`} as LocalizationItemResponse,
          { key: `ERROR.FIELD_REQUIRED`, value: `Le champ est obligatoire!`} as LocalizationItemResponse,
          { key: `ERROR.CHECK_CHECKBOX`, value: `Veuillez cocher la case!`} as LocalizationItemResponse,
          { key: `ERROR.INVALID_EMAIL`, value: `Format d'email invalide!`} as LocalizationItemResponse,
          { key: `ERROR.UNEXPECTED_ERROR`, value: `Une erreur inattendue s'est produite!`} as LocalizationItemResponse,
          { key: `MENU.HOME`, value: `Accueil`} as LocalizationItemResponse,
          { key: `MENU.JOBS`, value: `Emplois`} as LocalizationItemResponse,
          { key: `MENU.COMPANIES`, value: `Entreprises`} as LocalizationItemResponse,
          { key: `MENU.KARMA`, value: `Karma`} as LocalizationItemResponse,
          { key: `COMMON.WELCOME_BACK`, value: `Bon retour`} as LocalizationItemResponse,
          { key: `MENU.ACTIVE_APPLICATIONS`, value: `Candidatures actives`} as LocalizationItemResponse,
          { key: `MENU.TODOS`, value: `Tâches`} as LocalizationItemResponse,
          { key: `MENU.RESPONSE_RATE`, value: `Taux de réponse`} as LocalizationItemResponse,
          { key: `MENU.UPCOMING_INTERVIEWS`, value: `Entretiens à venir`} as LocalizationItemResponse,
          { key: `COMMON.NEW_APPLICATION`, value: `Nouvelle candidature`} as LocalizationItemResponse,
          { key: `STATS.JOB_APPLICATIONS_TREND`, value: `Tendance des candidatures`} as LocalizationItemResponse,
          { key: `STATS.TOP_COMPANIES`, value: `Meilleures entreprises (Candidatures)`} as LocalizationItemResponse,
          { key: `STATS.NEW_JOB_LISTINGS_PER_DAY`, value: `Nouvelles offres d'emploi par jour`} as LocalizationItemResponse,
          { key: `STATS.APPLICATION_STATUS_DISTRIBUTION`, value: `Répartition des statuts de candidature`} as LocalizationItemResponse,
          { key: `STATUS.APPLIED`, value: `Postulé`} as LocalizationItemResponse,
          { key: `STATUS.REJECTED`, value: `Rejeté`} as LocalizationItemResponse,
          { key: `STATUS.OFFER`, value: `Offre`} as LocalizationItemResponse,
          { key: `STATUS.INTERVIEW`, value: `Entretien`} as LocalizationItemResponse,
          { key: `STATUS.IN_REVIEW`, value: `En cours d'examen`} as LocalizationItemResponse,
          { key: `COMMON.CREATE`, value: `Créer`} as LocalizationItemResponse,
          { key: `COMMON.EDIT`, value: `Modifier`} as LocalizationItemResponse,
          { key: `COMMON.APPLICATION_LINK`, value: `Lien de candidature`} as LocalizationItemResponse,
          { key: `COMMON.JOB_TITLE`, value: `Intitulé du poste`} as LocalizationItemResponse,
          { key: `COMMON.COMPANY`, value: `Entreprise`} as LocalizationItemResponse,
          { key: `COMMON.LOCATION`, value: `Lieu`} as LocalizationItemResponse,
          { key: `COMMON.EXPERIENCE_LEVEL`, value: `Niveau d'expérience`} as LocalizationItemResponse,
          { key: `COMMON.JOB_TYPE`, value: `Type d'emploi`} as LocalizationItemResponse,
          { key: `COMMON.SOURCE`, value: `Source`} as LocalizationItemResponse,
          { key: `COMMON.SALARY_RANGE`, value: `Échelle salariale`} as LocalizationItemResponse,
          { key: `COMMON.FROM`, value: `De`} as LocalizationItemResponse,
          { key: `COMMON.TO`, value: `À`} as LocalizationItemResponse,
          { key: `COMMON.CURRENCY`, value: `Devise`} as LocalizationItemResponse,
          { key: `COMMON.POSTED_DATE`, value: `Date de publication`} as LocalizationItemResponse,
          { key: `COMMON.APPLICATION_DEADLINE`, value: `Date limite de candidature`} as LocalizationItemResponse,
          { key: `COMMON.Contact_EMAIL`, value: `Email de contact`} as LocalizationItemResponse,
          { key: `COMMON.DESCRIPTION`, value: `Description`} as LocalizationItemResponse,
          { key: `COMMON.NOTES`, value: `Notes`} as LocalizationItemResponse,
          { key: `COMMON.CANCEL`, value: `Annuler`} as LocalizationItemResponse,
          { key: `COMMON.UPDATE`, value: `Mettre à jour`} as LocalizationItemResponse,
          { key: `COMMON.EDIT_PROFILE`, value: `Modifier le profil`} as LocalizationItemResponse,
          { key: `COMMON.EDIT_SKILLS`, value: `Modifier les compétences`} as LocalizationItemResponse,
          { key: `COMMON.ADD_EXPERIENCE`, value: `Ajouter une expérience`} as LocalizationItemResponse,
          { key: `COMMON.SKILLS`, value: `Compétences`} as LocalizationItemResponse,
          { key: `COMMON.EXPERIENCE`, value: `Expérience`} as LocalizationItemResponse,
          { key: `COMMON.EDUCATION`, value: `Éducation`} as LocalizationItemResponse,
          { key: `COMMON.CERTIFICATIONS`, value: `Certifications`} as LocalizationItemResponse,
          { key: `ROLE.USER`, value: `Utilisateur`} as LocalizationItemResponse,
          { key: `ROLE.TECHNICAL_SUPPORT`, value: `Support technique`} as LocalizationItemResponse,
          { key: `ROLE.ADMIN`, value: `Administrateur`} as LocalizationItemResponse,
          { key: `ROLE.SUPER_ADMIN`, value: `Super Administrateur`} as LocalizationItemResponse,
          { key: `JOB_TYPE.FULL_TIME`, value: `Temps plein`} as LocalizationItemResponse,
          { key: `JOB_TYPE.PART_TIME`, value: `Temps partiel`} as LocalizationItemResponse,
          { key: `JOB_TYPE.CONTRACT`, value: `Contrat`} as LocalizationItemResponse,
          { key: `JOB_TYPE.TEMPORARY`, value: `Temporaire`} as LocalizationItemResponse,
          { key: `JOB_TYPE.INTERN`, value: `Stagiaire`} as LocalizationItemResponse,
          { key: `JOB_TYPE.VOLUNTEER`, value: `Bénévole`} as LocalizationItemResponse,
          { key: `JOB_TYPE.FREELANCE`, value: `Freelance`} as LocalizationItemResponse,
          { key: `JOB_TYPE.STARTUP`, value: `Startup`} as LocalizationItemResponse,
          { key: `JOB_TYPE.OTHER`, value: `Autre`} as LocalizationItemResponse,
          { key: `JOB_SOURCE.JOB_BOARD`, value: `Site d'emploi`} as LocalizationItemResponse,
          { key: `JOB_SOURCE.COMPANY_WEBSITE`, value: `Site de l'entreprise`} as LocalizationItemResponse,
          { key: `JOB_SOURCE.RECOMMENDATION`, value: `Recommandation`} as LocalizationItemResponse,
          { key: `JOB_SOURCE.OTHER`, value: `Autre`} as LocalizationItemResponse,
          { key: `EXPERIENCE_LEVEL.INTERNSHIP`, value: `Stage`} as LocalizationItemResponse,
          { key: `EXPERIENCE_LEVEL.ENTRY_LEVEL`, value: `Débutant`} as LocalizationItemResponse,
          { key: `EXPERIENCE_LEVEL.JUNIOR`, value: `Junior`} as LocalizationItemResponse,
          { key: `EXPERIENCE_LEVEL.MID_LEVEL`, value: `Intermédiaire`} as LocalizationItemResponse,
          { key: `EXPERIENCE_LEVEL.SENIOR`, value: `Senior`} as LocalizationItemResponse,
          { key: `EXPERIENCE_LEVEL.EXECUTIVE`, value: `Cadre`} as LocalizationItemResponse,
          { key: `COMMON.APPLICATIONS`, value: `Applications`} as LocalizationItemResponse,
          { key: `DATES.JANUARY_SHORT`, value: `Janv`} as LocalizationItemResponse,
          { key: `DATES.FEBRUARY_SHORT`, value: `Févr`} as LocalizationItemResponse,
          { key: `DATES.MARCH_SHORT`, value: `Mars`} as LocalizationItemResponse,
          { key: `DATES.APRIL_SHORT`, value: `Avr`} as LocalizationItemResponse,
          { key: `DATES.MAY_SHORT`, value: `Mai`} as LocalizationItemResponse,
          { key: `DATES.JUNE_SHORT`, value: `Juin`} as LocalizationItemResponse,
          { key: `DATES.JULY_SHORT`, value: `Juil`} as LocalizationItemResponse,
          { key: `DATES.AUGUST_SHORT`, value: `Août`} as LocalizationItemResponse,
          { key: `DATES.SEPTEMBER_SHORT`, value: `Sept`} as LocalizationItemResponse,
          { key: `DATES.OCTOBER_SHORT`, value: `Oct`} as LocalizationItemResponse,
          { key: `DATES.NOVEMBER_SHORT`, value: `Nov`} as LocalizationItemResponse,
          { key: `DATES.DECEMBER_SHORT`, value: `Déc`} as LocalizationItemResponse,
          { key: `DATES.MONDAY_SHORT`, value: `Lun`} as LocalizationItemResponse,
          { key: `DATES.TUESDAY_SHORT`, value: `Mar`} as LocalizationItemResponse,
          { key: `DATES.WEDNESDAY_SHORT`, value: `Mer`} as LocalizationItemResponse,
          { key: `DATES.THURSDAY_SHORT`, value: `Jeu`} as LocalizationItemResponse,
          { key: `DATES.FRIDAY_SHORT`, value: `Ven`} as LocalizationItemResponse,
          { key: `DATES.SATURDAY_SHORT`, value: `Sam`} as LocalizationItemResponse,
          { key: `DATES.SUNDAY_SHORT`, value: `Dim`} as LocalizationItemResponse,
          { key: `ERROR.USER_NOT_FOUND`, value: `Utilisateur non trouvé`} as LocalizationItemResponse,
          { key: `COMMON.OK`, value: `Ok`} as LocalizationItemResponse,
          { key: `COMMON.USER_PREFERENCES`, value: `Préférences utilisateur`} as LocalizationItemResponse,
          { key: `ERROR.UPDATE_ONLY_OWN_SETTINGS`, value: `L'utilisateur ne peut mettre à jour que ses propres paramètres`} as LocalizationItemResponse,
          { key: `COMMON.FIRST_NAME`, value: `Prénom`} as LocalizationItemResponse,
          { key: `COMMON.LAST_NAME`, value: `Nom`} as LocalizationItemResponse,
          { key: `COMMON.LANGUAGE`, value: `Langue`} as LocalizationItemResponse,
          { key: `COMMON.TIME_ZONE`, value: `Fuseau horaire`} as LocalizationItemResponse,
          { key: `COMMON.COUNTRY`, value: `Pays`} as LocalizationItemResponse,
          { key: `COMMON.APPLICATION_AI_TEXTAREA`, value: `Zone de texte IA de l'application`} as LocalizationItemResponse,
          { key: `WORK_ARRANGEMENT.SHIFT_BASED`, value: `Por turnos`} as LocalizationItemResponse,
          { key: `MESSAGES.CHANGES_SUCCESSFULLY_SAVED`, value: `Les modifications ont été enregistrées avec succès`} as LocalizationItemResponse,
          { key: `INPUT.TO_MANY_ITEMS.START_TYPING`, value: `Trop d'éléments. Veuillez commencer à taper`} as LocalizationItemResponse,
          { key: `ERROR.INVALID_URL`, value: `Format d'URL invalide`} as LocalizationItemResponse,
          { key: `ERROR.URL_NOT_HTTPS`, value: `L'URL n'utilise pas HTTPS`} as LocalizationItemResponse,
          { key: `ERROR.UNKNOWN_URL_TYPE`, value: `L'URL est sûre mais ne correspond pas à un modèle de nom d'utilisateur connu`} as LocalizationItemResponse,
          { key: `COMMON.PHONE`, value: `Téléphone`} as LocalizationItemResponse,
          { key: `SKILL_LEVEL.BEGINNER`, value: `Débutant`} as LocalizationItemResponse,
          { key: `SKILL_LEVEL.BASIC`, value: `Basique`} as LocalizationItemResponse,
          { key: `SKILL_LEVEL.INTERMEDIATE`, value: `Intermédiaire`} as LocalizationItemResponse,
          { key: `SKILL_LEVEL.ADVANCED`, value: `Avancé`} as LocalizationItemResponse,
          { key: `SKILL_LEVEL.EXPERT`, value: `Expert`} as LocalizationItemResponse,
          { key: `SKILL_LEVEL.MASTER`, value: `Maître`} as LocalizationItemResponse,
          { key: `SKILL_LEVEL.WORLD_CLASS`, value: `De classe mondiale`} as LocalizationItemResponse,
          { key: `WORK_ARRANGEMENT.ON_SITE`, value: `Sur site`} as LocalizationItemResponse,
          { key: `WORK_ARRANGEMENT.REMOTE`, value: `À distance`} as LocalizationItemResponse,
          { key: `WORK_ARRANGEMENT.HYBRID`, value: `Hybride`} as LocalizationItemResponse,
          { key: `WORK_ARRANGEMENT.FLEXIBLE`, value: `Flexible`} as LocalizationItemResponse,
          { key: `WORK_ARRANGEMENT.TRAVEL_REQUIRED`, value: `Voyage requis`} as LocalizationItemResponse,
          { key: `WORK_ARRANGEMENT.SHIFT_BASED`, value: `Basé sur les quarts`} as LocalizationItemResponse,
      ]
    } as LocalizationResponse,
    {
      locale: 'ua',
      items: [
          { key: `AUTH.GREETINGS`, value: `Привіт, Хонклер!`} as LocalizationItemResponse,
          { key: `AUTH.SIGN_IN.JOKE`, value: `Можливо, нам потрібно повернутися до`} as LocalizationItemResponse,
          { key: `COMMON.LOGIN_OR_EMAIL`, value: `Логін або електронна пошта`} as LocalizationItemResponse,
          { key: `COMMON.PASSWORD`, value: `Пароль`} as LocalizationItemResponse,
          { key: `COMMON.CONFIRM_PASSWORD`, value: `Підтвердіть пароль`} as LocalizationItemResponse,
          { key: `COMMON.REMEMBER_ME`, value: `Запамятати мене`} as LocalizationItemResponse,
          { key: `COMMON.FORGOT`, value: `Забули пароль`} as LocalizationItemResponse,
          { key: `COMMON.SIGN_IN`, value: `Увійти`} as LocalizationItemResponse,
          { key: `COMMON.SIGN_UP`, value: `Зареєструватися`} as LocalizationItemResponse,
          { key: `AUTH.NO_ACCOUNT.SIGN_UP`, value: `Немає облікового запису? Зареєструйтеся`} as LocalizationItemResponse,
          { key: `AUTH.HAS_ACCOUNT.SIGN_IN`, value: `Вже маєте обліковий запис? Увійдіть`} as LocalizationItemResponse,
          { key: `COMMON.LOGIN`, value: `Логін`} as LocalizationItemResponse,
          { key: `COMMON.EMAIL`, value: `Електронна пошта`} as LocalizationItemResponse,
          { key: `COMMON.CONFIRM_EMAIL`, value: `Підтвердити електронну пошту`} as LocalizationItemResponse,
          { key: `COMMON.PROCEED`, value: `Продовжити`} as LocalizationItemResponse,
          { key: `COMMON.FIRST_NAME`, value: `Ім'я`} as LocalizationItemResponse,
          { key: `COMMON.LAST_NAME`, value: `Прізвище`} as LocalizationItemResponse,
          { key: `COMMON.NO_COMPLAINTS`, value: `Немає скарг`} as LocalizationItemResponse,
          { key: `COMMON.WE_ARE_HONKING`, value: `Ми сигналимо з 2024 року!`} as LocalizationItemResponse,
          { key: `COMMON.DO_NOT_STORE_SENS_DATA`, value: `НЕ ЗБЕРІГАЙТЕ ЖОДНИХ КОНФІДЕНЦІЙНИХ ДАНИХ!`} as LocalizationItemResponse,
          { key: `COMMON.LIGHT_THEME`, value: `Світла тема`} as LocalizationItemResponse,
          { key: `COMMON.DARK_THEME`, value: `Темна тема`} as LocalizationItemResponse,
          { key: `ERROR.PASSWORDS_DO_NOT_MATCH`, value: `Паролі не співпадають`} as LocalizationItemResponse,
          { key: `ERROR.EMAILS_DO_NOT_MATCH`, value: `Електронні адреси не співпадають`} as LocalizationItemResponse,
          { key: `ERROR.FIELD_REQUIRED`, value: `Поле є обов’язковим!`} as LocalizationItemResponse,
          { key: `ERROR.CHECK_CHECKBOX`, value: `Будь ласка, відмітьте поле!`} as LocalizationItemResponse,
          { key: `ERROR.INVALID_EMAIL`, value: `Невірний формат електронної пошти!`} as LocalizationItemResponse,
          { key: `MENU.HOME`, value: `Головна`} as LocalizationItemResponse,
          { key: `MENU.JOBS`, value: `Робота`} as LocalizationItemResponse,
          { key: `MENU.COMPANIES`, value: `Компанії`} as LocalizationItemResponse,
          { key: `MENU.KARMA`, value: `Карма`} as LocalizationItemResponse,
          { key: `COMMON.WELCOME_BACK`, value: `Ласкаво просимо`} as LocalizationItemResponse,
          { key: `MENU.ACTIVE_APPLICATIONS`, value: `Активні заявки`} as LocalizationItemResponse,
          { key: `MENU.TODOS`, value: `Завдання`} as LocalizationItemResponse,
          { key: `MENU.RESPONSE_RATE`, value: `Рівень відгуку`} as LocalizationItemResponse,
          { key: `MENU.UPCOMING_INTERVIEWS`, value: `Майбутні співбесіди`} as LocalizationItemResponse,
          { key: `COMMON.NEW_APPLICATION`, value: `Нова заявка`} as LocalizationItemResponse,
          { key: `STATS.JOB_APPLICATIONS_TREND`, value: `Тенденція заявок`} as LocalizationItemResponse,
          { key: `STATS.TOP_COMPANIES`, value: `Найкращі компанії (Заявки)`} as LocalizationItemResponse,
          { key: `STATS.NEW_JOB_LISTINGS_PER_DAY`, value: `Нові вакансії за день`} as LocalizationItemResponse,
          { key: `STATS.APPLICATION_STATUS_DISTRIBUTION`, value: `Розподіл статусу заявок`} as LocalizationItemResponse,
          { key: `STATUS.APPLIED`, value: `Подано`} as LocalizationItemResponse,
          { key: `STATUS.REJECTED`, value: `Відхилено`} as LocalizationItemResponse,
          { key: `STATUS.OFFER`, value: `Пропозиція`} as LocalizationItemResponse,
          { key: `STATUS.INTERVIEW`, value: `Співбесіда`} as LocalizationItemResponse,
          { key: `STATUS.IN_REVIEW`, value: `На розгляді`} as LocalizationItemResponse,
          { key: `COMMON.CREATE`, value: `Створити`} as LocalizationItemResponse,
          { key: `COMMON.EDIT`, value: `Редагувати`} as LocalizationItemResponse,
          { key: `COMMON.APPLICATION_LINK`, value: `Посилання на заявку`} as LocalizationItemResponse,
          { key: `COMMON.JOB_TITLE`, value: `Назва вакансії`} as LocalizationItemResponse,
          { key: `COMMON.COMPANY`, value: `Компанія`} as LocalizationItemResponse,
          { key: `COMMON.LOCATION`, value: `Місцезнаходження`} as LocalizationItemResponse,
          { key: `COMMON.EXPERIENCE_LEVEL`, value: `Рівень досвіду`} as LocalizationItemResponse,
          { key: `COMMON.JOB_TYPE`, value: `Тип роботи`} as LocalizationItemResponse,
          { key: `COMMON.SOURCE`, value: `Джерело`} as LocalizationItemResponse,
          { key: `COMMON.SALARY_RANGE`, value: `Діапазон зарплат`} as LocalizationItemResponse,
          { key: `COMMON.FROM`, value: `Від`} as LocalizationItemResponse,
          { key: `COMMON.TO`, value: `До`} as LocalizationItemResponse,
          { key: `COMMON.CURRENCY`, value: `Валюта`} as LocalizationItemResponse,
          { key: `COMMON.POSTED_DATE`, value: `Дата публікації`} as LocalizationItemResponse,
          { key: `COMMON.APPLICATION_DEADLINE`, value: `Кінцевий термін подачі заявки`} as LocalizationItemResponse,
          { key: `COMMON.Contact_EMAIL`, value: `Контактний Email`} as LocalizationItemResponse,
          { key: `COMMON.DESCRIPTION`, value: `Опис`} as LocalizationItemResponse,
          { key: `COMMON.NOTES`, value: `Примітки`} as LocalizationItemResponse,
          { key: `COMMON.CANCEL`, value: `Скасувати`} as LocalizationItemResponse,
          { key: `COMMON.UPDATE`, value: `Оновити`} as LocalizationItemResponse,
          { key: `COMMON.EDIT_PROFILE`, value: `Редагувати профіль`} as LocalizationItemResponse,
          { key: `COMMON.EDIT_SKILLS`, value: `Редагувати навички`} as LocalizationItemResponse,
          { key: `COMMON.ADD_EXPERIENCE`, value: `Додати досвід`} as LocalizationItemResponse,
          { key: `COMMON.SKILLS`, value: `Навички`} as LocalizationItemResponse,
          { key: `COMMON.EXPERIENCE`, value: `Досвід`} as LocalizationItemResponse,
          { key: `COMMON.EDUCATION`, value: `Освіта`} as LocalizationItemResponse,
          { key: `COMMON.CERTIFICATIONS`, value: `Сертифікації`} as LocalizationItemResponse,
          { key: `ROLE.USER`, value: `Користувач`} as LocalizationItemResponse,
          { key: `ROLE.TECHNICAL_SUPPORT`, value: `Технічна підтримка`} as LocalizationItemResponse,
          { key: `ROLE.ADMIN`, value: `Адміністратор`} as LocalizationItemResponse,
          { key: `ROLE.SUPER_ADMIN`, value: `Супер Адміністратор`} as LocalizationItemResponse,
          { key: `JOB_TYPE.FULL_TIME`, value: `Повний робочий день`} as LocalizationItemResponse,
          { key: `JOB_TYPE.PART_TIME`, value: `Неповний робочий день`} as LocalizationItemResponse,
          { key: `JOB_TYPE.CONTRACT`, value: `Контракт`} as LocalizationItemResponse,
          { key: `JOB_TYPE.TEMPORARY`, value: `Тимчасова робота`} as LocalizationItemResponse,
          { key: `JOB_TYPE.INTERN`, value: `Стажування`} as LocalizationItemResponse,
          { key: `JOB_TYPE.VOLUNTEER`, value: `Волонтерство`} as LocalizationItemResponse,
          { key: `JOB_TYPE.FREELANCE`, value: `Фріланс`} as LocalizationItemResponse,
          { key: `JOB_TYPE.STARTUP`, value: `Стартап`} as LocalizationItemResponse,
          { key: `JOB_TYPE.OTHER`, value: `Інше`} as LocalizationItemResponse,
          { key: `JOB_SOURCE.JOB_BOARD`, value: `Дошка вакансій`} as LocalizationItemResponse,
          { key: `JOB_SOURCE.COMPANY_WEBSITE`, value: `Веб-сайт компанії`} as LocalizationItemResponse,
          { key: `JOB_SOURCE.RECOMMENDATION`, value: `Рекомендація`} as LocalizationItemResponse,
          { key: `JOB_SOURCE.OTHER`, value: `Інше`} as LocalizationItemResponse,
          { key: `EXPERIENCE_LEVEL.INTERNSHIP`, value: `Стажування`} as LocalizationItemResponse,
          { key: `EXPERIENCE_LEVEL.ENTRY_LEVEL`, value: `Початковий рівень`} as LocalizationItemResponse,
          { key: `EXPERIENCE_LEVEL.JUNIOR`, value: `Молодший`} as LocalizationItemResponse,
          { key: `EXPERIENCE_LEVEL.MID_LEVEL`, value: `Середній рівень`} as LocalizationItemResponse,
          { key: `EXPERIENCE_LEVEL.SENIOR`, value: `Старший`} as LocalizationItemResponse,
          { key: `EXPERIENCE_LEVEL.EXECUTIVE`, value: `Керівник`} as LocalizationItemResponse,
          { key: `COMMON.APPLICATIONS`, value: `Аплікації`} as LocalizationItemResponse,
          { key: `DATES.JANUARY_SHORT`, value: `Січ`} as LocalizationItemResponse,
          { key: `DATES.FEBRUARY_SHORT`, value: `Лют`} as LocalizationItemResponse,
          { key: `DATES.MARCH_SHORT`, value: `Бер`} as LocalizationItemResponse,
          { key: `DATES.APRIL_SHORT`, value: `Кві`} as LocalizationItemResponse,
          { key: `DATES.MAY_SHORT`, value: `Тра`} as LocalizationItemResponse,
          { key: `DATES.JUNE_SHORT`, value: `Чер`} as LocalizationItemResponse,
          { key: `DATES.JULY_SHORT`, value: `Лип`} as LocalizationItemResponse,
          { key: `DATES.AUGUST_SHORT`, value: `Сер`} as LocalizationItemResponse,
          { key: `DATES.SEPTEMBER_SHORT`, value: `Вер`} as LocalizationItemResponse,
          { key: `DATES.OCTOBER_SHORT`, value: `Жов`} as LocalizationItemResponse,
          { key: `DATES.NOVEMBER_SHORT`, value: `Лис`} as LocalizationItemResponse,
          { key: `DATES.DECEMBER_SHORT`, value: `Гру`} as LocalizationItemResponse,
          { key: `DATES.MONDAY_SHORT`, value: `Пн`} as LocalizationItemResponse,
          { key: `DATES.TUESDAY_SHORT`, value: `Вт`} as LocalizationItemResponse,
          { key: `DATES.WEDNESDAY_SHORT`, value: `Ср`} as LocalizationItemResponse,
          { key: `DATES.THURSDAY_SHORT`, value: `Чт`} as LocalizationItemResponse,
          { key: `DATES.FRIDAY_SHORT`, value: `Пт`} as LocalizationItemResponse,
          { key: `DATES.SATURDAY_SHORT`, value: `Сб`} as LocalizationItemResponse,
          { key: `DATES.SUNDAY_SHORT`, value: `Нд`} as LocalizationItemResponse,
          { key: `ERROR.USER_NOT_FOUND`, value: `Користувача не знайдено`} as LocalizationItemResponse,
          { key: `COMMON.OK`, value: `Ок`} as LocalizationItemResponse,
          { key: `COMMON.USER_PREFERENCES`, value: `Налаштування користувача`} as LocalizationItemResponse,
          { key: `ERROR.UPDATE_ONLY_OWN_SETTINGS`, value: `Користувач може змінювати лише свої налаштування`} as LocalizationItemResponse,
          { key: `COMMON.FIRST_NAME`, value: `Ім'я`} as LocalizationItemResponse,
          { key: `COMMON.LAST_NAME`, value: `Прізвище`} as LocalizationItemResponse,
          { key: `COMMON.LANGUAGE`, value: `Мова`} as LocalizationItemResponse,
          { key: `COMMON.TIME_ZONE`, value: `Часовий пояс`} as LocalizationItemResponse,
          { key: `COMMON.COUNTRY`, value: `Країна`} as LocalizationItemResponse,
          { key: `COMMON.APPLICATION_AI_TEXTAREA`, value: `Текстова область AI додатку`} as LocalizationItemResponse,
          { key: `MESSAGES.CHANGES_SUCCESSFULLY_SAVED`, value: `Зміни успішно збережено`} as LocalizationItemResponse,
          { key: `INPUT.TO_MANY_ITEMS.START_TYPING`, value: `Забагато елементів. Почніть вводити текст`} as LocalizationItemResponse,
          { key: `ERROR.INVALID_URL`, value: `Невірний формат URL`} as LocalizationItemResponse,
          { key: `ERROR.URL_NOT_HTTPS`, value: `URL не використовує HTTPS`} as LocalizationItemResponse,
          { key: `ERROR.UNKNOWN_URL_TYPE`, value: `URL безпечний, але не відповідає відомому шаблону імені користувача`} as LocalizationItemResponse,
          { key: `COMMON.PHONE`, value: `Телефон`} as LocalizationItemResponse,
          { key: `SKILL_LEVEL.BEGINNER`, value: `Початківець`} as LocalizationItemResponse,
          { key: `SKILL_LEVEL.BASIC`, value: `Базовий`} as LocalizationItemResponse,
          { key: `SKILL_LEVEL.INTERMEDIATE`, value: `Середній`} as LocalizationItemResponse,
          { key: `SKILL_LEVEL.ADVANCED`, value: `Просунутий`} as LocalizationItemResponse,
          { key: `SKILL_LEVEL.EXPERT`, value: `Експерт`} as LocalizationItemResponse,
          { key: `SKILL_LEVEL.MASTER`, value: `Майстер`} as LocalizationItemResponse,
          { key: `SKILL_LEVEL.WORLD_CLASS`, value: `Світового класу`} as LocalizationItemResponse,
          { key: `WORK_ARRANGEMENT.ON_SITE`, value: `На місці`} as LocalizationItemResponse,
          { key: `WORK_ARRANGEMENT.REMOTE`, value: `Віддалено`} as LocalizationItemResponse,
          { key: `WORK_ARRANGEMENT.HYBRID`, value: `Гібридний`} as LocalizationItemResponse,
          { key: `WORK_ARRANGEMENT.FLEXIBLE`, value: `Гнучкий`} as LocalizationItemResponse,
          { key: `WORK_ARRANGEMENT.TRAVEL_REQUIRED`, value: `Потрібні поїздки`} as LocalizationItemResponse,
          { key: `WORK_ARRANGEMENT.SHIFT_BASED`, value: `Позмінний графік`} as LocalizationItemResponse,
      ]
    } as LocalizationResponse,
    {
      locale: 'ru',
      items: [
          { key: `AUTH.GREETINGS`, value: `Привет, Хонклер!`} as LocalizationItemResponse,
          { key: `AUTH.SIGN_IN.JOKE`, value: `Возможно, нам нужно вернуться к`} as LocalizationItemResponse,
          { key: `COMMON.LOGIN_OR_EMAIL`, value: `Логин или Email`} as LocalizationItemResponse,
          { key: `COMMON.PASSWORD`, value: `Пароль`} as LocalizationItemResponse,
          { key: `COMMON.CONFIRM_PASSWORD`, value: `Подтвердите пароль`} as LocalizationItemResponse,
          { key: `COMMON.REMEMBER_ME`, value: `Запомнить меня`} as LocalizationItemResponse,
          { key: `COMMON.FORGOT`, value: `Забыли пароль`} as LocalizationItemResponse,
          { key: `COMMON.SIGN_IN`, value: `Войти`} as LocalizationItemResponse,
          { key: `COMMON.SIGN_UP`, value: `Зарегистрироваться`} as LocalizationItemResponse,
          { key: `AUTH.NO_ACCOUNT.SIGN_UP`, value: `Нет учетной записи? Зарегистрируйтесь`} as LocalizationItemResponse,
          { key: `AUTH.HAS_ACCOUNT.SIGN_IN`, value: `Уже есть учетная запись? Войти`} as LocalizationItemResponse,
          { key: `COMMON.LOGIN`, value: `Логин`} as LocalizationItemResponse,
          { key: `COMMON.EMAIL`, value: `Электронная почта`} as LocalizationItemResponse,
          { key: `COMMON.CONFIRM_EMAIL`, value: `Подтвердите электронную почту`} as LocalizationItemResponse,
          { key: `COMMON.PROCEED`, value: `Продолжить`} as LocalizationItemResponse,
          { key: `COMMON.FIRST_NAME`, value: `Имя`} as LocalizationItemResponse,
          { key: `COMMON.LAST_NAME`, value: `Фамилия`} as LocalizationItemResponse,
          { key: `COMMON.NO_COMPLAINTS`, value: `Нет жалоб`} as LocalizationItemResponse,
          { key: `COMMON.WE_ARE_HONKING`, value: `Мы сигналим с 2024 года!`} as LocalizationItemResponse,
          { key: `COMMON.DO_NOT_STORE_SENS_DATA`, value: `НЕ СОХРАНЯЙТЕ КОНФИДЕНЦИАЛЬНЫЕ ДАННЫЕ!`} as LocalizationItemResponse,
          { key: `COMMON.LIGHT_THEME`, value: `Светлая тема`} as LocalizationItemResponse,
          { key: `COMMON.DARK_THEME`, value: `Темная тема`} as LocalizationItemResponse,
          { key: `ERROR.PASSWORDS_DO_NOT_MATCH`, value: `Пароли не совпадают`} as LocalizationItemResponse,
          { key: `ERROR.EMAILS_DO_NOT_MATCH`, value: `Электронные адреса не совпадают`} as LocalizationItemResponse,
          { key: `ERROR.FIELD_REQUIRED`, value: `Поле обязательно для заполнения!`} as LocalizationItemResponse,
          { key: `ERROR.CHECK_CHECKBOX`, value: `Пожалуйста, установите флажок!`} as LocalizationItemResponse,
          { key: `ERROR.INVALID_EMAIL`, value: `Неверный формат электронной почты!`} as LocalizationItemResponse,
          { key: `MENU.HOME`, value: `Главная`} as LocalizationItemResponse,
          { key: `MENU.JOBS`, value: `Вакансии`} as LocalizationItemResponse,
          { key: `MENU.COMPANIES`, value: `Компании`} as LocalizationItemResponse,
          { key: `MENU.KARMA`, value: `Карма`} as LocalizationItemResponse,
          { key: `COMMON.WELCOME_BACK`, value: `Добро пожаловать`} as LocalizationItemResponse,
          { key: `MENU.ACTIVE_APPLICATIONS`, value: `Активные заявки`} as LocalizationItemResponse,
          { key: `MENU.TODOS`, value: `Задачи`} as LocalizationItemResponse,
          { key: `MENU.RESPONSE_RATE`, value: `Уровень отклика`} as LocalizationItemResponse,
          { key: `MENU.UPCOMING_INTERVIEWS`, value: `Предстоящие интервью`} as LocalizationItemResponse,
          { key: `COMMON.NEW_APPLICATION`, value: `Новая заявка`} as LocalizationItemResponse,
          { key: `STATS.JOB_APPLICATIONS_TREND`, value: `Тренд заявок на работу`} as LocalizationItemResponse,
          { key: `STATS.TOP_COMPANIES`, value: `Топ компаний (заявки)`} as LocalizationItemResponse,
          { key: `STATS.NEW_JOB_LISTINGS_PER_DAY`, value: `Новые вакансии за день`} as LocalizationItemResponse,
          { key: `STATS.APPLICATION_STATUS_DISTRIBUTION`, value: `Распределение статуса заявок`} as LocalizationItemResponse,
          { key: `STATUS.APPLIED`, value: `Подано`} as LocalizationItemResponse,
          { key: `STATUS.REJECTED`, value: `Отклонено`} as LocalizationItemResponse,
          { key: `STATUS.OFFER`, value: `Предложение`} as LocalizationItemResponse,
          { key: `STATUS.INTERVIEW`, value: `Собеседование`} as LocalizationItemResponse,
          { key: `STATUS.IN_REVIEW`, value: `На рассмотрении`} as LocalizationItemResponse,
          { key: `COMMON.CREATE`, value: `Создать`} as LocalizationItemResponse,
          { key: `COMMON.EDIT`, value: `Редактировать`} as LocalizationItemResponse,
          { key: `COMMON.APPLICATION_LINK`, value: `Ссылка на заявку`} as LocalizationItemResponse,
          { key: `COMMON.JOB_TITLE`, value: `Название вакансии`} as LocalizationItemResponse,
          { key: `COMMON.COMPANY`, value: `Компания`} as LocalizationItemResponse,
          { key: `COMMON.LOCATION`, value: `Местоположение`} as LocalizationItemResponse,
          { key: `COMMON.EXPERIENCE_LEVEL`, value: `Уровень опыта`} as LocalizationItemResponse,
          { key: `COMMON.JOB_TYPE`, value: `Тип работы`} as LocalizationItemResponse,
          { key: `COMMON.SOURCE`, value: `Источник`} as LocalizationItemResponse,
          { key: `COMMON.SALARY_RANGE`, value: `Диапазон зарплаты`} as LocalizationItemResponse,
          { key: `COMMON.FROM`, value: `От`} as LocalizationItemResponse,
          { key: `COMMON.TO`, value: `До`} as LocalizationItemResponse,
          { key: `COMMON.CURRENCY`, value: `Валюта`} as LocalizationItemResponse,
          { key: `COMMON.POSTED_DATE`, value: `Дата публикации`} as LocalizationItemResponse,
          { key: `COMMON.APPLICATION_DEADLINE`, value: `Крайний срок подачи заявки`} as LocalizationItemResponse,
          { key: `COMMON.Contact_EMAIL`, value: `Контактный Email`} as LocalizationItemResponse,
          { key: `COMMON.DESCRIPTION`, value: `Описание`} as LocalizationItemResponse,
          { key: `COMMON.NOTES`, value: `Заметки`} as LocalizationItemResponse,
          { key: `COMMON.CANCEL`, value: `Отмена`} as LocalizationItemResponse,
          { key: `COMMON.UPDATE`, value: `Обновить`} as LocalizationItemResponse,
          { key: `COMMON.EDIT_PROFILE`, value: `Редактировать профиль`} as LocalizationItemResponse,
          { key: `COMMON.EDIT_SKILLS`, value: `Редактировать навыки`} as LocalizationItemResponse,
          { key: `COMMON.ADD_EXPERIENCE`, value: `Добавить опыт`} as LocalizationItemResponse,
          { key: `COMMON.SKILLS`, value: `Навыки`} as LocalizationItemResponse,
          { key: `COMMON.EXPERIENCE`, value: `Опыт`} as LocalizationItemResponse,
          { key: `COMMON.EDUCATION`, value: `Образование`} as LocalizationItemResponse,
          { key: `COMMON.CERTIFICATIONS`, value: `Сертификаты`} as LocalizationItemResponse,
          { key: `ROLE.USER`, value: `Пользователь`} as LocalizationItemResponse,
          { key: `ROLE.TECHNICAL_SUPPORT`, value: `Техническая поддержка`} as LocalizationItemResponse,
          { key: `ROLE.ADMIN`, value: `Администратор`} as LocalizationItemResponse,
          { key: `ROLE.SUPER_ADMIN`, value: `Супер Администратор`} as LocalizationItemResponse,
          { key: `JOB_TYPE.FULL_TIME`, value: `Полная занятость`} as LocalizationItemResponse,
          { key: `JOB_TYPE.PART_TIME`, value: `Частичная занятость`} as LocalizationItemResponse,
          { key: `JOB_TYPE.CONTRACT`, value: `Контракт`} as LocalizationItemResponse,
          { key: `JOB_TYPE.TEMPORARY`, value: `Временная работа`} as LocalizationItemResponse,
          { key: `JOB_TYPE.INTERN`, value: `Стажировка`} as LocalizationItemResponse,
          { key: `JOB_TYPE.VOLUNTEER`, value: `Волонтерство`} as LocalizationItemResponse,
          { key: `JOB_TYPE.FREELANCE`, value: `Фриланс`} as LocalizationItemResponse,
          { key: `JOB_TYPE.STARTUP`, value: `Стартап`} as LocalizationItemResponse,
          { key: `JOB_TYPE.OTHER`, value: `Другое`} as LocalizationItemResponse,
          { key: `JOB_SOURCE.JOB_BOARD`, value: `Доска вакансий`} as LocalizationItemResponse,
          { key: `JOB_SOURCE.COMPANY_WEBSITE`, value: `Сайт компании`} as LocalizationItemResponse,
          { key: `JOB_SOURCE.RECOMMENDATION`, value: `Рекомендация`} as LocalizationItemResponse,
          { key: `JOB_SOURCE.OTHER`, value: `Другое`} as LocalizationItemResponse,
          { key: `EXPERIENCE_LEVEL.INTERNSHIP`, value: `Стажировка`} as LocalizationItemResponse,
          { key: `EXPERIENCE_LEVEL.ENTRY_LEVEL`, value: `Начальный уровень`} as LocalizationItemResponse,
          { key: `EXPERIENCE_LEVEL.JUNIOR`, value: `Младший`} as LocalizationItemResponse,
          { key: `EXPERIENCE_LEVEL.MID_LEVEL`, value: `Средний уровень`} as LocalizationItemResponse,
          { key: `EXPERIENCE_LEVEL.SENIOR`, value: `Старший`} as LocalizationItemResponse,
          { key: `EXPERIENCE_LEVEL.EXECUTIVE`, value: `Руководитель`} as LocalizationItemResponse,
          { key: `COMMON.APPLICATIONS`, value: `Апликации`} as LocalizationItemResponse,
          { key: `DATES.JANUARY_SHORT`, value: `Янв`} as LocalizationItemResponse,
          { key: `DATES.FEBRUARY_SHORT`, value: `Фев`} as LocalizationItemResponse,
          { key: `DATES.MARCH_SHORT`, value: `Мар`} as LocalizationItemResponse,
          { key: `DATES.APRIL_SHORT`, value: `Апр`} as LocalizationItemResponse,
          { key: `DATES.MAY_SHORT`, value: `Май`} as LocalizationItemResponse,
          { key: `DATES.JUNE_SHORT`, value: `Июн`} as LocalizationItemResponse,
          { key: `DATES.JULY_SHORT`, value: `Июл`} as LocalizationItemResponse,
          { key: `DATES.AUGUST_SHORT`, value: `Авг`} as LocalizationItemResponse,
          { key: `DATES.SEPTEMBER_SHORT`, value: `Сен`} as LocalizationItemResponse,
          { key: `DATES.OCTOBER_SHORT`, value: `Окт`} as LocalizationItemResponse,
          { key: `DATES.NOVEMBER_SHORT`, value: `Ноя`} as LocalizationItemResponse,
          { key: `DATES.DECEMBER_SHORT`, value: `Дек`} as LocalizationItemResponse,
          { key: `DATES.MONDAY_SHORT`, value: `Пн`} as LocalizationItemResponse,
          { key: `DATES.TUESDAY_SHORT`, value: `Вт`} as LocalizationItemResponse,
          { key: `DATES.WEDNESDAY_SHORT`, value: `Ср`} as LocalizationItemResponse,
          { key: `DATES.THURSDAY_SHORT`, value: `Чт`} as LocalizationItemResponse,
          { key: `DATES.FRIDAY_SHORT`, value: `Пт`} as LocalizationItemResponse,
          { key: `DATES.SATURDAY_SHORT`, value: `Сб`} as LocalizationItemResponse,
          { key: `DATES.SUNDAY_SHORT`, value: `Вс`} as LocalizationItemResponse,
          { key: `ERROR.USER_NOT_FOUND`, value: `Пользователь не найден`} as LocalizationItemResponse,
          { key: `COMMON.OK`, value: `Ок`} as LocalizationItemResponse,
          { key: `COMMON.USER_PREFERENCES`, value: `Настройки пользователя`} as LocalizationItemResponse,
          { key: `ERROR.UPDATE_ONLY_OWN_SETTINGS`, value: `Пользователь может изменять только свои настройки`} as LocalizationItemResponse,
          { key: `COMMON.FIRST_NAME`, value: `Имя`} as LocalizationItemResponse,
          { key: `COMMON.LAST_NAME`, value: `Фамилия`} as LocalizationItemResponse,
          { key: `COMMON.LANGUAGE`, value: `Язык`} as LocalizationItemResponse,
          { key: `COMMON.TIME_ZONE`, value: `Часовой пояс`} as LocalizationItemResponse,
          { key: `COMMON.COUNTRY`, value: `Страна`} as LocalizationItemResponse,
          { key: `COMMON.APPLICATION_AI_TEXTAREA`, value: `Текстовое поле AI приложения`} as LocalizationItemResponse,
          { key: `MESSAGES.CHANGES_SUCCESSFULLY_SAVED`, value: `Изменения успешно сохранены`} as LocalizationItemResponse,
          { key: `INPUT.TO_MANY_ITEMS.START_TYPING`, value: `Слишком много элементов. Начните вводить текст`} as LocalizationItemResponse,
          { key: `ERROR.INVALID_URL`, value: `Неверный формат URL`} as LocalizationItemResponse,
          { key: `ERROR.URL_NOT_HTTPS`, value: `URL не использует HTTPS`} as LocalizationItemResponse,
          { key: `ERROR.UNKNOWN_URL_TYPE`, value: `URL безопасен, но не соответствует известному шаблону имени пользователя`} as LocalizationItemResponse,
          { key: `COMMON.PHONE`, value: `Телефон`} as LocalizationItemResponse,
          { key: `SKILL_LEVEL.BEGINNER`, value: `Новичок`} as LocalizationItemResponse,
          { key: `SKILL_LEVEL.BASIC`, value: `Базовый`} as LocalizationItemResponse,
          { key: `SKILL_LEVEL.INTERMEDIATE`, value: `Средний`} as LocalizationItemResponse,
          { key: `SKILL_LEVEL.ADVANCED`, value: `Продвинутый`} as LocalizationItemResponse,
          { key: `SKILL_LEVEL.EXPERT`, value: `Эксперт`} as LocalizationItemResponse,
          { key: `SKILL_LEVEL.MASTER`, value: `Мастер`} as LocalizationItemResponse,
          { key: `SKILL_LEVEL.WORLD_CLASS`, value: `Мирового уровня`} as LocalizationItemResponse,
          { key: `WORK_ARRANGEMENT.ON_SITE`, value: `На месте`} as LocalizationItemResponse,
          { key: `WORK_ARRANGEMENT.REMOTE`, value: `Удаленно`} as LocalizationItemResponse,
          { key: `WORK_ARRANGEMENT.HYBRID`, value: `Гибридный`} as LocalizationItemResponse,
          { key: `WORK_ARRANGEMENT.FLEXIBLE`, value: `Гибкий`} as LocalizationItemResponse,
          { key: `WORK_ARRANGEMENT.TRAVEL_REQUIRED`, value: `Требуются поездки`} as LocalizationItemResponse,
          { key: `WORK_ARRANGEMENT.SHIFT_BASED`, value: `Посменный график`} as LocalizationItemResponse,
      ]
    } as LocalizationResponse,
    {
      locale: 'de',
      items: [
          { key: `AUTH.GREETINGS`, value: `Grüße, Honkler!`} as LocalizationItemResponse,
          { key: `AUTH.SIGN_IN.JOKE`, value: `Vielleicht müssen wir zurück`} as LocalizationItemResponse,
          { key: `COMMON.LOGIN_OR_EMAIL`, value: `Login oder E-Mail`} as LocalizationItemResponse,
          { key: `COMMON.PASSWORD`, value: `Passwort`} as LocalizationItemResponse,
          { key: `COMMON.CONFIRM_PASSWORD`, value: `Passwort bestätigen`} as LocalizationItemResponse,
          { key: `COMMON.REMEMBER_ME`, value: `Erinnere dich an mich`} as LocalizationItemResponse,
          { key: `COMMON.FORGOT`, value: `Passwort vergessen`} as LocalizationItemResponse,
          { key: `COMMON.SIGN_IN`, value: `Anmelden`} as LocalizationItemResponse,
          { key: `COMMON.SIGN_UP`, value: `Registrieren`} as LocalizationItemResponse,
          { key: `AUTH.NO_ACCOUNT.SIGN_UP`, value: `Kein Konto? Registrieren`} as LocalizationItemResponse,
          { key: `AUTH.HAS_ACCOUNT.SIGN_IN`, value: `Bereits ein Konto? Anmelden`} as LocalizationItemResponse,
          { key: `COMMON.LOGIN`, value: `Anmeldung`} as LocalizationItemResponse,
          { key: `COMMON.EMAIL`, value: `E-Mail`} as LocalizationItemResponse,
          { key: `COMMON.CONFIRM_EMAIL`, value: `E-Mail bestätigen`} as LocalizationItemResponse,
          { key: `COMMON.PROCEED`, value: `Fortfahren`} as LocalizationItemResponse,
          { key: `COMMON.FIRST_NAME`, value: `Vorname`} as LocalizationItemResponse,
          { key: `COMMON.LAST_NAME`, value: `Nachname`} as LocalizationItemResponse,
          { key: `COMMON.NO_COMPLAINTS`, value: `Keine Beschwerden`} as LocalizationItemResponse,
          { key: `COMMON.WE_ARE_HONKING`, value: `Wir hupen seit 2024!`} as LocalizationItemResponse,
          { key: `COMMON.DO_NOT_STORE_SENS_DATA`, value: `SPEICHERN SIE HIER KEINE VERTRAULICHEN DATEN!`} as LocalizationItemResponse,
          { key: `COMMON.LIGHT_THEME`, value: `Helles Thema`} as LocalizationItemResponse,
          { key: `COMMON.DARK_THEME`, value: `Dunkles Thema`} as LocalizationItemResponse,
          { key: `ERROR.PASSWORDS_DO_NOT_MATCH`, value: `Passwörter stimmen nicht überein`} as LocalizationItemResponse,
          { key: `ERROR.EMAILS_DO_NOT_MATCH`, value: `E-Mail-Adressen stimmen nicht überein`} as LocalizationItemResponse,
          { key: `ERROR.FIELD_REQUIRED`, value: `Das Feld ist erforderlich!`} as LocalizationItemResponse,
          { key: `ERROR.CHECK_CHECKBOX`, value: `Bitte markieren Sie das Kästchen!`} as LocalizationItemResponse,
          { key: `ERROR.INVALID_EMAIL`, value: `Ungültiges E-Mail-Format!`} as LocalizationItemResponse,
          { key: `MENU.HOME`, value: `Startseite`} as LocalizationItemResponse,
          { key: `MENU.JOBS`, value: `Jobs`} as LocalizationItemResponse,
          { key: `MENU.COMPANIES`, value: `Unternehmen`} as LocalizationItemResponse,
          { key: `MENU.KARMA`, value: `Karma`} as LocalizationItemResponse,
          { key: `COMMON.WELCOME_BACK`, value: `Willkommen zurück`} as LocalizationItemResponse,
          { key: `MENU.ACTIVE_APPLICATIONS`, value: `Aktive Bewerbungen`} as LocalizationItemResponse,
          { key: `MENU.TODOS`, value: `Aufgaben`} as LocalizationItemResponse,
          { key: `MENU.RESPONSE_RATE`, value: `Antwortquote`} as LocalizationItemResponse,
          { key: `MENU.UPCOMING_INTERVIEWS`, value: `Bevorstehende Interviews`} as LocalizationItemResponse,
          { key: `COMMON.NEW_APPLICATION`, value: `Neue Bewerbung`} as LocalizationItemResponse,
          { key: `STATS.JOB_APPLICATIONS_TREND`, value: `Bewerbungstrend`} as LocalizationItemResponse,
          { key: `STATS.TOP_COMPANIES`, value: `Top-Unternehmen (Bewerbungen)`} as LocalizationItemResponse,
          { key: `STATS.NEW_JOB_LISTINGS_PER_DAY`, value: `Neue Stellenangebote pro Tag`} as LocalizationItemResponse,
          { key: `STATS.APPLICATION_STATUS_DISTRIBUTION`, value: `Verteilung des Bewerbungsstatus`} as LocalizationItemResponse,
          { key: `STATUS.APPLIED`, value: `Beworben`} as LocalizationItemResponse,
          { key: `STATUS.REJECTED`, value: `Abgelehnt`} as LocalizationItemResponse,
          { key: `STATUS.OFFER`, value: `Angebot`} as LocalizationItemResponse,
          { key: `STATUS.INTERVIEW`, value: `Vorstellungsgespräch`} as LocalizationItemResponse,
          { key: `STATUS.IN_REVIEW`, value: `In Überprüfung`} as LocalizationItemResponse,
          { key: `COMMON.CREATE`, value: `Erstellen`} as LocalizationItemResponse,
          { key: `COMMON.EDIT`, value: `Bearbeiten`} as LocalizationItemResponse,
          { key: `COMMON.APPLICATION_LINK`, value: `Bewerbungslink`} as LocalizationItemResponse,
          { key: `COMMON.JOB_TITLE`, value: `Jobtitel`} as LocalizationItemResponse,
          { key: `COMMON.COMPANY`, value: `Unternehmen`} as LocalizationItemResponse,
          { key: `COMMON.LOCATION`, value: `Standort`} as LocalizationItemResponse,
          { key: `COMMON.EXPERIENCE_LEVEL`, value: `Erfahrungsstufe`} as LocalizationItemResponse,
          { key: `COMMON.JOB_TYPE`, value: `Jobtyp`} as LocalizationItemResponse,
          { key: `COMMON.SOURCE`, value: `Quelle`} as LocalizationItemResponse,
          { key: `COMMON.SALARY_RANGE`, value: `Gehaltsbereich`} as LocalizationItemResponse,
          { key: `COMMON.FROM`, value: `Von`} as LocalizationItemResponse,
          { key: `COMMON.TO`, value: `Bis`} as LocalizationItemResponse,
          { key: `COMMON.CURRENCY`, value: `Währung`} as LocalizationItemResponse,
          { key: `COMMON.POSTED_DATE`, value: `Veröffentlichungsdatum`} as LocalizationItemResponse,
          { key: `COMMON.APPLICATION_DEADLINE`, value: `Bewerbungsschluss`} as LocalizationItemResponse,
          { key: `COMMON.Contact_EMAIL`, value: `Kontakt-E-Mail`} as LocalizationItemResponse,
          { key: `COMMON.DESCRIPTION`, value: `Beschreibung`} as LocalizationItemResponse,
          { key: `COMMON.NOTES`, value: `Notizen`} as LocalizationItemResponse,
          { key: `COMMON.CANCEL`, value: `Abbrechen`} as LocalizationItemResponse,
          { key: `COMMON.UPDATE`, value: `Aktualisieren`} as LocalizationItemResponse,
          { key: `COMMON.EDIT_PROFILE`, value: `Profil bearbeiten`} as LocalizationItemResponse,
          { key: `COMMON.EDIT_SKILLS`, value: `Fähigkeiten bearbeiten`} as LocalizationItemResponse,
          { key: `COMMON.ADD_EXPERIENCE`, value: `Erfahrung hinzufügen`} as LocalizationItemResponse,
          { key: `COMMON.SKILLS`, value: `Fähigkeiten`} as LocalizationItemResponse,
          { key: `COMMON.EXPERIENCE`, value: `Erfahrung`} as LocalizationItemResponse,
          { key: `COMMON.EDUCATION`, value: `Bildung`} as LocalizationItemResponse,
          { key: `COMMON.CERTIFICATIONS`, value: `Zertifikate`} as LocalizationItemResponse,
          { key: `ROLE.USER`, value: `Benutzer`} as LocalizationItemResponse,
          { key: `ROLE.TECHNICAL_SUPPORT`, value: `Technischer Support`} as LocalizationItemResponse,
          { key: `ROLE.ADMIN`, value: `Administrator`} as LocalizationItemResponse,
          { key: `ROLE.SUPER_ADMIN`, value: `Super Administrator`} as LocalizationItemResponse,
          { key: `JOB_TYPE.FULL_TIME`, value: `Vollzeit`} as LocalizationItemResponse,
          { key: `JOB_TYPE.PART_TIME`, value: `Teilzeit`} as LocalizationItemResponse,
          { key: `JOB_TYPE.CONTRACT`, value: `Vertrag`} as LocalizationItemResponse,
          { key: `JOB_TYPE.TEMPORARY`, value: `Temporär`} as LocalizationItemResponse,
          { key: `JOB_TYPE.INTERN`, value: `Praktikum`} as LocalizationItemResponse,
          { key: `JOB_TYPE.VOLUNTEER`, value: `Freiwilligendienst`} as LocalizationItemResponse,
          { key: `JOB_TYPE.FREELANCE`, value: `Freelance`} as LocalizationItemResponse,
          { key: `JOB_TYPE.STARTUP`, value: `Startup`} as LocalizationItemResponse,
          { key: `JOB_TYPE.OTHER`, value: `Andere`} as LocalizationItemResponse,
          { key: `JOB_SOURCE.JOB_BOARD`, value: `Jobbörse`} as LocalizationItemResponse,
          { key: `JOB_SOURCE.COMPANY_WEBSITE`, value: `Unternehmenswebsite`} as LocalizationItemResponse,
          { key: `JOB_SOURCE.RECOMMENDATION`, value: `Empfehlung`} as LocalizationItemResponse,
          { key: `JOB_SOURCE.OTHER`, value: `Andere`} as LocalizationItemResponse,
          { key: `EXPERIENCE_LEVEL.INTERNSHIP`, value: `Praktikum`} as LocalizationItemResponse,
          { key: `EXPERIENCE_LEVEL.ENTRY_LEVEL`, value: `Einstiegslevel`} as LocalizationItemResponse,
          { key: `EXPERIENCE_LEVEL.JUNIOR`, value: `Junior`} as LocalizationItemResponse,
          { key: `EXPERIENCE_LEVEL.MID_LEVEL`, value: `Mittleres Level`} as LocalizationItemResponse,
          { key: `EXPERIENCE_LEVEL.SENIOR`, value: `Senior`} as LocalizationItemResponse,
          { key: `EXPERIENCE_LEVEL.EXECUTIVE`, value: `Führungskraft`} as LocalizationItemResponse,
          { key: `COMMON.APPLICATIONS`, value: `Anwendungen`} as LocalizationItemResponse,
          { key: `DATES.JANUARY_SHORT`, value: `Jan`} as LocalizationItemResponse,
          { key: `DATES.FEBRUARY_SHORT`, value: `Feb`} as LocalizationItemResponse,
          { key: `DATES.MARCH_SHORT`, value: `Mär`} as LocalizationItemResponse,
          { key: `DATES.APRIL_SHORT`, value: `Apr`} as LocalizationItemResponse,
          { key: `DATES.MAY_SHORT`, value: `Mai`} as LocalizationItemResponse,
          { key: `DATES.JUNE_SHORT`, value: `Jun`} as LocalizationItemResponse,
          { key: `DATES.JULY_SHORT`, value: `Jul`} as LocalizationItemResponse,
          { key: `DATES.AUGUST_SHORT`, value: `Aug`} as LocalizationItemResponse,
          { key: `DATES.SEPTEMBER_SHORT`, value: `Sep`} as LocalizationItemResponse,
          { key: `DATES.OCTOBER_SHORT`, value: `Okt`} as LocalizationItemResponse,
          { key: `DATES.NOVEMBER_SHORT`, value: `Nov`} as LocalizationItemResponse,
          { key: `DATES.DECEMBER_SHORT`, value: `Dez`} as LocalizationItemResponse,
          { key: `DATES.MONDAY_SHORT`, value: `Mo`} as LocalizationItemResponse,
          { key: `DATES.TUESDAY_SHORT`, value: `Di`} as LocalizationItemResponse,
          { key: `DATES.WEDNESDAY_SHORT`, value: `Mi`} as LocalizationItemResponse,
          { key: `DATES.THURSDAY_SHORT`, value: `Do`} as LocalizationItemResponse,
          { key: `DATES.FRIDAY_SHORT`, value: `Fr`} as LocalizationItemResponse,
          { key: `DATES.SATURDAY_SHORT`, value: `Sa`} as LocalizationItemResponse,
          { key: `DATES.SUNDAY_SHORT`, value: `So`} as LocalizationItemResponse,
          { key: `ERROR.USER_NOT_FOUND`, value: `Benutzer nicht gefunden`} as LocalizationItemResponse,
          { key: `COMMON.OK`, value: `Ok`} as LocalizationItemResponse,
          { key: `COMMON.USER_PREFERENCES`, value: `Benutzereinstellungen`} as LocalizationItemResponse,
          { key: `ERROR.UPDATE_ONLY_OWN_SETTINGS`, value: `Benutzer kann nur eigene Einstellungen aktualisieren`} as LocalizationItemResponse,
          { key: `COMMON.FIRST_NAME`, value: `Vorname`} as LocalizationItemResponse,
          { key: `COMMON.LAST_NAME`, value: `Nachname`} as LocalizationItemResponse,
          { key: `COMMON.LANGUAGE`, value: `Sprache`} as LocalizationItemResponse,
          { key: `COMMON.TIME_ZONE`, value: `Zeitzone`} as LocalizationItemResponse,
          { key: `COMMON.COUNTRY`, value: `Land`} as LocalizationItemResponse,
          { key: `COMMON.APPLICATION_AI_TEXTAREA`, value: `KI-Textfeld der Anwendung`} as LocalizationItemResponse,
          { key: `MESSAGES.CHANGES_SUCCESSFULLY_SAVED`, value: `Änderungen wurden erfolgreich gespeichert`} as LocalizationItemResponse,
          { key: `INPUT.TO_MANY_ITEMS.START_TYPING`, value: `Zu viele Elemente. Bitte beginnen Sie mit der Eingabe`} as LocalizationItemResponse,
          { key: `ERROR.INVALID_URL`, value: `Ungültiges URL-Format`} as LocalizationItemResponse,
          { key: `ERROR.URL_NOT_HTTPS`, value: `Die URL verwendet kein HTTPS`} as LocalizationItemResponse,
          { key: `ERROR.UNKNOWN_URL_TYPE`, value: `Die URL ist sicher, entspricht jedoch keinem bekannten Benutzernamenmuster`} as LocalizationItemResponse,
          { key: `COMMON.PHONE`, value: `Telefon`} as LocalizationItemResponse,
          { key: `SKILL_LEVEL.BEGINNER`, value: `Anfänger`} as LocalizationItemResponse,
          { key: `SKILL_LEVEL.BASIC`, value: `Grundlegend`} as LocalizationItemResponse,
          { key: `SKILL_LEVEL.INTERMEDIATE`, value: `Mittelstufe`} as LocalizationItemResponse,
          { key: `SKILL_LEVEL.ADVANCED`, value: `Fortgeschritten`} as LocalizationItemResponse,
          { key: `SKILL_LEVEL.EXPERT`, value: `Experte`} as LocalizationItemResponse,
          { key: `SKILL_LEVEL.MASTER`, value: `Meister`} as LocalizationItemResponse,
          { key: `SKILL_LEVEL.WORLD_CLASS`, value: `Weltklasse`} as LocalizationItemResponse,
          { key: `WORK_ARRANGEMENT.ON_SITE`, value: `Vor Ort`} as LocalizationItemResponse,
          { key: `WORK_ARRANGEMENT.REMOTE`, value: `Fernarbeit`} as LocalizationItemResponse,
          { key: `WORK_ARRANGEMENT.HYBRID`, value: `Hybrid`} as LocalizationItemResponse,
          { key: `WORK_ARRANGEMENT.FLEXIBLE`, value: `Flexibel`} as LocalizationItemResponse,
          { key: `WORK_ARRANGEMENT.TRAVEL_REQUIRED`, value: `Reisen erforderlich`} as LocalizationItemResponse,
          { key: `WORK_ARRANGEMENT.SHIFT_BASED`, value: `Schichtbasiert`} as LocalizationItemResponse,
      ]
    } as LocalizationResponse,
    {
      locale: 'it',
      items: [
          { key: `AUTH.GREETINGS`, value: `Saluti, Honkler!`} as LocalizationItemResponse,
          { key: `AUTH.SIGN_IN.JOKE`, value: `Forse dobbiamo tornare a`} as LocalizationItemResponse,
          { key: `COMMON.LOGIN_OR_EMAIL`, value: `Login o Email`} as LocalizationItemResponse,
          { key: `COMMON.PASSWORD`, value: `Password`} as LocalizationItemResponse,
          { key: `COMMON.CONFIRM_PASSWORD`, value: `Conferma password`} as LocalizationItemResponse,
          { key: `COMMON.REMEMBER_ME`, value: `Ricordati di me`} as LocalizationItemResponse,
          { key: `COMMON.FORGOT`, value: `Password dimenticata`} as LocalizationItemResponse,
          { key: `COMMON.SIGN_IN`, value: `Accedi`} as LocalizationItemResponse,
          { key: `COMMON.SIGN_UP`, value: `Iscriviti`} as LocalizationItemResponse,
          { key: `AUTH.NO_ACCOUNT.SIGN_UP`, value: `Non hai un account? Iscriviti`} as LocalizationItemResponse,
          { key: `AUTH.HAS_ACCOUNT.SIGN_IN`, value: `Hai già un account? Accedi`} as LocalizationItemResponse,
          { key: `COMMON.LOGIN`, value: `Accesso`} as LocalizationItemResponse,
          { key: `COMMON.EMAIL`, value: `Email`} as LocalizationItemResponse,
          { key: `COMMON.CONFIRM_EMAIL`, value: `Conferma email`} as LocalizationItemResponse,
          { key: `COMMON.PROCEED`, value: `Procedere`} as LocalizationItemResponse,
          { key: `COMMON.FIRST_NAME`, value: `Nome`} as LocalizationItemResponse,
          { key: `COMMON.LAST_NAME`, value: `Cognome`} as LocalizationItemResponse,
          { key: `COMMON.NO_COMPLAINTS`, value: `Nessun reclamo`} as LocalizationItemResponse,
          { key: `COMMON.WE_ARE_HONKING`, value: `Stiamo suonando il clacson dal 2024!`} as LocalizationItemResponse,
          { key: `COMMON.DO_NOT_STORE_SENS_DATA`, value: `NON MEMORIZZARE ALCUN DATO SENSIBILE QUI!`} as LocalizationItemResponse,
          { key: `COMMON.LIGHT_THEME`, value: `Tema chiaro`} as LocalizationItemResponse,
          { key: `COMMON.DARK_THEME`, value: `Tema scuro`} as LocalizationItemResponse,
          { key: `ERROR.PASSWORDS_DO_NOT_MATCH`, value: `Le password non corrispondono`} as LocalizationItemResponse,
          { key: `ERROR.EMAILS_DO_NOT_MATCH`, value: `Le email non corrispondono`} as LocalizationItemResponse,
          { key: `ERROR.FIELD_REQUIRED`, value: `Il campo è obbligatorio!`} as LocalizationItemResponse,
          { key: `ERROR.CHECK_CHECKBOX`, value: `Si prega di selezionare la casella!`} as LocalizationItemResponse,
          { key: `ERROR.INVALID_EMAIL`, value: `Formato email non valido!`} as LocalizationItemResponse,
          { key: `MENU.HOME`, value: `Home`} as LocalizationItemResponse,
          { key: `MENU.JOBS`, value: `Lavori`} as LocalizationItemResponse,
          { key: `MENU.COMPANIES`, value: `Aziende`} as LocalizationItemResponse,
          { key: `MENU.KARMA`, value: `Karma`} as LocalizationItemResponse,
          { key: `COMMON.WELCOME_BACK`, value: `Bentornato`} as LocalizationItemResponse,
          { key: `MENU.ACTIVE_APPLICATIONS`, value: `Candidature attive`} as LocalizationItemResponse,
          { key: `MENU.TODOS`, value: `Attività`} as LocalizationItemResponse,
          { key: `MENU.RESPONSE_RATE`, value: `Tasso di risposta`} as LocalizationItemResponse,
          { key: `MENU.UPCOMING_INTERVIEWS`, value: `Prossimi colloqui`} as LocalizationItemResponse,
          { key: `COMMON.NEW_APPLICATION`, value: `Nuova candidatura`} as LocalizationItemResponse,
          { key: `STATS.JOB_APPLICATIONS_TREND`, value: `Tendenza delle candidature`} as LocalizationItemResponse,
          { key: `STATS.TOP_COMPANIES`, value: `Principali aziende (Candidature)`} as LocalizationItemResponse,
          { key: `STATS.NEW_JOB_LISTINGS_PER_DAY`, value: `Nuovi annunci di lavoro al giorno`} as LocalizationItemResponse,
          { key: `STATS.APPLICATION_STATUS_DISTRIBUTION`, value: `Distribuzione dello stato della candidatura`} as LocalizationItemResponse,
          { key: `STATUS.APPLIED`, value: `Candidatura inviata`} as LocalizationItemResponse,
          { key: `STATUS.REJECTED`, value: `Rifiutato`} as LocalizationItemResponse,
          { key: `STATUS.OFFER`, value: `Offerta`} as LocalizationItemResponse,
          { key: `STATUS.INTERVIEW`, value: `Colloquio`} as LocalizationItemResponse,
          { key: `STATUS.IN_REVIEW`, value: `In revisione`} as LocalizationItemResponse,
          { key: `COMMON.CREATE`, value: `Crea`} as LocalizationItemResponse,
          { key: `COMMON.EDIT`, value: `Modifica`} as LocalizationItemResponse,
          { key: `COMMON.APPLICATION_LINK`, value: `Link della candidatura`} as LocalizationItemResponse,
          { key: `COMMON.JOB_TITLE`, value: `Titolo del lavoro`} as LocalizationItemResponse,
          { key: `COMMON.COMPANY`, value: `Azienda`} as LocalizationItemResponse,
          { key: `COMMON.LOCATION`, value: `Posizione`} as LocalizationItemResponse,
          { key: `COMMON.EXPERIENCE_LEVEL`, value: `Livello di esperienza`} as LocalizationItemResponse,
          { key: `COMMON.JOB_TYPE`, value: `Tipo di lavoro`} as LocalizationItemResponse,
          { key: `COMMON.SOURCE`, value: `Fonte`} as LocalizationItemResponse,
          { key: `COMMON.SALARY_RANGE`, value: `Fascia salariale`} as LocalizationItemResponse,
          { key: `COMMON.FROM`, value: `Da`} as LocalizationItemResponse,
          { key: `COMMON.TO`, value: `A`} as LocalizationItemResponse,
          { key: `COMMON.CURRENCY`, value: `Valuta`} as LocalizationItemResponse,
          { key: `COMMON.POSTED_DATE`, value: `Data di pubblicazione`} as LocalizationItemResponse,
          { key: `COMMON.APPLICATION_DEADLINE`, value: `Scadenza della candidatura`} as LocalizationItemResponse,
          { key: `COMMON.Contact_EMAIL`, value: `Email di contatto`} as LocalizationItemResponse,
          { key: `COMMON.DESCRIPTION`, value: `Descrizione`} as LocalizationItemResponse,
          { key: `COMMON.NOTES`, value: `Note`} as LocalizationItemResponse,
          { key: `COMMON.CANCEL`, value: `Annulla`} as LocalizationItemResponse,
          { key: `COMMON.UPDATE`, value: `Aggiorna`} as LocalizationItemResponse,
          { key: `COMMON.EDIT_PROFILE`, value: `Modifica profilo`} as LocalizationItemResponse,
          { key: `COMMON.EDIT_SKILLS`, value: `Modifica competenze`} as LocalizationItemResponse,
          { key: `COMMON.ADD_EXPERIENCE`, value: `Aggiungi esperienza`} as LocalizationItemResponse,
          { key: `COMMON.SKILLS`, value: `Competenze`} as LocalizationItemResponse,
          { key: `COMMON.EXPERIENCE`, value: `Esperienza`} as LocalizationItemResponse,
          { key: `COMMON.EDUCATION`, value: `Istruzione`} as LocalizationItemResponse,
          { key: `COMMON.CERTIFICATIONS`, value: `Certificazioni`} as LocalizationItemResponse,
          { key: `ROLE.USER`, value: `Utente`} as LocalizationItemResponse,
          { key: `ROLE.TECHNICAL_SUPPORT`, value: `Supporto tecnico`} as LocalizationItemResponse,
          { key: `ROLE.ADMIN`, value: `Amministratore`} as LocalizationItemResponse,
          { key: `ROLE.SUPER_ADMIN`, value: `Super Amministratore`} as LocalizationItemResponse,
          { key: `JOB_TYPE.FULL_TIME`, value: `Tempo pieno`} as LocalizationItemResponse,
          { key: `JOB_TYPE.PART_TIME`, value: `Part-time`} as LocalizationItemResponse,
          { key: `JOB_TYPE.CONTRACT`, value: `Contratto`} as LocalizationItemResponse,
          { key: `JOB_TYPE.TEMPORARY`, value: `Temporaneo`} as LocalizationItemResponse,
          { key: `JOB_TYPE.INTERN`, value: `Tirocinio`} as LocalizationItemResponse,
          { key: `JOB_TYPE.VOLUNTEER`, value: `Volontariato`} as LocalizationItemResponse,
          { key: `JOB_TYPE.FREELANCE`, value: `Freelance`} as LocalizationItemResponse,
          { key: `JOB_TYPE.STARTUP`, value: `Startup`} as LocalizationItemResponse,
          { key: `JOB_TYPE.OTHER`, value: `Altro`} as LocalizationItemResponse,
          { key: `JOB_SOURCE.JOB_BOARD`, value: `Bacheca lavoro`} as LocalizationItemResponse,
          { key: `JOB_SOURCE.COMPANY_WEBSITE`, value: `Sito web aziendale`} as LocalizationItemResponse,
          { key: `JOB_SOURCE.RECOMMENDATION`, value: `Raccomandazione`} as LocalizationItemResponse,
          { key: `JOB_SOURCE.OTHER`, value: `Altro`} as LocalizationItemResponse,
          { key: `EXPERIENCE_LEVEL.INTERNSHIP`, value: `Tirocinio`} as LocalizationItemResponse,
          { key: `EXPERIENCE_LEVEL.ENTRY_LEVEL`, value: `Livello base`} as LocalizationItemResponse,
          { key: `EXPERIENCE_LEVEL.JUNIOR`, value: `Junior`} as LocalizationItemResponse,
          { key: `EXPERIENCE_LEVEL.MID_LEVEL`, value: `Livello intermedio`} as LocalizationItemResponse,
          { key: `EXPERIENCE_LEVEL.SENIOR`, value: `Senior`} as LocalizationItemResponse,
          { key: `EXPERIENCE_LEVEL.EXECUTIVE`, value: `Dirigente`} as LocalizationItemResponse,
          { key: `COMMON.APPLICATIONS`, value: `Applicazioni`} as LocalizationItemResponse,
          { key: `DATES.JANUARY_SHORT`, value: `Gen`} as LocalizationItemResponse,
          { key: `DATES.FEBRUARY_SHORT`, value: `Feb`} as LocalizationItemResponse,
          { key: `DATES.MARCH_SHORT`, value: `Mar`} as LocalizationItemResponse,
          { key: `DATES.APRIL_SHORT`, value: `Apr`} as LocalizationItemResponse,
          { key: `DATES.MAY_SHORT`, value: `Mag`} as LocalizationItemResponse,
          { key: `DATES.JUNE_SHORT`, value: `Giu`} as LocalizationItemResponse,
          { key: `DATES.JULY_SHORT`, value: `Lug`} as LocalizationItemResponse,
          { key: `DATES.AUGUST_SHORT`, value: `Ago`} as LocalizationItemResponse,
          { key: `DATES.SEPTEMBER_SHORT`, value: `Set`} as LocalizationItemResponse,
          { key: `DATES.OCTOBER_SHORT`, value: `Ott`} as LocalizationItemResponse,
          { key: `DATES.NOVEMBER_SHORT`, value: `Nov`} as LocalizationItemResponse,
          { key: `DATES.DECEMBER_SHORT`, value: `Dic`} as LocalizationItemResponse,
          { key: `DATES.MONDAY_SHORT`, value: `Lun`} as LocalizationItemResponse,
          { key: `DATES.TUESDAY_SHORT`, value: `Mar`} as LocalizationItemResponse,
          { key: `DATES.WEDNESDAY_SHORT`, value: `Mer`} as LocalizationItemResponse,
          { key: `DATES.THURSDAY_SHORT`, value: `Gio`} as LocalizationItemResponse,
          { key: `DATES.FRIDAY_SHORT`, value: `Ven`} as LocalizationItemResponse,
          { key: `DATES.SATURDAY_SHORT`, value: `Sab`} as LocalizationItemResponse,
          { key: `DATES.SUNDAY_SHORT`, value: `Dom`} as LocalizationItemResponse,
          { key: `ERROR.USER_NOT_FOUND`, value: `Utente non trovato`} as LocalizationItemResponse,
          { key: `COMMON.OK`, value: `Ok`} as LocalizationItemResponse,
          { key: `COMMON.USER_PREFERENCES`, value: `Preferenze utente`} as LocalizationItemResponse,
          { key: `ERROR.UPDATE_ONLY_OWN_SETTINGS`, value: `L'utente può aggiornare solo le proprie impostazioni`} as LocalizationItemResponse,
          { key: `COMMON.FIRST_NAME`, value: `Nome`} as LocalizationItemResponse,
          { key: `COMMON.LAST_NAME`, value: `Cognome`} as LocalizationItemResponse,
          { key: `COMMON.LANGUAGE`, value: `Lingua`} as LocalizationItemResponse,
          { key: `COMMON.TIME_ZONE`, value: `Fuso orario`} as LocalizationItemResponse,
          { key: `COMMON.COUNTRY`, value: `Paese`} as LocalizationItemResponse,
          { key: `COMMON.APPLICATION_AI_TEXTAREA`, value: `Area di testo AI dell'applicazione`} as LocalizationItemResponse,
          { key: `MESSAGES.CHANGES_SUCCESSFULLY_SAVED`, value: `Le modifiche sono state salvate con successo`} as LocalizationItemResponse,
          { key: `INPUT.TO_MANY_ITEMS.START_TYPING`, value: `Troppi elementi. Per favore, inizia a digitare`} as LocalizationItemResponse,
          { key: `ERROR.INVALID_URL`, value: `Formato URL non valido`} as LocalizationItemResponse,
          { key: `ERROR.URL_NOT_HTTPS`, value: `L'URL non utilizza HTTPS`} as LocalizationItemResponse,
          { key: `ERROR.UNKNOWN_URL_TYPE`, value: `L'URL è sicuro ma non corrisponde a un modello di nome utente noto`} as LocalizationItemResponse,
          { key: `COMMON.PHONE`, value: `Telefono`} as LocalizationItemResponse,
          { key: `SKILL_LEVEL.BEGINNER`, value: `Principiante`} as LocalizationItemResponse,
          { key: `SKILL_LEVEL.BASIC`, value: `Base`} as LocalizationItemResponse,
          { key: `SKILL_LEVEL.INTERMEDIATE`, value: `Intermedio`} as LocalizationItemResponse,
          { key: `SKILL_LEVEL.ADVANCED`, value: `Avanzato`} as LocalizationItemResponse,
          { key: `SKILL_LEVEL.EXPERT`, value: `Esperto`} as LocalizationItemResponse,
          { key: `SKILL_LEVEL.MASTER`, value: `Maestro`} as LocalizationItemResponse,
          { key: `SKILL_LEVEL.WORLD_CLASS`, value: `Di classe mondiale`} as LocalizationItemResponse,
          { key: `WORK_ARRANGEMENT.ON_SITE`, value: `In sede`} as LocalizationItemResponse,
          { key: `WORK_ARRANGEMENT.REMOTE`, value: `Remoto`} as LocalizationItemResponse,
          { key: `WORK_ARRANGEMENT.HYBRID`, value: `Ibrido`} as LocalizationItemResponse,
          { key: `WORK_ARRANGEMENT.FLEXIBLE`, value: `Flessibile`} as LocalizationItemResponse,
          { key: `WORK_ARRANGEMENT.TRAVEL_REQUIRED`, value: `Viaggi richiesti`} as LocalizationItemResponse,
          { key: `WORK_ARRANGEMENT.SHIFT_BASED`, value: `Basato sui turni`} as LocalizationItemResponse,
      ]
    } as LocalizationResponse,
  ],
  version: 'static'
} as LocalizationsResponse;
