// Auto-generated file from a4-localizations_ua.csv

export const localization_ua: Map<string, string> = new Map<string, string>([
  ['AUTH.GREETINGS', 'Привіт, друже, Хонклере!'],
  ['AUTH.SIGN_IN.JOKE', 'Можливо, нам потрібно повернутися до'],
  ['COMMON.LOGIN_OR_EMAIL', 'Логін або Email'],
  ['COMMON.PASSWORD', 'Пароль'],
  ['COMMON.CONFIRM_PASSWORD', 'Пароль'],
  ['COMMON.REMEMBER_ME', 'Запам\'ятати мене'],
  ['COMMON.FORGOT', 'Забули'],
  ['COMMON.SIGN_IN', 'Увійдіть'],
  ['COMMON.SIGN_UP', 'Зареєструватися'],
  ['AUTH.NO_ACCOUNT.SIGN_UP', 'Не маєте облікового запису? Зареєструватися'],
  ['AUTH.HAS_ACCOUNT.SIGN_IN', 'Вже маєте обліковий запис? Увійдіть'],
  ['COMMON.LOGIN', 'Логін'],
  ['COMMON.EMAIL', 'Email'],
  ['COMMON.CONFIRM_EMAIL', 'Підтвердити email'],
  ['COMMON.PROCEED', 'Продовжити'],
  ['COMMON.NO_COMPLAINTS', 'Немає скарг'],
  ['COMMON.WE_ARE_HONKING', 'Ми хонкаємо з 2024 року!'],
  ['COMMON.DO_NOT_STORE_SENS_DATA', 'НЕ ЗБЕРІГАЙТЕ ТУТ ЖОДНИХ КОНФІДЕНЦІЙНИХ ДАНИХ!'],
  ['COMMON.LIGHT_THEME', 'Світла тема'],
  ['COMMON.DARK_THEME', 'Темна тема'],
  ['ERROR.PASSWORDS_DO_NOT_MATCH', 'Паролі не підходять'],
  ['ERROR.EMAILS_DO_NOT_MATCH', 'Електронні адреси не збігаються'],
  ['ERROR.FIELD_REQUIRED', 'Поле обов\'язкове для заповнення!'],
  ['ERROR.CHECK_CHECKBOX', 'Будь ласка, поставте галочку!'],
  ['ERROR.INVALID_EMAIL', 'Неправильний формат електронної пошти!'],
  ['MENU.HOME', 'Головна'],
  ['MENU.JOBS', 'Вакансії'],
  ['MENU.COMPANIES', 'Компанії'],
  ['MENU.KARMA', 'Карма'],
  ['COMMON.WELCOME_BACK', 'Ласкаво просимо назад'],
  ['MENU.ACTIVE_APPLICATIONS', 'Активні заявки'],
  ['MENU.TODOS', 'TODOs'],
  ['MENU.RESPONSE_RATE', 'Відсоток відповідей'],
  ['MENU.UPCOMING_INTERVIEWS', 'Найближчі співбесіди'],
  ['COMMON.NEW_APPLICATION', 'Нова заявка'],
  ['STATS.JOB_APPLICATIONS_TREND', 'Тенденція заявок на вакансії'],
  ['STATS.TOP_COMPANIES', 'Найкращі компанії (заявки)'],
  ['STATS.NEW_JOB_LISTINGS_PER_DAY', 'Кількість нових вакансій на день'],
  ['STATS.APPLICATION_STATUS_DISTRIBUTION', 'Розподіл статусів заявок'],
  ['STATUS.APPLIED', 'Подано'],
  ['STATUS.REJECTED', 'Відхилено'],
  ['STATUS.OFFER', 'Пропозиція'],
  ['STATUS.INTERVIEW', 'Співбесіда'],
  ['STATUS.IN_REVIEW', 'На розгляді'],
  ['COMMON.CREATE', 'Створити'],
  ['COMMON.EDIT', 'Редагувати'],
  ['COMMON.APPLICATION_LINK', 'Посилання на заявку'],
  ['COMMON.JOB_TITLE', 'Назва посади'],
  ['COMMON.COMPANY', 'Компанія'],
  ['COMMON.LOCATION', 'Місцезнаходження'],
  ['COMMON.EXPERIENCE_LEVEL', 'Рівень досвіду'],
  ['COMMON.JOB_TYPE', 'Тип вакансії'],
  ['COMMON.SOURCE', 'Джерело'],
  ['COMMON.SALARY_RANGE', 'Діапазон заробітних плат'],
  ['COMMON.FROM', 'Від'],
  ['COMMON.TO', 'До'],
  ['COMMON.CURRENCY', 'Валюта'],
  ['COMMON.POSTED_DATE', 'Дата публікації'],
  ['COMMON.APPLICATION_DEADLINE', 'Дедлайн подачі заявок'],
  ['COMMON.Contact_EMAIL', 'Контактний email'],
  ['COMMON.DESCRIPTION', 'Опис'],
  ['COMMON.NOTES', 'Примітки'],
  ['COMMON.CANCEL', 'Скасувати'],
  ['COMMON.UPDATE', 'Оновити'],
  ['COMMON.EDIT_PROFILE', 'Редагувати профіль'],
  ['COMMON.EDIT_SKILLS', 'Редагувати навички'],
  ['COMMON.ADD_EXPERIENCE', 'Додати досвід'],
  ['COMMON.SKILLS', 'Навички'],
  ['COMMON.EXPERIENCE', 'Досвід роботи'],
  ['COMMON.EDUCATION', 'Освіта'],
  ['COMMON.CERTIFICATIONS', 'Сертифікати'],
  ['ROLE.USER', 'Користувач'],
  ['ROLE.TECHNICAL_SUPPORT', 'Технічна підтримка'],
  ['ROLE.ADMIN', 'Адміністратор'],
  ['ROLE.SUPER_ADMIN', 'Супер адміністратор'],
  ['JOB_TYPE.FULL_TIME', 'Повний робочий день'],
  ['JOB_TYPE.PART_TIME', 'Неповний робочий день'],
  ['JOB_TYPE.CONTRACT', 'Контракт'],
  ['JOB_TYPE.TEMPORARY', 'Тимчасовий'],
  ['JOB_TYPE.INTERN', 'Стажер'],
  ['JOB_TYPE.VOLUNTEER', 'Волонтер'],
  ['JOB_TYPE.FREELANCE', 'Фріланс'],
  ['JOB_TYPE.STARTUP', 'Стартап'],
  ['JOB_TYPE.OTHER', 'Інше'],
  ['JOB_SOURCE.JOB_BOARD', 'Дошка вакансій'],
  ['JOB_SOURCE.COMPANY_WEBSITE', 'Сайт компанії'],
  ['JOB_SOURCE.RECOMMENDATION', 'Рекомендація'],
  ['JOB_SOURCE.OTHER', 'Інше'],
  ['EXPERIENCE_LEVEL.INTERNSHIP', 'Стажування'],
  ['EXPERIENCE_LEVEL.ENTRY_LEVEL', 'Початковий рівень'],
  ['EXPERIENCE_LEVEL.JUNIOR', 'Молодший'],
  ['EXPERIENCE_LEVEL.MID_LEVEL', 'Середній рівень'],
  ['EXPERIENCE_LEVEL.SENIOR', 'Старший'],
  ['EXPERIENCE_LEVEL.EXECUTIVE', 'Керівник'],
  ['COMMON.APPLICATIONS', 'Заявки'],
  ['DATES.JANUARY_SHORT', 'Січ'],
  ['DATES.FEBRUARY_SHORT', 'Лют'],
  ['DATES.MARCH_SHORT', 'Бер'],
  ['DATES.APRIL_SHORT', 'Квіт'],
  ['DATES.MAY_SHORT', 'Трав'],
  ['DATES.JUNE_SHORT', 'Чер'],
  ['DATES.JULY_SHORT', 'Лип'],
  ['DATES.AUGUST_SHORT', 'Сер'],
  ['DATES.SEPTEMBER_SHORT', 'Вер'],
  ['DATES.OCTOBER_SHORT', 'Жов'],
  ['DATES.NOVEMBER_SHORT', 'Лист'],
  ['DATES.DECEMBER_SHORT', 'Гру'],
  ['DATES.MONDAY_SHORT', 'Пн'],
  ['DATES.TUESDAY_SHORT', 'Вт'],
  ['DATES.WEDNESDAY_SHORT', 'Ср'],
  ['DATES.THURSDAY_SHORT', 'Чт'],
  ['DATES.FRIDAY_SHORT', 'Пт'],
  ['DATES.SATURDAY_SHORT', 'Сб'],
  ['DATES.SUNDAY_SHORT', 'Нд'],
  ['ERROR.USER_NOT_FOUND', 'Користувача не знайдено'],
  ['COMMON.OK', 'Гаразд'],
  ['COMMON.USER_PREFERENCES', 'Налаштування користувача'],
  ['ERROR.UPDATE_ONLY_OWN_SETTINGS', 'Користувач може змінювати лише власні налаштування'],
  ['COMMON.FIRST_NAME', 'Ім\'я'],
  ['COMMON.LAST_NAME', 'Прізвище'],
  ['COMMON.LANGUAGE', 'Мова'],
  ['COMMON.TIME_ZONE', 'Часовий пояс'],
  ['COMMON.COUNTRY', 'Країна'],
  ['COMMON.APPLICATION_AI_TEXTAREA', 'Область тексту додатка AI'],
  ['MESSAGES.CHANGES_SUCCESSFULLY_SAVED', 'Зміни успішно збережено'],
  ['INPUT.TO_MANY_ITEMS.START_TYPING', 'Занадто багато товарів. Будь ласка, почніть вводити'],
  ['ERROR.INVALID_URL', 'Неправильний формат URL-адреси'],
  ['ERROR.URL_NOT_HTTPS', 'URL-адреса не використовує HTTPS'],
  ['ERROR.UNKNOWN_URL_TYPE', 'URL-адреса безпечна, але не відповідає відомому шаблону імені користувача'],
  ['COMMON.PHONE', 'Телефон'],
  ['SKILL_LEVEL.BEGINNER', 'Початковий'],
  ['SKILL_LEVEL.BASIC', 'Базовий'],
  ['SKILL_LEVEL.INTERMEDIATE', 'Проміжний'],
  ['SKILL_LEVEL.ADVANCED', 'Просунутий'],
  ['SKILL_LEVEL.EXPERT', 'Експерт'],
  ['SKILL_LEVEL.MASTER', 'Майстер'],
  ['SKILL_LEVEL.WORLD_CLASS', 'Світовий клас'],
  ['WORK_ARRANGEMENT.ON_SITE', 'Очний'],
  ['WORK_ARRANGEMENT.REMOTE', 'Дистанційний'],
  ['WORK_ARRANGEMENT.HYBRID', 'Гібридний'],
  ['WORK_ARRANGEMENT.FLEXIBLE', 'Гнучкий'],
  ['WORK_ARRANGEMENT.TRAVEL_REQUIRED', 'Потрібні відрядження'],
  ['WORK_ARRANGEMENT.SHIFT_BASED', 'Позмінний'],
  ['COMMON.ADD', 'Додати'],
  ['COMMON.REMOVE', 'Видалити'],
  ['COMMON.ALREADY_EXISTS', 'Вже існує'],
  ['COMMON.LANGUAGE_LEVEL', 'Мовний рівень'],
  ['COMMON.LANGUAGES', 'Мови'],
  ['COMMON.EDIT_LANGUAGES', 'Редагувати мови'],
  ['ERROR.COMMON_ERROR', 'Виникла непередбачувана помилка.'],
  ['ERROR.NOT_FOUND', 'Не знайдено'],
  ['ERROR.ENTITY_NOT_FOUND', 'Сутність не знайдено'],
  ['ERROR.ENTITY_WITH_ID_NOT_FOUND', 'Сутність з таким ідентифікатором не знайдено'],
  ['ERROR.ENTITY_WITH_EMAIL_ALREADY_EXISTS', 'Сутність з такою адресою вже існує'],
  ['ERROR.ENTITY_WITH_LOGIN_ALREADY_EXISTS', 'Сутність з таким логіном вже існує'],
  ['ERROR.VALIDATION_ERROR', 'Помилка валідації'],
  ['ERROR.ENTITY_ALREADY_EXISTS', 'Сутність вже існує'],
  ['ERROR.INTERNAL_SERVER_ERROR', 'Внутрішня помилка сервера'],
  ['ERROR.BLOCKED', 'Заблоковано'],
  ['ERROR.RESOURCE_NOT_FOUND', 'Ресурс не знайдено'],
  ['ERROR.ENTITY_BLOCKED', 'Сутність заблоковано'],
  ['ERROR.ENTITY_PESSIMISTIC_LOCKED', 'Сутність песимістично заблоковано'],
  ['ERROR.WRONG_AUTH', 'Неправильні облікові дані'],
  ['ERROR.FORBIDDEN', 'У доступі відмовлено'],
  ['ERROR.USER_BLOCKED', 'Користувача заблоковано'],
  ['ERROR.POTENTIAL_HARMFUL_CONTENT', 'Виявлено потенційно шкідливий вміст'],
  ['ERROR.JWT_MIN_LENGTH', 'JWT токен занадто короткий'],
  ['ERROR.JWT_INVALID_FORMAT', 'Неправильний формат JWT'],
  ['ERROR.JWT_USER_CLAIM_NOT_FOUND', 'Заявку користувача не знайдено в JWT'],
  ['ERROR.JWT_USER_CLAIM_INVALID_CONVERSION', 'Не вдається конвертувати вимогу користувача в JWT'],
  ['ERROR.FORGOT_PASSWORD_REQUEST_TOO_SOON', 'Забутий пароль запитано надто рано'],
  ['ERROR.RESTORE_PASSWORD_PROCESSING_ISSUE', 'Виникла помилка під час відновлення пароля'],
  ['ERROR.VERSION_NOT_SPECIFIED', 'Не вказано версію'],
  ['ERROR.USER_PROJECT_LIMIT_EXCEEDED', 'Користувач перевищив ліміт проекту'],
  ['ERROR.ROLE_NOT_SUPPORTED', 'Ця роль не підтримується'],
  ['STATUS.NEW', 'Новий'],
  ['STATUS.ACTIVE', 'Активна'],
  ['STATUS.INACTIVE', 'Неактивна'],
  ['STATUS.BLOCKED', 'Заблоковано'],
  ['STATUS.DELETED', 'Видалено'],
  ['STATUS.PENDING', 'На розгляді'],
  ['STATUS.APPROVED', 'Затверджено'],
  ['STATUS.COMPLETED', 'Завершено'],
  ['STATUS.CANCELLED', 'Скасовано'],
]);
