// Auto-generated file from a3-localizations_fr.csv

export const localization_fr: Map<string, string> = new Map<string, string>([
  ['AUTH.GREETINGS', 'Salutations, Honkler !'],
  ['AUTH.SIGN_IN.JOKE', 'Peut-être devons-nous revenir à'],
  ['AUTH.NO_ACCOUNT_SIGN_UP', 'Vous n\'avez pas de compte ? Inscrivez-vous maintenant !'],
  ['AUTH.HAS_ACCOUNT_SIGN_IN', 'Vous avez déjà un compte ? Connectez-vous maintenant !'],
  ['COMMON.FIX_ERROR_BEFORE_CONTINUE', 'Veuillez corriger l\'erreur avant de continuer.'],
  ['COMMON.WE_ARE_HONKING', 'Nous honkons depuis 2024!'],
  ['COMMON.BUTTON.OK', 'OK'],
  ['COMMON.BUTTON.CANCEL', 'Annuler'],
  ['COMMON.BUTTON.PROCEED', 'Continuer'],
  ['COMMON.BUTTON.SAVE', 'Enregistrer'],
  ['COMMON.BUTTON.UPDATE', 'Mettre à jour'],
  ['COMMON.BUTTON.HONK', 'Honk'],
  ['COMMON.BUTTON.ADD', 'Ajouter'],
  ['COMMON.BUTTON.REMOVE', 'Supprimer'],
  ['COMMON.BUTTON.EDIT', 'Modifier'],
  ['COMMON.BUTTON.CREATE', 'Créer'],
  ['COMMON.BUTTON.RESET', 'Réinitialiser'],
  ['AUTH.SIGN_IN.LOGIN_OR_EMAIL', 'Identifiant ou email'],
  ['COMMON.PASSWORD', 'Mot de passe'],
  ['AUTH.SIGN_IN.REMEMBER_ME', 'Se souvenir de moi'],
  ['AUTH.FORGOT', 'Mot de passe oublié ?'],
  ['AUTH.SIGN_IN.SIGN_IN', 'Se connecter'],
  ['COMMON.EMAIL', 'Email'],
  ['COMMON.LOGIN', 'Identifiant'],
  ['AUTH.SIGN_UP.WELCOME', 'Bienvenue dans la communauté Honkler !'],
  ['COMMON.FIRST_NAME', 'Prénom'],
  ['COMMON.LAST_NAME', 'Nom'],
  ['COMMON.CONFIRM_EMAIL', 'Confirmer l\'email'],
  ['COMMON.CONFIRM_PASSWORD', 'Confirmer le mot de passe'],
  ['COMMON.NO_COMPLAINTS', 'Aucune plainte'],
  ['COMMON.SIGN_UP', 'S\'inscrire'],
  ['PROFILE.EDUCATION.FIELD_OF_STUDY', 'Domaine d\'études'],
  ['PROFILE.EDUCATION.INSTITUTION', 'Établissement'],
  ['COMMON.DO_NOT_STORE_ANY_SENSITIVE_DATA', 'Ne stockez pas de données sensibles'],
  ['COMMON.START_DATE', 'Date de début'],
  ['COMMON.END_DATE', 'Date de fin'],
  ['COMMON.ISSUE_DATE', 'Date d\'émission'],
  ['COMMON.EXPIRATION_DATE', 'Date d\'expiration'],
  ['PROFILE.CERTIFICATION.CERTIFICATION', 'Certification'],
  ['PROFILE.CERTIFICATION.ISSUER', 'Émetteur'],
  ['PROFILE.PROJECT.PROJECT', 'Projet'],
  ['PROFILE.COMPANY.COMPANY', 'Entreprise'],
  ['PROFILE.ACHIEVEMENT.ACHIEVEMENT', 'Réalisation'],
  ['COMMON.POSITION', 'Poste'],
  ['COMMON.LOCATION', 'Lieu'],
  ['COMMON.COUNTRY', 'Pays'],
  ['JOB_TYPE.JOB_TYPE', 'Type d\'emploi'],
  ['JOB_TYPE.FULL_TIME', 'Temps plein'],
  ['JOB_TYPE.PART_TIME', 'Temps partiel'],
  ['JOB_TYPE.CONTRACT', 'Contrat'],
  ['JOB_TYPE.TEMPORARY', 'Temporaire'],
  ['JOB_TYPE.INTERN', 'Stage'],
  ['JOB_TYPE.VOLUNTEER', 'Volontaire'],
  ['JOB_TYPE.FREELANCE', 'Freelance'],
  ['JOB_TYPE.STARTUP', 'Startup'],
  ['JOB_TYPE.OTHER', 'Autre'],
  ['JOB_TYPE.DISTANCE', 'À distance'],
  ['JOB_TYPE.EVENING', 'Soir'],
  ['JOB_TYPE.ONLINE', 'En ligne'],
  ['JOB_TYPE.MIXED', 'Mixte'],
  ['JOB_TYPE.EXCHANGE', 'Échange'],
  ['JOB_TYPE.SELF_PACED', 'À son rythme'],
  ['JOB_TYPE.IN_PERSON', 'En présentiel'],
  ['JOB_TYPE.HYBRID', 'Hybride'],
  ['JOB_TYPE.PROCTORED_ONLINE', 'En ligne surveillé'],
  ['JOB_TYPE.UNPROCTORED', 'Non surveillé'],
  ['WORK_ARRANGEMENT.WORK_ARRANGEMENT', 'Modalité de travail'],
  ['WORK_ARRANGEMENT.ON_SITE', 'Sur site'],
  ['WORK_ARRANGEMENT.REMOTE', 'À distance'],
  ['WORK_ARRANGEMENT.HYBRID', 'Hybride'],
  ['WORK_ARRANGEMENT.FLEXIBLE', 'Flexible'],
  ['WORK_ARRANGEMENT.TRAVEL_REQUIRED', 'Déplacements requis'],
  ['WORK_ARRANGEMENT.SHIFT_BASED', 'Par quarts'],
  ['COMMON.DESCRIPTION', 'Description'],
  ['COMMON.SALARY_RANGE', 'Échelle salariale'],
  ['COMMON.FROM', 'De'],
  ['COMMON.TO', 'À'],
  ['COMMON.SKILLS', 'Compétences'],
  ['COMMON.SKILL', 'Compétence'],
  ['EXPERIENCE_LEVEL.EXPERIENCE_LEVEL', 'Niveau d\'expérience'],
  ['EXPERIENCE_LEVEL.INTERNSHIP', 'Stage'],
  ['EXPERIENCE_LEVEL.ENTRY_LEVEL', 'Débutant'],
  ['EXPERIENCE_LEVEL.JUNIOR', 'Junior'],
  ['EXPERIENCE_LEVEL.MID_LEVEL', 'Intermédiaire'],
  ['EXPERIENCE_LEVEL.SENIOR', 'Senior'],
  ['EXPERIENCE_LEVEL.LEADER', 'Lead'],
  ['EXPERIENCE_LEVEL.EXECUTIVE', 'Cadre'],
  ['EXPERIENCE_LEVEL.PRINCIPAL', 'Principal'],
  ['EXPERIENCE_LEVEL.STAFF', 'Personnel'],
  ['EXPERIENCE_LEVEL.OTHER', 'Autre'],
  ['EXPERIENCE_LEVEL.TIER_1', 'Niveau 1'],
  ['EXPERIENCE_LEVEL.TIER_2', 'Niveau 2'],
  ['EXPERIENCE_LEVEL.TIER_3', 'Niveau 3'],
  ['EXPERIENCE_LEVEL.TIER_4', 'Niveau 4'],
  ['EXPERIENCE_LEVEL.TIER_5', 'Niveau 5'],
  ['EXPERIENCE_LEVEL.TIER_6', 'Niveau 6'],
  ['EXPERIENCE_LEVEL.TIER_7', 'Niveau 7'],
  ['COMMON.LANGUAGES', 'Langues'],
  ['COMMON.LANGUAGE', 'Langue'],
  ['LANGUAGE_LEVEL.LANGUAGE_LEVEL', 'Niveau de langue'],
  ['LANGUAGE_LEVEL.BEGINNER', 'Débutant'],
  ['LANGUAGE_LEVEL.ELEMENTARY', 'Élémentaire'],
  ['LANGUAGE_LEVEL.INTERMEDIATE', 'Intermédiaire'],
  ['LANGUAGE_LEVEL.UPPER_INTERMEDIATE', 'Intermédiaire supérieur'],
  ['LANGUAGE_LEVEL.ADVANCED', 'Avancé'],
  ['LANGUAGE_LEVEL.PROFICIENT', 'Compétent'],
  ['LANGUAGE_LEVEL.NATIVE', 'Natif'],
  ['PROFILE.SECTION.PRIMARY_INFO', 'Informations principales'],
  ['PROFILE.SECTION.AUTH_SECTION', 'Section d\'authentification'],
  ['PROFILE.HEADLINE', 'Titre'],
  ['PROFILE.SECTION.SECONDARY_INFO', 'Informations secondaires'],
  ['COMMON.CURRENCY', 'Devise'],
  ['COMMON.TIME_ZONE', 'Fuseau horaire'],
  ['COMMON.PHONE', 'Téléphone'],
  ['PROFILE.LINKS', 'Liens'],
  ['PROFILE.SECTION.AI', 'IA'],
  ['PROFILE.APPLICATION.AI_TEXTAREA', 'Zone de texte IA pour les candidatures'],
  ['THEME.DARK', 'Thème sombre'],
  ['THEME.LIGHT', 'Thème clair'],
  ['MENU.HOME', 'Accueil'],
  ['MENU.JOBS', 'Emplois'],
  ['MENU.COMPANIES', 'Entreprises'],
  ['MENU.KARMA', 'Karma'],
  ['IN_DEVELOPMENT.OOPS_PAGE', 'Oups ! Page en construction.'],
  ['COMMON.GO_HOME', 'Retour à l\'accueil'],
  ['COMMON.BACK_TO_SIGN_IN', 'Retour à la connexion'],
  ['NOT_FOUND.PAGE_NOT_FOUND', 'Oups ! La page que vous recherchez n\'existe pas.'],
  ['MENU.ACTIVE_APPLICATIONS', 'Candidatures actives'],
  ['MENU.TODOS', 'Tâches'],
  ['MENU.RESPONSE_RATE', 'Taux de réponse'],
  ['MENU.UPCOMING_INTERVIEWS', 'Entretiens à venir'],
  ['STATS.NEW_JOB_LISTINGS_PER_DAY', 'Nouvelles offres par jour'],
  ['STATS.JOB_APPLICATIONS_TREND', 'Tendance des candidatures'],
  ['COMMON.JOB.NEW_APPLICATION', 'Candidature'],
  ['COMMON.JOB.NEW_APPLICATIONS', 'Candidatures'],
  ['STATS.TOP_COMPANIES', 'Meilleures entreprises'],
  ['STATS.APPLICATION_STATUS_DISTRIBUTION', 'Distribution des statuts de candidature'],
  ['JOB_STATUS.APPLIED', 'Postulé'],
  ['JOB_STATUS.IN_REVIEW', 'En cours d\'examen'],
  ['JOB_STATUS.INTERVIEW', 'Entretien'],
  ['JOB_STATUS.OFFER', 'Offre'],
  ['JOB_STATUS.REJECTED', 'Rejeté'],
  ['COMMON.WELCOME_BACK', 'Bon retour parmi nous !'],
  ['PROFILE.SECTION.WORK_EXPERIENCE', 'Expérience professionnelle'],
  ['PROFILE.SECTION.EDUCATION', 'Formation'],
  ['PROFILE.SECTION.PROJECTS', 'Projets'],
  ['PROFILE.SECTION.ACHIEVEMENTS', 'Réalisations'],
  ['PROFILE.SECTION.CERTIFICATIONS', 'Certifications'],
  ['COMMON.EMPTY_SECTION', 'Section vide'],
  ['PROFILE.USER_PREFERENCES', 'Préférences utilisateur'],
  ['ERROR.NOT_FOUND', 'Non trouvé'],
  ['ERROR.ENTITY_NOT_FOUND', 'Entité non trouvée'],
  ['ERROR.ENTITY_WITH_ID_NOT_FOUND', 'Entité avec ID non trouvée'],
  ['ERROR.ENTITY_WITH_EMAIL_ALREADY_EXISTS', 'Entité avec cet email existe déjà'],
  ['ERROR.ENTITY_WITH_LOGIN_ALREADY_EXISTS', 'Entité avec cet identifiant existe déjà'],
  ['ERROR.VALIDATION_ERROR', 'Erreur de validation'],
  ['ERROR.ENTITY_ALREADY_EXISTS', 'Entité existe déjà'],
  ['ERROR.ALREADY_EXISTS', 'Existe déjà'],
  ['ERROR.INTERNAL_SERVER_ERROR', 'Erreur interne du serveur'],
  ['ERROR.BLOCKED', 'Bloqué'],
  ['ERROR.RESOURCE_NOT_FOUND', 'Ressource non trouvée'],
  ['ERROR.ENTITY_BLOCKED', 'Entité bloquée'],
  ['ERROR.ENTITY_PESSIMISTIC_LOCKED', 'Entité verrouillée'],
  ['ERROR.WRONG_AUTH', 'Authentification incorrecte'],
  ['ERROR.FORBIDDEN', 'Interdit'],
  ['ERROR.USER_BLOCKED', 'Utilisateur bloqué'],
  ['ERROR.POTENTIAL_HARMFUL_CONTENT', 'Contenu potentiellement dangereux'],
  ['ERROR.JWT_MIN_LENGTH', 'Longueur minimale du JWT'],
  ['ERROR.JWT_INVALID_FORMAT', 'Format JWT invalide'],
  ['ERROR.JWT_USER_CLAIM_NOT_FOUND', 'Revendication utilisateur JWT non trouvée'],
  ['ERROR.JWT_USER_CLAIM_INVALID_CONVERSION', 'Conversion invalide de la revendication utilisateur JWT'],
  ['ERROR.FORGOT_PASSWORD_REQUEST_TOO_SOON', 'Demande de mot de passe oublié trop tôt'],
  ['ERROR.RESTORE_PASSWORD_PROCESSING_ISSUE', 'Problème de traitement de la restauration du mot de passe'],
  ['ERROR.VERSION_NOT_SPECIFIED', 'Version non spécifiée'],
  ['ERROR.VERSION_NOT_SUPPORTED', 'Version non supportée'],
  ['ERROR.UPDATE_ONLY_OWN_SETTINGS', 'Mettre à jour uniquement ses propres paramètres'],
  ['ERROR.INVALID_URL', 'URL invalide'],
  ['ERROR.URL_NOT_HTTPS', 'URL non HTTPS'],
  ['ERROR.UNKNOWN_URL_TYPE', 'Type d\'URL inconnu'],
  ['ENTITY.STATUS.NEW', 'Nouveau'],
  ['ENTITY.STATUS.ACTIVE', 'Actif'],
  ['ENTITY.STATUS.INACTIVE', 'Inactif'],
  ['ENTITY.STATUS.BLOCKED', 'Bloqué'],
  ['ENTITY.STATUS.DELETED', 'Supprimé'],
  ['ENTITY.STATUS.PENDING', 'En attente'],
  ['ENTITY.STATUS.APPROVED', 'Approuvé'],
  ['ENTITY.STATUS.REJECTED', 'Rejeté'],
  ['ENTITY.STATUS.COMPLETED', 'Terminé'],
  ['ENTITY.STATUS.CANCELLED', 'Annulé'],
  ['ENTITY.STATUS.ARCHIVED', 'Archivé'],
  ['MESSAGES.CHANGES_SUCCESSFULLY_SAVED', 'Modifications enregistrées avec succès'],
  ['DATES.JANUARY_SHORT', 'Jan'],
  ['DATES.FEBRUARY_SHORT', 'Fév'],
  ['DATES.MARCH_SHORT', 'Mar'],
  ['DATES.APRIL_SHORT', 'Avr'],
  ['DATES.MAY_SHORT', 'Mai'],
  ['DATES.JUNE_SHORT', 'Juin'],
  ['DATES.JULY_SHORT', 'Juil'],
  ['DATES.AUGUST_SHORT', 'Août'],
  ['DATES.SEPTEMBER_SHORT', 'Sept'],
  ['DATES.OCTOBER_SHORT', 'Oct'],
  ['DATES.NOVEMBER_SHORT', 'Nov'],
  ['DATES.DECEMBER_SHORT', 'Déc'],
  ['DATES.MONDAY_SHORT', 'Lun'],
  ['DATES.TUESDAY_SHORT', 'Mar'],
  ['DATES.WEDNESDAY_SHORT', 'Mer'],
  ['DATES.THURSDAY_SHORT', 'Jeu'],
  ['DATES.FRIDAY_SHORT', 'Ven'],
  ['DATES.SATURDAY_SHORT', 'Sam'],
  ['DATES.SUNDAY_SHORT', 'Dim'],
  ['INPUT.TOO_MANY_ITEMS_START_TYPING', 'Trop d\'éléments, commencez à taper...'],
  ['ERROR.FIELD_REQUIRED', 'Le champ est requis'],
  ['ERROR.CHECK_CHECKBOX', 'Cocher la case'],
  ['ERROR.INVALID_EMAIL', 'Email invalide'],
  ['JOB_SOURCE.JOB_BOARD', 'Tableau d\'emplois'],
  ['JOB_SOURCE.COMPANY_WEBSITE', 'Site web de l\'entreprise'],
  ['JOB_SOURCE.RECOMMENDATION', 'Recommandation'],
  ['JOB_SOURCE.SOCIAL_MEDIA', 'Réseaux sociaux'],
  ['JOB_SOURCE.OTHER', 'Autre'],
  ['ROLE.ROLE', 'Rôle'],
  ['ROLE.USER', 'Utilisateur'],
  ['ROLE.TECHNICAL_SUPPORT', 'Support technique'],
  ['ROLE.ADMIN', 'Administrateur'],
  ['ROLE.SUPER_ADMIN', 'Super administrateur'],
  ['COMMON.JOB_TITLE', 'Titre du poste'],
  ['COMMON.SOURCE', 'Source'],
  ['COMMON.POSTED_DATE', 'Date de publication'],
  ['COMMON.DEADLINE', 'Date limite'],
  ['COMMON.CONTACT_EMAIL', 'Email de contact'],
  ['APPLICATION.APPLICATION_LINK', 'Lien de candidature'],
  ['COMMON.NOTES', 'Notes'],
  ['SKILL_LEVEL.SKILL_LEVEL', 'Niveau de compétence'],
  ['SKILL_LEVEL.BEGINNER', 'Débutant'],
  ['SKILL_LEVEL.BASIC', 'Basique'],
  ['SKILL_LEVEL.INTERMEDIATE', 'Intermédiaire'],
  ['SKILL_LEVEL.ADVANCED', 'Avancé'],
  ['SKILL_LEVEL.EXPERT', 'Expert'],
  ['SKILL_LEVEL.MASTER', 'Maître'],
  ['SKILL_LEVEL.WORLD_CLASS', 'De classe mondiale'],
  ['PROFILE.SHOW_CURRENT_POSITION', 'Afficher le poste actuel'],
  ['PROFILE.SHOW_HIGHEST_EDUCATION', 'Afficher la formation la plus élevée'],
]);
