// Auto-generated file from a7-localizations_it.csv

export const localization_it: Map<string, string> = new Map<string, string>([
  ['AUTH.GREETINGS', 'Saluti amici, Honkler!'],
  ['AUTH.SIGN_IN.JOKE', 'Forse abbiamo bisogno di tornare a'],
  ['COMMON.LOGIN_OR_EMAIL', 'Accesso o e-mail'],
  ['COMMON.PASSWORD', 'Password di accesso'],
  ['COMMON.CONFIRM_PASSWORD', 'Password di accesso'],
  ['COMMON.REMEMBER_ME', 'Ricordati di me'],
  ['COMMON.FORGOT', 'Dimenticato'],
  ['COMMON.SIGN_IN', 'Accedi'],
  ['COMMON.SIGN_UP', 'Iscriviti'],
  ['AUTH.NO_ACCOUNT.SIGN_UP', 'Non hai un account? Iscriviti'],
  ['AUTH.HAS_ACCOUNT.SIGN_IN', 'Hai già un account? Accedi'],
  ['COMMON.LOGIN', 'Accesso'],
  ['COMMON.EMAIL', 'Email'],
  ['COMMON.CONFIRM_EMAIL', 'Confermare l\'e-mail'],
  ['COMMON.PROCEED', 'Procedere'],
  ['COMMON.NO_COMPLAINTS', 'Nessun reclamo'],
  ['COMMON.WE_ARE_HONKING', 'Suoniamo il clacson dal 2024!'],
  ['COMMON.DO_NOT_STORE_SENS_DATA', 'NON MEMORIZZARE DATI SENSIBILI QUI!'],
  ['COMMON.LIGHT_THEME', 'Tema chiaro'],
  ['COMMON.DARK_THEME', 'Tema scuro'],
  ['ERROR.PASSWORDS_DO_NOT_MATCH', 'Le password non corrispondono'],
  ['ERROR.EMAILS_DO_NOT_MATCH', 'Le e-mail non corrispondono'],
  ['ERROR.FIELD_REQUIRED', 'Il campo è obbligatorio!'],
  ['ERROR.CHECK_CHECKBOX', 'Selezionare la casella!'],
  ['ERROR.INVALID_EMAIL', 'Formato email non valido!'],
  ['MENU.HOME', 'La casa'],
  ['MENU.JOBS', 'Lavoro'],
  ['MENU.COMPANIES', 'Aziende'],
  ['MENU.KARMA', 'Karma'],
  ['COMMON.WELCOME_BACK', 'Bentornato'],
  ['MENU.ACTIVE_APPLICATIONS', 'Applicazioni attive'],
  ['MENU.TODOS', 'TODOs'],
  ['MENU.RESPONSE_RATE', 'Tasso di risposta'],
  ['MENU.UPCOMING_INTERVIEWS', 'Prossimi colloqui'],
  ['COMMON.NEW_APPLICATION', 'Nuove candidature'],
  ['STATS.JOB_APPLICATIONS_TREND', 'Tendenza delle domande di lavoro'],
  ['STATS.TOP_COMPANIES', 'Aziende top (candidature)'],
  ['STATS.NEW_JOB_LISTINGS_PER_DAY', 'Nuovi annunci di lavoro al giorno'],
  ['STATS.APPLICATION_STATUS_DISTRIBUTION', 'Distribuzione dello stato delle candidature'],
  ['STATUS.APPLIED', 'Richiesta'],
  ['STATUS.REJECTED', 'Rifiutato'],
  ['STATUS.OFFER', 'Offerta'],
  ['STATUS.INTERVIEW', 'Colloquio'],
  ['STATUS.IN_REVIEW', 'In revisione'],
  ['COMMON.CREATE', 'Creare'],
  ['COMMON.EDIT', 'Modifica'],
  ['COMMON.APPLICATION_LINK', 'Link alla candidatura'],
  ['COMMON.JOB_TITLE', 'Titolo del lavoro'],
  ['COMMON.COMPANY', 'Azienda'],
  ['COMMON.LOCATION', 'Sede di lavoro'],
  ['COMMON.EXPERIENCE_LEVEL', 'Livello di esperienza'],
  ['COMMON.JOB_TYPE', 'Tipo di lavoro'],
  ['COMMON.SOURCE', 'Fonte'],
  ['COMMON.SALARY_RANGE', 'Range di retribuzione'],
  ['COMMON.FROM', 'Da'],
  ['COMMON.TO', 'A'],
  ['COMMON.CURRENCY', 'Valuta'],
  ['COMMON.POSTED_DATE', 'Data di pubblicazione'],
  ['COMMON.APPLICATION_DEADLINE', 'Scadenza di candidatura'],
  ['COMMON.Contact_EMAIL', 'Email di contatto'],
  ['COMMON.DESCRIPTION', 'Descrizione'],
  ['COMMON.NOTES', 'Note'],
  ['COMMON.CANCEL', 'Annullamento'],
  ['COMMON.UPDATE', 'Aggiornare'],
  ['COMMON.EDIT_PROFILE', 'Modifica il profilo'],
  ['COMMON.EDIT_SKILLS', 'Modifica le competenze'],
  ['COMMON.ADD_EXPERIENCE', 'Aggiungi esperienza'],
  ['COMMON.SKILLS', 'Competenze'],
  ['COMMON.EXPERIENCE', 'Esperienza'],
  ['COMMON.EDUCATION', 'Formazione'],
  ['COMMON.CERTIFICATIONS', 'Certificazioni'],
  ['ROLE.USER', 'Utente'],
  ['ROLE.TECHNICAL_SUPPORT', 'Supporto tecnico'],
  ['ROLE.ADMIN', 'Amministratore'],
  ['ROLE.SUPER_ADMIN', 'Super Admin'],
  ['JOB_TYPE.FULL_TIME', 'A tempo pieno'],
  ['JOB_TYPE.PART_TIME', 'A tempo parziale'],
  ['JOB_TYPE.CONTRACT', 'Contratto'],
  ['JOB_TYPE.TEMPORARY', 'Temporaneo'],
  ['JOB_TYPE.INTERN', 'Stagista'],
  ['JOB_TYPE.VOLUNTEER', 'Volontario'],
  ['JOB_TYPE.FREELANCE', 'Freelance'],
  ['JOB_TYPE.STARTUP', 'Avviamento'],
  ['JOB_TYPE.OTHER', 'Altro'],
  ['JOB_SOURCE.JOB_BOARD', 'Ufficio di collocamento'],
  ['JOB_SOURCE.COMPANY_WEBSITE', 'Sito web aziendale'],
  ['JOB_SOURCE.RECOMMENDATION', 'Raccomandazione'],
  ['JOB_SOURCE.OTHER', 'Altro'],
  ['EXPERIENCE_LEVEL.INTERNSHIP', 'Stage'],
  ['EXPERIENCE_LEVEL.ENTRY_LEVEL', 'Livello di ingresso'],
  ['EXPERIENCE_LEVEL.JUNIOR', 'Junior'],
  ['EXPERIENCE_LEVEL.MID_LEVEL', 'Livello medio'],
  ['EXPERIENCE_LEVEL.SENIOR', 'Senior'],
  ['EXPERIENCE_LEVEL.EXECUTIVE', 'Dirigente'],
  ['COMMON.APPLICATIONS', 'Applicazioni'],
  ['DATES.JANUARY_SHORT', 'Gen'],
  ['DATES.FEBRUARY_SHORT', 'Feb'],
  ['DATES.MARCH_SHORT', 'Mar'],
  ['DATES.APRIL_SHORT', 'Apr'],
  ['DATES.MAY_SHORT', 'Mag'],
  ['DATES.JUNE_SHORT', 'Giu'],
  ['DATES.JULY_SHORT', 'Lug'],
  ['DATES.AUGUST_SHORT', 'Ago'],
  ['DATES.SEPTEMBER_SHORT', 'Set'],
  ['DATES.OCTOBER_SHORT', 'Ott'],
  ['DATES.NOVEMBER_SHORT', 'Nov'],
  ['DATES.DECEMBER_SHORT', 'Dic'],
  ['DATES.MONDAY_SHORT', 'Lun'],
  ['DATES.TUESDAY_SHORT', 'Mar'],
  ['DATES.WEDNESDAY_SHORT', 'Mer'],
  ['DATES.THURSDAY_SHORT', 'Gio'],
  ['DATES.FRIDAY_SHORT', 'Ven'],
  ['DATES.SATURDAY_SHORT', 'Sab'],
  ['DATES.SUNDAY_SHORT', 'Dom'],
  ['ERROR.USER_NOT_FOUND', 'Utente non trovato'],
  ['COMMON.OK', 'Ok'],
  ['COMMON.USER_PREFERENCES', 'Preferenze dell\'utente'],
  ['ERROR.UPDATE_ONLY_OWN_SETTINGS', 'L\'utente può aggiornare solo le proprie impostazioni'],
  ['COMMON.FIRST_NAME', 'Nome e cognome'],
  ['COMMON.LAST_NAME', 'Cognome'],
  ['COMMON.LANGUAGE', 'Lingua'],
  ['COMMON.TIME_ZONE', 'Fuso orario'],
  ['COMMON.COUNTRY', 'Paese'],
  ['COMMON.APPLICATION_AI_TEXTAREA', 'Applicazione AI textarea'],
  ['MESSAGES.CHANGES_SUCCESSFULLY_SAVED', 'Le modifiche sono state salvate con successo'],
  ['INPUT.TO_MANY_ITEMS.START_TYPING', 'Troppi elementi. Iniziare a digitare'],
  ['ERROR.INVALID_URL', 'Formato URL non valido'],
  ['ERROR.URL_NOT_HTTPS', 'L\'URL non utilizza HTTPS'],
  ['ERROR.UNKNOWN_URL_TYPE', 'L\'URL è sicuro ma non corrisponde a un modello di nome utente noto'],
  ['COMMON.PHONE', 'Telefono'],
  ['SKILL_LEVEL.BEGINNER', 'Principiante'],
  ['SKILL_LEVEL.BASIC', 'Base'],
  ['SKILL_LEVEL.INTERMEDIATE', 'Intermedio'],
  ['SKILL_LEVEL.ADVANCED', 'Avanzato'],
  ['SKILL_LEVEL.EXPERT', 'Esperto'],
  ['SKILL_LEVEL.MASTER', 'Maestro'],
  ['SKILL_LEVEL.WORLD_CLASS', 'Classe mondiale'],
  ['WORK_ARRANGEMENT.ON_SITE', 'In loco'],
  ['WORK_ARRANGEMENT.REMOTE', 'A distanza'],
  ['WORK_ARRANGEMENT.HYBRID', 'Ibrido'],
  ['WORK_ARRANGEMENT.FLEXIBLE', 'Flessibile'],
  ['WORK_ARRANGEMENT.TRAVEL_REQUIRED', 'Viaggi richiesti'],
  ['WORK_ARRANGEMENT.SHIFT_BASED', 'A turni'],
  ['COMMON.ADD', 'Aggiungi'],
  ['COMMON.REMOVE', 'Rimuovere'],
  ['COMMON.ALREADY_EXISTS', 'Esiste già'],
  ['COMMON.LANGUAGE_LEVEL', 'Livello di lingua'],
  ['COMMON.LANGUAGES', 'Lingue'],
  ['COMMON.EDIT_LANGUAGES', 'Modifica lingue'],
  ['ERROR.COMMON_ERROR', 'Si è verificato un errore inatteso.'],
  ['ERROR.NOT_FOUND', 'Non trovato'],
  ['ERROR.ENTITY_NOT_FOUND', 'Entità non trovata'],
  ['ERROR.ENTITY_WITH_ID_NOT_FOUND', 'Entità con questo ID non trovata'],
  ['ERROR.ENTITY_WITH_EMAIL_ALREADY_EXISTS', 'L\'entità con questa e-mail esiste già'],
  ['ERROR.ENTITY_WITH_LOGIN_ALREADY_EXISTS', 'L\'entità con questo login esiste già'],
  ['ERROR.VALIDATION_ERROR', 'Errore di convalida'],
  ['ERROR.ENTITY_ALREADY_EXISTS', 'Entità già esistente'],
  ['ERROR.INTERNAL_SERVER_ERROR', 'Errore interno del server'],
  ['ERROR.BLOCKED', 'Bloccato'],
  ['ERROR.RESOURCE_NOT_FOUND', 'Risorsa non trovata'],
  ['ERROR.ENTITY_BLOCKED', 'L\'entità è bloccata'],
  ['ERROR.ENTITY_PESSIMISTIC_LOCKED', 'L\'entità è pessimisticamente bloccata'],
  ['ERROR.WRONG_AUTH', 'Credenziali errate'],
  ['ERROR.FORBIDDEN', 'Accesso negato'],
  ['ERROR.USER_BLOCKED', 'L\'utente è bloccato'],
  ['ERROR.POTENTIAL_HARMFUL_CONTENT', 'Rilevato contenuto potenzialmente dannoso'],
  ['ERROR.JWT_MIN_LENGTH', 'Il token JWT è troppo corto'],
  ['ERROR.JWT_INVALID_FORMAT', 'Formato JWT non valido'],
  ['ERROR.JWT_USER_CLAIM_NOT_FOUND', 'Richiesta dell\'utente non trovata nel JWT'],
  ['ERROR.JWT_USER_CLAIM_INVALID_CONVERSION', 'Impossibile convertire la richiesta dell\'utente in JWT'],
  ['ERROR.FORGOT_PASSWORD_REQUEST_TOO_SOON', 'Password dimenticata richiesta troppo presto'],
  ['ERROR.RESTORE_PASSWORD_PROCESSING_ISSUE', 'Si è verificato un problema durante il ripristino della password'],
  ['ERROR.VERSION_NOT_SPECIFIED', 'Versione non specificata'],
  ['ERROR.USER_PROJECT_LIMIT_EXCEEDED', 'L\'utente ha superato il limite del progetto'],
  ['ERROR.ROLE_NOT_SUPPORTED', 'Questo ruolo non è supportato'],
  ['STATUS.NEW', 'Nuovo'],
  ['STATUS.ACTIVE', 'Attivo'],
  ['STATUS.INACTIVE', 'Inattivo'],
  ['STATUS.BLOCKED', 'Bloccato'],
  ['STATUS.DELETED', 'Eliminato'],
  ['STATUS.PENDING', 'In attesa'],
  ['STATUS.APPROVED', 'Approvato'],
  ['STATUS.COMPLETED', 'Completato'],
  ['STATUS.CANCELLED', 'Annullato'],
]);
