// Auto-generated file from a1-localizations_en.csv

export const localization_en: Map<string, string> = new Map<string, string>([
  ['AUTH.GREETINGS', 'Greetings fellow, Honkler!'],
  ['AUTH.SIGN_IN.JOKE', 'Maybe we need back to'],
  ['COMMON.AUTH.LOGIN_OR_EMAIL', 'Login or Email'],
  ['COMMON.AUTH.PASSWORD', 'Password'],
  ['COMMON.AUTH.CONFIRM_PASSWORD', 'Password'],
  ['COMMON.AUTH.REMEMBER_ME', 'Remember me'],
  ['COMMON.AUTH.FORGOT', 'Forgot'],
  ['COMMON.AUTH.SIGN_IN', 'Sign In'],
  ['COMMON.AUTH.SIGN_UP', 'Sign Up'],
  ['AUTH.NO_ACCOUNT.SIGN_UP', 'Don\'t have an account? Sign Up'],
  ['AUTH.HAS_ACCOUNT.SIGN_IN', 'Already have an account? Sign In'],
  ['COMMON.AUTH.LOGIN', 'Login'],
  ['COMMON.AUTH.EMAIL', 'Email'],
  ['COMMON.AUTH.CONFIRM_EMAIL', 'Confirm email'],
  ['COMMON.AUTH.PROCEED', 'Proceed'],
  ['COMMON.SYSTEM.NO_COMPLAINTS', 'No complaints'],
  ['COMMON.SYSTEM.WE_ARE_HONKING', 'We are honking since 2024!'],
  ['COMMON.SYSTEM.DO_NOT_STORE_SENS_DATA', 'DO NOT STORE ANY SENSITIVE DATA HERE!'],
  ['COMMON.UI.LIGHT_THEME', 'Light theme'],
  ['COMMON.UI.DARK_THEME', 'Dark theme'],
  ['ERROR.VALIDATION.PASSWORDS_DO_NOT_MATCH', 'Passwords do not match'],
  ['ERROR.VALIDATION.EMAILS_DO_NOT_MATCH', 'Emails do not match'],
  ['ERROR.VALIDATION.FIELD_REQUIRED', 'The field is required!'],
  ['ERROR.VALIDATION.CHECK_CHECKBOX', 'Please check the box!'],
  ['ERROR.VALIDATION.INVALID_EMAIL', 'Invalid email format!'],
  ['MENU.HOME', 'Home'],
  ['MENU.JOBS', 'Jobs'],
  ['MENU.COMPANIES', 'Companies'],
  ['MENU.KARMA', 'Karma'],
  ['COMMON.UI.WELCOME_BACK', 'Welcome back'],
  ['MENU.ACTIVE_APPLICATIONS', 'Active Applications'],
  ['MENU.TODOS', 'TODOs'],
  ['MENU.RESPONSE_RATE', 'Response Rate'],
  ['MENU.UPCOMING_INTERVIEWS', 'Upcoming Interviews'],
  ['COMMON.UI.NEW_APPLICATION', 'New Application'],
  ['STATS.JOB_APPLICATIONS_TREND', 'Job Applications Trend'],
  ['STATS.TOP_COMPANIES', 'Top Companies (Applications)'],
  ['STATS.NEW_JOB_LISTINGS_PER_DAY', 'New Job Listings per Day'],
  ['STATS.APPLICATION_STATUS_DISTRIBUTION', 'Application Status Distribution'],
  ['STATUS.APPLIED', 'Applied'],
  ['STATUS.REJECTED', 'Rejected'],
  ['STATUS.OFFER', 'Offer'],
  ['STATUS.INTERVIEW', 'Interview'],
  ['STATUS.IN_REVIEW', 'In Review'],
  ['COMMON.UI.CREATE', 'Create'],
  ['COMMON.UI.EDIT', 'Edit'],
  ['COMMON.JOB.APPLICATION_LINK', 'Application Link'],
  ['COMMON.JOB.TITLE', 'Job Title'],
  ['COMMON.JOB.COMPANY', 'Company'],
  ['COMMON.JOB.LOCATION', 'Location'],
  ['COMMON.JOB.EXPERIENCE_LEVEL', 'Experience Level'],
  ['COMMON.JOB.TYPE', 'Job Type'],
  ['COMMON.JOB.SOURCE', 'Source'],
  ['COMMON.JOB.SALARY_RANGE', 'Salary range'],
  ['COMMON.FORM.FROM', 'From'],
  ['COMMON.FORM.TO', 'To'],
  ['COMMON.FORM.CURRENCY', 'Currency'],
  ['COMMON.JOB.POSTED_DATE', 'Posted Date'],
  ['COMMON.JOB.APPLICATION_DEADLINE', 'Application Deadline'],
  ['COMMON.JOB.CONTACT_EMAIL', 'Contact Email'],
  ['COMMON.JOB.DESCRIPTION', 'Description'],
  ['COMMON.JOB.NOTES', 'Notes'],
  ['COMMON.UI.CANCEL', 'Cancel'],
  ['COMMON.UI.UPDATE', 'Update'],
  ['COMMON.USER.EDIT_PROFILE', 'Edit profile'],
  ['COMMON.USER.EDIT_SKILLS', 'Edit skills'],
  ['COMMON.USER.ADD_EXPERIENCE', 'Add experience'],
  ['COMMON.SKILLS.SKILLS', 'Skills'],
  ['COMMON.SKILLS.EXPERIENCE', 'Experience'],
  ['COMMON.SKILLS.EDUCATION', 'Education'],
  ['COMMON.SKILLS.CERTIFICATIONS', 'Certifications'],
  ['ROLE.USER', 'User'],
  ['ROLE.TECHNICAL_SUPPORT', 'Technical Support'],
  ['ROLE.ADMIN', 'Admin'],
  ['ROLE.SUPER_ADMIN', 'Super Admin'],
  ['JOB_TYPE.FULL_TIME', 'Full-time'],
  ['JOB_TYPE.PART_TIME', 'Part-time'],
  ['JOB_TYPE.CONTRACT', 'Contract'],
  ['JOB_TYPE.TEMPORARY', 'Temporary'],
  ['JOB_TYPE.INTERN', 'Intern'],
  ['JOB_TYPE.VOLUNTEER', 'Volunteer'],
  ['JOB_TYPE.FREELANCE', 'Freelance'],
  ['JOB_TYPE.STARTUP', 'Startup'],
  ['JOB_TYPE.OTHER', 'Other'],
  ['JOB_SOURCE.JOB_BOARD', 'Job Board'],
  ['JOB_SOURCE.COMPANY_WEBSITE', 'Company Website'],
  ['JOB_SOURCE.RECOMMENDATION', 'Recommendation'],
  ['JOB_SOURCE.OTHER', 'Other'],
  ['EXPERIENCE_LEVEL.INTERNSHIP', 'Internship'],
  ['EXPERIENCE_LEVEL.ENTRY_LEVEL', 'Entry Level'],
  ['EXPERIENCE_LEVEL.JUNIOR', 'Junior'],
  ['EXPERIENCE_LEVEL.MID_LEVEL', 'Mid Level'],
  ['EXPERIENCE_LEVEL.SENIOR', 'Senior'],
  ['EXPERIENCE_LEVEL.EXECUTIVE', 'Executive'],
  ['COMMON.JOB.APPLICATIONS', 'Applications'],
  ['DATES.JANUARY_SHORT', 'Jan'],
  ['DATES.FEBRUARY_SHORT', 'Feb'],
  ['DATES.MARCH_SHORT', 'Mar'],
  ['DATES.APRIL_SHORT', 'Apr'],
  ['DATES.MAY_SHORT', 'May'],
  ['DATES.JUNE_SHORT', 'Jun'],
  ['DATES.JULY_SHORT', 'Jul'],
  ['DATES.AUGUST_SHORT', 'Aug'],
  ['DATES.SEPTEMBER_SHORT', 'Sep'],
  ['DATES.OCTOBER_SHORT', 'Oct'],
  ['DATES.NOVEMBER_SHORT', 'Nov'],
  ['DATES.DECEMBER_SHORT', 'Dec'],
  ['DATES.MONDAY_SHORT', 'Mon'],
  ['DATES.TUESDAY_SHORT', 'Tue'],
  ['DATES.WEDNESDAY_SHORT', 'Wed'],
  ['DATES.THURSDAY_SHORT', 'Thu'],
  ['DATES.FRIDAY_SHORT', 'Fri'],
  ['DATES.SATURDAY_SHORT', 'Sat'],
  ['DATES.SUNDAY_SHORT', 'Sun'],
  ['ERROR.ENTITY.USER_NOT_FOUND', 'User not found'],
  ['COMMON.UI.OK', 'Ok'],
  ['COMMON.USER.PREFERENCES', 'User preferences'],
  ['ERROR.ENTITY.UPDATE_ONLY_OWN_SETTINGS', 'User can update only own settings'],
  ['COMMON.USER.FIRST_NAME', 'First Name'],
  ['COMMON.USER.LAST_NAME', 'Last Name'],
  ['COMMON.USER.LANGUAGE', 'Language'],
  ['COMMON.USER.TIME_ZONE', 'Time Zone'],
  ['COMMON.USER.COUNTRY', 'Country'],
  ['COMMON.FORM.AI_TEXTAREA', 'Application AI textarea'],
  ['MESSAGES.CHANGES_SUCCESSFULLY_SAVED', 'Changes have been saved successfully'],
  ['COMMON.FORM.TOO_MANY_ITEMS', 'Too many items. Please start typing'],
  ['ERROR.VALIDATION.INVALID_URL', 'Invalid URL format'],
  ['ERROR.VALIDATION.URL_NOT_HTTPS', 'URL is not using HTTPS'],
  ['ERROR.VALIDATION.UNKNOWN_URL_TYPE', 'URL is safe but does not match a known username pattern'],
  ['COMMON.USER.PHONE', 'Phone'],
  ['SKILL_LEVEL.BEGINNER', 'Beginner'],
  ['SKILL_LEVEL.BASIC', 'Basic'],
  ['SKILL_LEVEL.INTERMEDIATE', 'Intermediate'],
  ['SKILL_LEVEL.ADVANCED', 'Advanced'],
  ['SKILL_LEVEL.EXPERT', 'Expert'],
  ['SKILL_LEVEL.MASTER', 'Master'],
  ['SKILL_LEVEL.WORLD_CLASS', 'World-Class'],
  ['WORK_ARRANGEMENT.ON_SITE', 'On-site'],
  ['WORK_ARRANGEMENT.REMOTE', 'Remote'],
  ['WORK_ARRANGEMENT.HYBRID', 'Hybrid'],
  ['WORK_ARRANGEMENT.FLEXIBLE', 'Flexible'],
  ['WORK_ARRANGEMENT.TRAVEL_REQUIRED', 'Travel Required'],
  ['WORK_ARRANGEMENT.SHIFT_BASED', 'Shift-based'],
  ['COMMON.UI.ADD', 'Add'],
  ['COMMON.UI.REMOVE', 'Remove'],
  ['COMMON.FORM.ALREADY_EXISTS', 'Already exists'],
  ['COMMON.SKILLS.LANGUAGE_LEVEL', 'Language Level'],
  ['COMMON.SKILLS.LANGUAGES', 'Languages'],
  ['COMMON.SKILLS.EDIT_LANGUAGES', 'Edit languages'],
  ['ERROR.SYSTEM.COMMON_ERROR', 'Unexpected error occurred.'],
  ['ERROR.ENTITY.NOT_FOUND', 'Not found'],
  ['ERROR.ENTITY.ENTITY_NOT_FOUND', 'Entity not found'],
  ['ERROR.ENTITY.ENTITY_WITH_ID_NOT_FOUND', 'Entity with this ID not found'],
  ['ERROR.ENTITY.ENTITY_WITH_EMAIL_ALREADY_EXISTS', 'Entity with this email already exists'],
  ['ERROR.ENTITY.ENTITY_WITH_LOGIN_ALREADY_EXISTS', 'Entity with this login already exists'],
  ['ERROR.VALIDATION.VALIDATION_ERROR', 'Validation error'],
  ['ERROR.ENTITY.ENTITY_ALREADY_EXISTS', 'Entity already exists'],
  ['ERROR.SYSTEM.INTERNAL_SERVER_ERROR', 'Internal server error'],
  ['ERROR.ENTITY.BLOCKED', 'Blocked'],
  ['ERROR.ENTITY.RESOURCE_NOT_FOUND', 'Resource not found'],
  ['ERROR.ENTITY.ENTITY_BLOCKED', 'Entity is blocked'],
  ['ERROR.ENTITY.ENTITY_PESSIMISTIC_LOCKED', 'Entity is pessimistically locked'],
  ['ERROR.AUTH.WRONG_CREDENTIALS', 'Wrong credentials'],
  ['ERROR.AUTH.FORBIDDEN', 'Access denied'],
  ['ERROR.ENTITY.USER_BLOCKED', 'User is blocked'],
  ['ERROR.SYSTEM.POTENTIAL_HARMFUL_CONTENT', 'Potential harmful content detected'],
  ['ERROR.AUTH.JWT_MIN_LENGTH', 'JWT token is too short'],
  ['ERROR.AUTH.JWT_INVALID_FORMAT', 'Invalid JWT format'],
  ['ERROR.AUTH.JWT_USER_CLAIM_NOT_FOUND', 'User claim not found in JWT'],
  ['ERROR.AUTH.JWT_USER_CLAIM_INVALID_CONVERSION', 'Cannot convert user claim in JWT'],
  ['ERROR.AUTH.FORGOT_PASSWORD_REQUEST_TOO_SOON', 'Forgot password requested too soon'],
  ['ERROR.AUTH.RESTORE_PASSWORD_PROCESSING_ISSUE', 'An issue occurred during password restoration'],
  ['ERROR.SYSTEM.VERSION_NOT_SPECIFIED', 'Version not specified'],
  ['ERROR.ENTITY.USER_PROJECT_LIMIT_EXCEEDED', 'User has exceeded project limit'],
  ['ERROR.ENTITY.ROLE_NOT_SUPPORTED', 'This role is not supported'],
  ['STATUS.NEW', 'New'],
  ['STATUS.ACTIVE', 'Active'],
  ['STATUS.INACTIVE', 'Inactive'],
  ['STATUS.BLOCKED', 'Blocked'],
  ['STATUS.DELETED', 'Deleted'],
  ['STATUS.PENDING', 'Pending'],
  ['STATUS.APPROVED', 'Approved'],
  ['STATUS.COMPLETED', 'Completed'],
  ['STATUS.CANCELLED', 'Cancelled'],
  ['KARMA.TITLE', 'Your Karma'],
  ['KARMA.POINTS', 'karma points'],
  ['KARMA.STATS.ACTIVITY', 'Activity'],
  ['KARMA.STATS.ACTIVITY_DESC', 'Community participation level'],
  ['KARMA.STATS.HELP', 'Help'],
  ['KARMA.STATS.HELP_DESC', 'Helped other users'],
  ['KARMA.STATS.ACHIEVEMENTS', 'Achievements'],
  ['KARMA.STATS.ACHIEVEMENTS_DESC', 'Received awards'],
  ['KARMA.HISTORY.TITLE', 'Karma History'],
  ['KARMA.HISTORY.DATE', 'Date'],
  ['KARMA.HISTORY.EVENT', 'Event'],
  ['KARMA.HISTORY.CHANGE', 'Change'],
  ['KARMA.HISTORY.EVENTS.TASK_HELP', 'Helped solve a task'],
  ['KARMA.HISTORY.EVENTS.DISCUSSION', 'Active participation in discussion'],
  ['KARMA.HISTORY.EVENTS.MATERIAL', 'Published useful material'],
]);
