// Auto-generated file from a3-localizations_fr.csv

export const localization_fr: Map<string, string> = new Map<string, string>([
  [`AUTH.GREETINGS`, `Bonjour à tous, Honkler !`],
  [`AUTH.SIGN_IN.JOKE`, `Peut-être devrions-nous revenir à`],
  [`COMMON.LOGIN_OR_EMAIL`, `Login ou Email`],
  [`COMMON.PASSWORD`, `Mot de passe`],
  [`COMMON.CONFIRM_PASSWORD`, `Mot de passe`],
  [`COMMON.REMEMBER_ME`, `Se souvenir de moi`],
  [`COMMON.FORGOT`, `Oublié`],
  [`COMMON.SIGN_IN`, `Se connecter`],
  [`COMMON.SIGN_UP`, `S'inscrire`],
  [`AUTH.NO_ACCOUNT.SIGN_UP`, `Vous n''avez pas de compte ? S'inscrire`],
  [`AUTH.HAS_ACCOUNT.SIGN_IN`, `Vous avez déjà un compte ? S'inscrire`],
  [`COMMON.LOGIN`, `Se connecter`],
  [`COMMON.EMAIL`, `Courriel`],
  [`COMMON.CONFIRM_EMAIL`, `Confirmer l'email`],
  [`COMMON.PROCEED`, `Procéder`],
  [`COMMON.FIRST_NAME`, `Prénom`],
  [`COMMON.LAST_NAME`, `Nom de famille`],
  [`COMMON.NO_COMPLAINTS`, `Pas de plaintes`],
  [`COMMON.WE_ARE_HONKING`, `Nous klaxonnons depuis 2024 !`],
  [`COMMON.DO_NOT_STORE_SENS_DATA`, `NE STOCKEZ PAS DE DONNÉES SENSIBLES ICI !`],
  [`COMMON.LIGHT_THEME`, `Thème clair`],
  [`COMMON.DARK_THEME`, `Thème sombre`],
  [`ERROR.PASSWORDS_DO_NOT_MATCH`, `Les mots de passe ne correspondent pas`],
  [`ERROR.EMAILS_DO_NOT_MATCH`, `Les courriels ne correspondent pas`],
  [`ERROR.FIELD_REQUIRED`, `Le champ est obligatoire !`],
  [`ERROR.CHECK_CHECKBOX`, `Veuillez cocher la case !`],
  [`ERROR.INVALID_EMAIL`, `Format d'e-mail non valide !`],
  [`MENU.HOME`, `Accueil`],
  [`MENU.JOBS`, `Emplois`],
  [`MENU.COMPANIES`, `Entreprises`],
  [`MENU.KARMA`, `Karma`],
  [`COMMON.WELCOME_BACK`, `Bienvenue`],
  [`MENU.ACTIVE_APPLICATIONS`, `Applications actives`],
  [`MENU.TODOS`, `TODOs`],
  [`MENU.RESPONSE_RATE`, `Taux de réponse`],
  [`MENU.UPCOMING_INTERVIEWS`, `Prochains entretiens`],
  [`COMMON.NEW_APPLICATION`, `Nouvelle candidature`],
  [`STATS.JOB_APPLICATIONS_TREND`, `Tendance des demandes d'emploi`],
  [`STATS.TOP_COMPANIES`, `Principales entreprises (candidatures)`],
  [`STATS.NEW_JOB_LISTINGS_PER_DAY`, `Nouvelles offres d'emploi par jour`],
  [`STATS.APPLICATION_STATUS_DISTRIBUTION`, `Répartition de l'état des candidatures`],
  [`STATUS.APPLIED`, `Candidature acceptée`],
  [`STATUS.REJECTED`, `Refusé`],
  [`STATUS.OFFER`, `Offre`],
  [`STATUS.INTERVIEW`, `Entretien`],
  [`STATUS.IN_REVIEW`, `En cours d'examen`],
  [`COMMON.CREATE`, `Créer`],
  [`COMMON.EDIT`, `Modifier`],
  [`COMMON.APPLICATION_LINK`, `Lien de candidature`],
  [`COMMON.JOB_TITLE`, `Titre du poste`],
  [`COMMON.COMPANY`, `Entreprise`],
  [`COMMON.LOCATION`, `Lieu de travail`],
  [`COMMON.EXPERIENCE_LEVEL`, `Niveau d'expérience`],
  [`COMMON.JOB_TYPE`, `Type d'emploi`],
  [`COMMON.SOURCE`, `Source d'information`],
  [`COMMON.SALARY_RANGE`, `Fourchette de salaire`],
  [`COMMON.FROM`, `A partir de`],
  [`COMMON.TO`, `jusqu'à`],
  [`COMMON.CURRENCY`, `Monnaie`],
  [`COMMON.POSTED_DATE`, `Date de publication`],
  [`COMMON.APPLICATION_DEADLINE`, `Date limite de candidature`],
  [`COMMON.Contact_EMAIL`, `Email de contact`],
  [`COMMON.DESCRIPTION`, `Description de la demande`],
  [`COMMON.NOTES`, `Notes (en anglais)`],
  [`COMMON.CANCEL`, `Annuler`],
  [`COMMON.UPDATE`, `Mise à jour`],
  [`COMMON.EDIT_PROFILE`, `Modifier le profil`],
  [`COMMON.EDIT_SKILLS`, `Modifier les compétences`],
  [`COMMON.ADD_EXPERIENCE`, `Ajouter une expérience`],
  [`COMMON.SKILLS`, `Compétences`],
  [`COMMON.EXPERIENCE`, `Expérience`],
  [`COMMON.EDUCATION`, `Formation`],
  [`COMMON.CERTIFICATIONS`, `Certifications`],
  [`ROLE.USER`, `Utilisateur`],
  [`ROLE.TECHNICAL_SUPPORT`, `Support technique`],
  [`ROLE.ADMIN`, `Administrateur`],
  [`ROLE.SUPER_ADMIN`, `Super Admin`],
  [`JOB_TYPE.FULL_TIME`, `Temps plein`],
  [`JOB_TYPE.PART_TIME`, `Temps partiel`],
  [`JOB_TYPE.CONTRACT`, `Contrat de travail`],
  [`JOB_TYPE.TEMPORARY`, `Temporaire`],
  [`JOB_TYPE.INTERN`, `Stagiaire`],
  [`JOB_TYPE.VOLUNTEER`, `Volontaire`],
  [`JOB_TYPE.FREELANCE`, `Freelance`],
  [`JOB_TYPE.STARTUP`, `Création d'entreprise`],
  [`JOB_TYPE.OTHER`, `Autre`],
  [`JOB_SOURCE.JOB_BOARD`, `Job Board`],
  [`JOB_SOURCE.COMPANY_WEBSITE`, `Site web de l'entreprise`],
  [`JOB_SOURCE.RECOMMENDATION`, `Recommandation`],
  [`JOB_SOURCE.OTHER`, `Autre`],
  [`EXPERIENCE_LEVEL.INTERNSHIP`, `Stage`],
  [`EXPERIENCE_LEVEL.ENTRY_LEVEL`, `Niveau d'entrée`],
  [`EXPERIENCE_LEVEL.JUNIOR`, `Débutant`],
  [`EXPERIENCE_LEVEL.MID_LEVEL`, `Niveau moyen`],
  [`EXPERIENCE_LEVEL.SENIOR`, `Senior`],
  [`EXPERIENCE_LEVEL.EXECUTIVE`, `Cadre`],
  [`COMMON.APPLICATIONS`, `Applications`],
  [`DATES.JANUARY_SHORT`, `Janv`],
  [`DATES.FEBRUARY_SHORT`, `Fév`],
  [`DATES.MARCH_SHORT`, `Mars`],
  [`DATES.APRIL_SHORT`, `Avr`],
  [`DATES.MAY_SHORT`, `Mai`],
  [`DATES.JUNE_SHORT`, `Juin`],
  [`DATES.JULY_SHORT`, `Juil`],
  [`DATES.AUGUST_SHORT`, `Août`],
  [`DATES.SEPTEMBER_SHORT`, `Sept`],
  [`DATES.OCTOBER_SHORT`, `Oct`],
  [`DATES.NOVEMBER_SHORT`, `Nov`],
  [`DATES.DECEMBER_SHORT`, `Déc`],
  [`DATES.MONDAY_SHORT`, `Lun`],
  [`DATES.TUESDAY_SHORT`, `Mar`],
  [`DATES.WEDNESDAY_SHORT`, `Mer`],
  [`DATES.THURSDAY_SHORT`, `Jeu`],
  [`DATES.FRIDAY_SHORT`, `Ven`],
  [`DATES.SATURDAY_SHORT`, `Sam`],
  [`DATES.SUNDAY_SHORT`, `Dim`],
  [`ERROR.USER_NOT_FOUND`, `Utilisateur non trouvé`],
  [`COMMON.OK`, `Ok`],
  [`COMMON.USER_PREFERENCES`, `Préférences de l'utilisateur`],
  [`ERROR.UPDATE_ONLY_OWN_SETTINGS`, `L'utilisateur ne peut mettre à jour que ses propres paramètres`],
  [`COMMON.FIRST_NAME`, `Prénom`],
  [`COMMON.LAST_NAME`, `Nom de famille`],
  [`COMMON.LANGUAGE`, `Langue`],
  [`COMMON.TIME_ZONE`, `Fuseau horaire`],
  [`COMMON.COUNTRY`, `Pays`],
  [`COMMON.APPLICATION_AI_TEXTAREA`, `Application AI textarea`],
  [`MESSAGES.CHANGES_SUCCESSFULLY_SAVED`, `Les modifications ont été enregistrées avec succès`],
  [`INPUT.TO_MANY_ITEMS.START_TYPING`, `Trop d'éléments. Veuillez commencer à taper`],
  [`ERROR.INVALID_URL`, `Format d'URL non valide`],
  [`ERROR.URL_NOT_HTTPS`, `L'URL n'utilise pas HTTPS`],
  [`ERROR.UNKNOWN_URL_TYPE`, `L'URL est sûre mais ne correspond pas à un modèle de nom d'utilisateur connu.`],
  [`COMMON.PHONE`, `Téléphone`],
  [`SKILL_LEVEL.BEGINNER`, `Débutant`],
  [`SKILL_LEVEL.BASIC`, `De base`],
  [`SKILL_LEVEL.INTERMEDIATE`, `Intermédiaire`],
  [`SKILL_LEVEL.ADVANCED`, `Avancé`],
  [`SKILL_LEVEL.EXPERT`, `Expert`],
  [`SKILL_LEVEL.MASTER`, `Maître`],
  [`SKILL_LEVEL.WORLD_CLASS`, `Niveau mondial`],
  [`WORK_ARRANGEMENT.ON_SITE`, `Sur place`],
  [`WORK_ARRANGEMENT.REMOTE`, `A distance`],
  [`WORK_ARRANGEMENT.HYBRID`, `Hybride`],
  [`WORK_ARRANGEMENT.FLEXIBLE`, `Flexible`],
  [`WORK_ARRANGEMENT.TRAVEL_REQUIRED`, `Déplacements nécessaires`],
  [`WORK_ARRANGEMENT.SHIFT_BASED`, `Basé sur le travail posté`],
  [`COMMON.ADD`, `Ajouter`],
  [`COMMON.REMOVE`, `Supprimer`],
  [`COMMON.ALREADY_EXISTS`, `Existe déjà`],
  [`COMMON.LANGUAGE_LEVEL`, `Niveau de langue`],
  [`COMMON.LANGUAGES`, `Langues`],
  [`COMMON.EDIT_LANGUAGES`, `Modifier les langues`],
  [`ERROR.COMMON_ERROR`, `Une erreur inattendue s'est produite.`],
  [`ERROR.NOT_FOUND`, `Non trouvé`],
  [`ERROR.ENTITY_NOT_FOUND`, `Entité non trouvée`],
  [`ERROR.ENTITY_WITH_ID_NOT_FOUND`, `L'entité avec cet identifiant n'a pas été trouvée`],
  [`ERROR.ENTITY_WITH_EMAIL_ALREADY_EXISTS`, `L'entité avec cet email existe déjà`],
  [`ERROR.ENTITY_WITH_LOGIN_ALREADY_EXISTS`, `L'entité avec ce login existe déjà`],
  [`ERROR.VALIDATION_ERROR`, `Erreur de validation`],
  [`ERROR.ENTITY_ALREADY_EXISTS`, `L'entité existe déjà`],
  [`ERROR.INTERNAL_SERVER_ERROR`, `Erreur interne du serveur`],
  [`ERROR.BLOCKED`, `Bloqué`],
  [`ERROR.RESOURCE_NOT_FOUND`, `Ressource non trouvée`],
  [`ERROR.ENTITY_BLOCKED`, `L'entité est bloquée`],
  [`ERROR.ENTITY_PESSIMISTIC_LOCKED`, `L'entité est verrouillée de manière pessimiste`],
  [`ERROR.WRONG_AUTH`, `Mauvaises informations d'identification`],
  [`ERROR.FORBIDDEN`, `Accès refusé`],
  [`ERROR.USER_BLOCKED`, `L'utilisateur est bloqué`],
  [`ERROR.POTENTIAL_HARMFUL_CONTENT`, `Contenu potentiellement dangereux détecté`],
  [`ERROR.JWT_MIN_LENGTH`, `Le jeton JWT est trop court`],
  [`ERROR.JWT_INVALID_FORMAT`, `Format JWT non valide`],
  [`ERROR.JWT_USER_CLAIM_NOT_FOUND`, `La demande de l'utilisateur n'a pas été trouvée dans le JWT`],
  [`ERROR.JWT_USER_CLAIM_INVALID_CONVERSION`, `Impossible de convertir la demande de l'utilisateur en JWT`],
  [`ERROR.FORGOT_PASSWORD_REQUEST_TOO_SOON`, `Mot de passe oublié demandé trop tôt`],
  [`ERROR.RESTORE_PASSWORD_PROCESSING_ISSUE`, `Un problème est survenu lors de la restauration du mot de passe`],
  [`ERROR.VERSION_NOT_SPECIFIED`, `Version non spécifiée`],
  [`ERROR.USER_PROJECT_LIMIT_EXCEEDED`, `L'utilisateur a dépassé la limite du projet`],
  [`ERROR.ROLE_NOT_SUPPORTED`, `Ce rôle n'est pas pris en charge`],
  [`STATUS.NEW`, `Nouveau`],
  [`STATUS.ACTIVE`, `Actif`],
  [`STATUS.INACTIVE`, `Inactif`],
  [`STATUS.BLOCKED`, `Bloqué`],
  [`STATUS.DELETED`, `Supprimé`],
  [`STATUS.PENDING`, `En attente`],
  [`STATUS.APPROVED`, `Approuvé`],
  [`STATUS.COMPLETED`, `Terminé`],
  [`STATUS.CANCELLED`, `Annulé`],
]);
