// Auto-generated file from a7-localizations_it.csv

export const localization_it: Map<string, string> = new Map<string, string>([
  ['AUTH.GREETINGS', 'Saluti, caro Honkler!'],
  ['AUTH.SIGN_IN.JOKE', 'Forse dobbiamo tornare a'],
  ['AUTH.NO_ACCOUNT_SIGN_UP', 'Non hai un account? Registrati ora!'],
  ['AUTH.HAS_ACCOUNT_SIGN_IN', 'Hai già un account? Accedi ora!'],
  ['COMMON.FIX_ERROR_BEFORE_CONTINUE', 'Per favore correggi l\'errore prima di continuare.'],
  ['COMMON.WE_ARE_HONKING', 'Stiamo honking dal 2024!'],
  ['COMMON.BUTTON.OK', 'OK'],
  ['COMMON.BUTTON.CANCEL', 'Annulla'],
  ['COMMON.BUTTON.PROCEED', 'Procedi'],
  ['COMMON.BUTTON.SAVE', 'Salva'],
  ['COMMON.BUTTON.UPDATE', 'Aggiorna'],
  ['COMMON.BUTTON.HONK', 'Honk'],
  ['COMMON.BUTTON.ADD', 'Aggiungi'],
  ['COMMON.BUTTON.REMOVE', 'Rimuovi'],
  ['COMMON.BUTTON.EDIT', 'Modifica'],
  ['COMMON.BUTTON.CREATE', 'Crea'],
  ['COMMON.BUTTON.RESET', 'Reimposta'],
  ['AUTH.SIGN_IN.LOGIN_OR_EMAIL', 'Nome utente o email'],
  ['COMMON.PASSWORD', 'Password'],
  ['AUTH.SIGN_IN.REMEMBER_ME', 'Ricordami'],
  ['AUTH.FORGOT', 'Dimenticato?'],
  ['AUTH.SIGN_IN.SIGN_IN', 'Accedi'],
  ['COMMON.EMAIL', 'Email'],
  ['COMMON.LOGIN', 'Nome utente'],
  ['AUTH.SIGN_UP.WELCOME', 'Benvenuto nella comunità Honkler!'],
  ['COMMON.FIRST_NAME', 'Nome'],
  ['COMMON.LAST_NAME', 'Cognome'],
  ['COMMON.CONFIRM_EMAIL', 'Conferma email'],
  ['COMMON.CONFIRM_PASSWORD', 'Conferma password'],
  ['COMMON.NO_COMPLAINTS', 'Nessuna lamentela'],
  ['COMMON.SIGN_UP', 'Registrati'],
  ['PROFILE.EDUCATION.FIELD_OF_STUDY', 'Campo di studio'],
  ['PROFILE.EDUCATION.INSTITUTION', 'Istituzione'],
  ['COMMON.DO_NOT_STORE_ANY_SENSITIVE_DATA', 'Non memorizzare dati sensibili'],
  ['COMMON.START_DATE', 'Data di inizio'],
  ['COMMON.END_DATE', 'Data di fine'],
  ['COMMON.ISSUE_DATE', 'Data di emissione'],
  ['COMMON.EXPIRATION_DATE', 'Data di scadenza'],
  ['PROFILE.CERTIFICATION.CERTIFICATION', 'Certificazione'],
  ['PROFILE.CERTIFICATION.ISSUER', 'Emittente'],
  ['PROFILE.PROJECT.PROJECT', 'Progetto'],
  ['PROFILE.COMPANY.COMPANY', 'Azienda'],
  ['PROFILE.ACHIEVEMENT.ACHIEVEMENT', 'Risultato'],
  ['COMMON.POSITION', 'Posizione'],
  ['COMMON.LOCATION', 'Località'],
  ['COMMON.COUNTRY', 'Paese'],
  ['JOB_TYPE.JOB_TYPE', 'Tipo di lavoro'],
  ['JOB_TYPE.FULL_TIME', 'Tempo pieno'],
  ['JOB_TYPE.PART_TIME', 'Part-time'],
  ['JOB_TYPE.CONTRACT', 'Contratto'],
  ['JOB_TYPE.TEMPORARY', 'Temporaneo'],
  ['JOB_TYPE.INTERN', 'Tirocinante'],
  ['JOB_TYPE.VOLUNTEER', 'Volontario'],
  ['JOB_TYPE.FREELANCE', 'Freelance'],
  ['JOB_TYPE.STARTUP', 'Startup'],
  ['JOB_TYPE.OTHER', 'Altro'],
  ['JOB_TYPE.DISTANCE', 'A distanza'],
  ['JOB_TYPE.EVENING', 'Sera'],
  ['JOB_TYPE.ONLINE', 'Online'],
  ['JOB_TYPE.MIXED', 'Misto'],
  ['JOB_TYPE.EXCHANGE', 'Scambio'],
  ['JOB_TYPE.SELF_PACED', 'Autogestito'],
  ['JOB_TYPE.IN_PERSON', 'In presenza'],
  ['JOB_TYPE.HYBRID', 'Ibrido'],
  ['JOB_TYPE.PROCTORED_ONLINE', 'Online supervisionato'],
  ['JOB_TYPE.UNPROCTORED', 'Non supervisionato'],
  ['WORK_ARRANGEMENT.WORK_ARRANGEMENT', 'Modalità di lavoro'],
  ['WORK_ARRANGEMENT.ON_SITE', 'In sede'],
  ['WORK_ARRANGEMENT.REMOTE', 'Remoto'],
  ['WORK_ARRANGEMENT.HYBRID', 'Ibrido'],
  ['WORK_ARRANGEMENT.FLEXIBLE', 'Flessibile'],
  ['WORK_ARRANGEMENT.TRAVEL_REQUIRED', 'Richiede viaggi'],
  ['WORK_ARRANGEMENT.SHIFT_BASED', 'A turni'],
  ['COMMON.DESCRIPTION', 'Descrizione'],
  ['COMMON.SALARY_RANGE', 'Fascia di stipendio'],
  ['COMMON.FROM', 'Da'],
  ['COMMON.TO', 'A'],
  ['COMMON.SKILLS', 'Competenze'],
  ['COMMON.SKILL', 'Competenza'],
  ['EXPERIENCE_LEVEL.EXPERIENCE_LEVEL', 'Livello di esperienza'],
  ['EXPERIENCE_LEVEL.INTERNSHIP', 'Tirocinio'],
  ['EXPERIENCE_LEVEL.ENTRY_LEVEL', 'Principiante'],
  ['EXPERIENCE_LEVEL.JUNIOR', 'Junior'],
  ['EXPERIENCE_LEVEL.MID_LEVEL', 'Medio'],
  ['EXPERIENCE_LEVEL.SENIOR', 'Senior'],
  ['EXPERIENCE_LEVEL.LEADER', 'Capo'],
  ['EXPERIENCE_LEVEL.EXECUTIVE', 'Dirigente'],
  ['EXPERIENCE_LEVEL.PRINCIPAL', 'Principale'],
  ['EXPERIENCE_LEVEL.STAFF', 'Staff'],
  ['EXPERIENCE_LEVEL.OTHER', 'Altro'],
  ['EXPERIENCE_LEVEL.TIER_1', 'Livello 1'],
  ['EXPERIENCE_LEVEL.TIER_2', 'Livello 2'],
  ['EXPERIENCE_LEVEL.TIER_3', 'Livello 3'],
  ['EXPERIENCE_LEVEL.TIER_4', 'Livello 4'],
  ['EXPERIENCE_LEVEL.TIER_5', 'Livello 5'],
  ['EXPERIENCE_LEVEL.TIER_6', 'Livello 6'],
  ['EXPERIENCE_LEVEL.TIER_7', 'Livello 7'],
  ['COMMON.LANGUAGES', 'Lingue'],
  ['COMMON.LANGUAGE', 'Lingua'],
  ['LANGUAGE_LEVEL.LANGUAGE_LEVEL', 'Livello di lingua'],
  ['LANGUAGE_LEVEL.BEGINNER', 'Principiante'],
  ['LANGUAGE_LEVEL.ELEMENTARY', 'Elementare'],
  ['LANGUAGE_LEVEL.INTERMEDIATE', 'Intermedio'],
  ['LANGUAGE_LEVEL.UPPER_INTERMEDIATE', 'Intermedio superiore'],
  ['LANGUAGE_LEVEL.ADVANCED', 'Avanzato'],
  ['LANGUAGE_LEVEL.PROFICIENT', 'Esperto'],
  ['LANGUAGE_LEVEL.NATIVE', 'Madrelingua'],
  ['PROFILE.SECTION.PRIMARY_INFO', 'Informazioni principali'],
  ['PROFILE.SECTION.AUTH_SECTION', 'Sezione autenticazione'],
  ['PROFILE.HEADLINE', 'Titolo'],
  ['PROFILE.SECTION.SECONDARY_INFO', 'Informazioni secondarie'],
  ['COMMON.CURRENCY', 'Valuta'],
  ['COMMON.TIME_ZONE', 'Fuso orario'],
  ['COMMON.PHONE', 'Telefono'],
  ['PROFILE.LINKS', 'Link'],
  ['PROFILE.SECTION.AI', 'IA'],
  ['PROFILE.APPLICATION.AI_TEXTAREA', 'Area di testo IA per l\'applicazione'],
  ['THEME.DARK', 'Tema scuro'],
  ['THEME.LIGHT', 'Tema chiaro'],
  ['MENU.HOME', 'Home'],
  ['MENU.JOBS', 'Lavori'],
  ['MENU.COMPANIES', 'Aziende'],
  ['MENU.KARMA', 'Karma'],
  ['IN_DEVELOPMENT.OOPS_PAGE', 'Ops! Pagina in costruzione.'],
  ['COMMON.GO_HOME', 'Torna alla home'],
  ['COMMON.BACK_TO_SIGN_IN', 'Torna all\'accesso'],
  ['NOT_FOUND.PAGE_NOT_FOUND', 'Ops! La pagina che stai cercando non esiste.'],
  ['MENU.ACTIVE_APPLICATIONS', 'Applicazioni attive'],
  ['MENU.TODOS', 'Da fare'],
  ['MENU.RESPONSE_RATE', 'Tasso di risposta'],
  ['MENU.UPCOMING_INTERVIEWS', 'Colloqui in arrivo'],
  ['STATS.NEW_JOB_LISTINGS_PER_DAY', 'Nuove offerte di lavoro al giorno'],
  ['STATS.JOB_APPLICATIONS_TREND', 'Andamento delle candidature'],
  ['COMMON.JOB.NEW_APPLICATION', 'Candidatura'],
  ['COMMON.JOB.NEW_APPLICATIONS', 'Candidature'],
  ['STATS.TOP_COMPANIES', 'Top aziende'],
  ['STATS.APPLICATION_STATUS_DISTRIBUTION', 'Distribuzione dello stato delle candidature'],
  ['JOB_STATUS.APPLIED', 'Candidato'],
  ['JOB_STATUS.IN_REVIEW', 'In revisione'],
  ['JOB_STATUS.INTERVIEW', 'Colloquio'],
  ['JOB_STATUS.OFFER', 'Offerta'],
  ['JOB_STATUS.REJECTED', 'Rifiutato'],
  ['COMMON.WELCOME_BACK', 'Bentornato'],
  ['PROFILE.SECTION.WORK_EXPERIENCE', 'Esperienza lavorativa'],
  ['PROFILE.SECTION.EDUCATION', 'Istruzione'],
  ['PROFILE.SECTION.PROJECTS', 'Progetti'],
  ['PROFILE.SECTION.ACHIEVEMENTS', 'Risultati'],
  ['PROFILE.SECTION.CERTIFICATIONS', 'Certificazioni'],
  ['COMMON.EMPTY_SECTION', 'Sezione vuota'],
  ['PROFILE.USER_PREFERENCES', 'Preferenze utente'],
  ['ERROR.NOT_FOUND', 'Non trovato'],
  ['ERROR.ENTITY_NOT_FOUND', 'Entità non trovata'],
  ['ERROR.ENTITY_WITH_ID_NOT_FOUND', 'Entità con ID non trovata'],
  ['ERROR.ENTITY_WITH_EMAIL_ALREADY_EXISTS', 'Entità con questa email esiste già'],
  ['ERROR.ENTITY_WITH_LOGIN_ALREADY_EXISTS', 'Entità con questo login esiste già'],
  ['ERROR.VALIDATION_ERROR', 'Errore di validazione'],
  ['ERROR.ENTITY_ALREADY_EXISTS', 'Entità già esistente'],
  ['ERROR.ALREADY_EXISTS', 'Già esistente'],
  ['ERROR.INTERNAL_SERVER_ERROR', 'Errore interno del server'],
  ['ERROR.BLOCKED', 'Bloccato'],
  ['ERROR.RESOURCE_NOT_FOUND', 'Risorsa non trovata'],
  ['ERROR.ENTITY_BLOCKED', 'Entità bloccata'],
  ['ERROR.ENTITY_PESSIMISTIC_LOCKED', 'Entità bloccata'],
  ['ERROR.WRONG_AUTH', 'Autenticazione errata'],
  ['ERROR.FORBIDDEN', 'Vietato'],
  ['ERROR.USER_BLOCKED', 'Utente bloccato'],
  ['ERROR.POTENTIAL_HARMFUL_CONTENT', 'Contenuto potenzialmente dannoso'],
  ['ERROR.JWT_MIN_LENGTH', 'Lunghezza minima JWT'],
  ['ERROR.JWT_INVALID_FORMAT', 'Formato JWT non valido'],
  ['ERROR.JWT_USER_CLAIM_NOT_FOUND', 'Richiesta utente JWT non trovata'],
  ['ERROR.JWT_USER_CLAIM_INVALID_CONVERSION', 'Conversione non valida della richiesta utente JWT'],
  ['ERROR.FORGOT_PASSWORD_REQUEST_TOO_SOON', 'Richiesta password dimenticata troppo presto'],
  ['ERROR.RESTORE_PASSWORD_PROCESSING_ISSUE', 'Problema nell\'elaborazione del ripristino della password'],
  ['ERROR.VERSION_NOT_SPECIFIED', 'Versione non specificata'],
  ['ERROR.VERSION_NOT_SUPPORTED', 'Versione non supportata'],
  ['ERROR.UPDATE_ONLY_OWN_SETTINGS', 'Aggiorna solo le tue impostazioni'],
  ['ERROR.INVALID_URL', 'URL non valida'],
  ['ERROR.URL_NOT_HTTPS', 'URL non HTTPS'],
  ['ERROR.UNKNOWN_URL_TYPE', 'Tipo di URL sconosciuto'],
  ['ENTITY.STATUS.NEW', 'Nuovo'],
  ['ENTITY.STATUS.ACTIVE', 'Attivo'],
  ['ENTITY.STATUS.INACTIVE', 'Inattivo'],
  ['ENTITY.STATUS.BLOCKED', 'Bloccato'],
  ['ENTITY.STATUS.DELETED', 'Eliminato'],
  ['ENTITY.STATUS.PENDING', 'In attesa'],
  ['ENTITY.STATUS.APPROVED', 'Approvato'],
  ['ENTITY.STATUS.REJECTED', 'Rifiutato'],
  ['ENTITY.STATUS.COMPLETED', 'Completato'],
  ['ENTITY.STATUS.CANCELLED', 'Annullato'],
  ['ENTITY.STATUS.ARCHIVED', 'Archiviato'],
  ['MESSAGES.CHANGES_SUCCESSFULLY_SAVED', 'Modifiche salvate con successo'],
  ['DATES.JANUARY_SHORT', 'Gen'],
  ['DATES.FEBRUARY_SHORT', 'Feb'],
  ['DATES.MARCH_SHORT', 'Mar'],
  ['DATES.APRIL_SHORT', 'Apr'],
  ['DATES.MAY_SHORT', 'Mag'],
  ['DATES.JUNE_SHORT', 'Giu'],
  ['DATES.JULY_SHORT', 'Lug'],
  ['DATES.AUGUST_SHORT', 'Ago'],
  ['DATES.SEPTEMBER_SHORT', 'Set'],
  ['DATES.OCTOBER_SHORT', 'Ott'],
  ['DATES.NOVEMBER_SHORT', 'Nov'],
  ['DATES.DECEMBER_SHORT', 'Dic'],
  ['DATES.MONDAY_SHORT', 'Lun'],
  ['DATES.TUESDAY_SHORT', 'Mar'],
  ['DATES.WEDNESDAY_SHORT', 'Mer'],
  ['DATES.THURSDAY_SHORT', 'Gio'],
  ['DATES.FRIDAY_SHORT', 'Ven'],
  ['DATES.SATURDAY_SHORT', 'Sab'],
  ['DATES.SUNDAY_SHORT', 'Dom'],
  ['INPUT.TOO_MANY_ITEMS_START_TYPING', 'Troppi elementi, inizia a digitare...'],
  ['ERROR.FIELD_REQUIRED', 'Campo obbligatorio'],
  ['ERROR.CHECK_CHECKBOX', 'Seleziona la casella'],
  ['ERROR.INVALID_EMAIL', 'Email non valida'],
  ['JOB_SOURCE.JOB_BOARD', 'Bacheca delle offerte di lavoro'],
  ['JOB_SOURCE.COMPANY_WEBSITE', 'Sito web aziendale'],
  ['JOB_SOURCE.RECOMMENDATION', 'Raccomandazione'],
  ['JOB_SOURCE.SOCIAL_MEDIA', 'Social media'],
  ['JOB_SOURCE.OTHER', 'Altro'],
  ['ROLE.ROLE', 'Ruolo'],
  ['ROLE.USER', 'Utente'],
  ['ROLE.TECHNICAL_SUPPORT', 'Supporto tecnico'],
  ['ROLE.ADMIN', 'Amministratore'],
  ['ROLE.SUPER_ADMIN', 'Super amministratore'],
  ['COMMON.JOB_TITLE', 'Titolo del lavoro'],
  ['COMMON.SOURCE', 'Fonte'],
  ['COMMON.POSTED_DATE', 'Data di pubblicazione'],
  ['COMMON.DEADLINE', 'Scadenza'],
  ['COMMON.CONTACT_EMAIL', 'Email di contatto'],
  ['APPLICATION.APPLICATION_LINK', 'Link della candidatura'],
  ['COMMON.NOTES', 'Note'],
  ['SKILL_LEVEL.SKILL_LEVEL', 'Livello di competenza'],
  ['SKILL_LEVEL.BEGINNER', 'Principiante'],
  ['SKILL_LEVEL.BASIC', 'Base'],
  ['SKILL_LEVEL.INTERMEDIATE', 'Intermedio'],
  ['SKILL_LEVEL.ADVANCED', 'Avanzato'],
  ['SKILL_LEVEL.EXPERT', 'Esperto'],
  ['SKILL_LEVEL.MASTER', 'Master'],
  ['SKILL_LEVEL.WORLD_CLASS', 'Di fama mondiale'],
]);
