// Auto-generated file from a4-localizations_ua.csv

export const localization_ua: Map<string, string> = new Map<string, string>([
  ['AUTH.GREETINGS', 'Вітаємо, Honkler!'],
  ['AUTH.SIGN_IN.JOKE', 'Можливо, нам потрібно повернутися до'],
  ['AUTH.NO_ACCOUNT_SIGN_UP', 'Немає облікового запису? Зареєструйтесь зараз!'],
  ['AUTH.HAS_ACCOUNT_SIGN_IN', 'Вже маєте обліковий запис? Увійдіть зараз!'],
  ['COMMON.FIX_ERROR_BEFORE_CONTINUE', 'Будь ласка, виправте помилку перед продовженням.'],
  ['COMMON.WE_ARE_HONKING', 'Ми honk\'аємо з 2024 року!'],
  ['COMMON.BUTTON.OK', 'OK'],
  ['COMMON.BUTTON.CANCEL', 'Скасувати'],
  ['COMMON.BUTTON.PROCEED', 'Продовжити'],
  ['COMMON.BUTTON.SAVE', 'Зберегти'],
  ['COMMON.BUTTON.UPDATE', 'Оновити'],
  ['COMMON.BUTTON.HONK', 'Honk'],
  ['COMMON.BUTTON.ADD', 'Додати'],
  ['COMMON.BUTTON.REMOVE', 'Видалити'],
  ['COMMON.BUTTON.EDIT', 'Редагувати'],
  ['COMMON.BUTTON.CREATE', 'Створити'],
  ['COMMON.BUTTON.RESET', 'Скинути'],
  ['AUTH.SIGN_IN.LOGIN_OR_EMAIL', 'Логін або email'],
  ['COMMON.PASSWORD', 'Пароль'],
  ['AUTH.SIGN_IN.REMEMBER_ME', 'Запам\'ятати мене'],
  ['AUTH.FORGOT', 'Забули?'],
  ['AUTH.SIGN_IN.SIGN_IN', 'Увійти'],
  ['COMMON.EMAIL', 'Email'],
  ['COMMON.LOGIN', 'Логін'],
  ['AUTH.SIGN_UP.WELCOME', 'Ласкаво просимо до спільноти Honkler!'],
  ['COMMON.FIRST_NAME', 'Ім\'я'],
  ['COMMON.LAST_NAME', 'Прізвище'],
  ['COMMON.CONFIRM_EMAIL', 'Підтвердити email'],
  ['COMMON.CONFIRM_PASSWORD', 'Підтвердити пароль'],
  ['COMMON.NO_COMPLAINTS', 'Немає скарг'],
  ['COMMON.SIGN_UP', 'Зареєструватися'],
  ['PROFILE.EDUCATION.FIELD_OF_STUDY', 'Спеціальність'],
  ['PROFILE.EDUCATION.INSTITUTION', 'Заклад'],
  ['COMMON.DO_NOT_STORE_ANY_SENSITIVE_DATA', 'Не зберігайте конфіденційні дані'],
  ['COMMON.START_DATE', 'Дата початку'],
  ['COMMON.END_DATE', 'Дата закінчення'],
  ['COMMON.ISSUE_DATE', 'Дата видачі'],
  ['COMMON.EXPIRATION_DATE', 'Термін дії'],
  ['PROFILE.CERTIFICATION.CERTIFICATION', 'Сертифікат'],
  ['PROFILE.CERTIFICATION.ISSUER', 'Видавець'],
  ['PROFILE.PROJECT.PROJECT', 'Проект'],
  ['PROFILE.COMPANY.COMPANY', 'Компанія'],
  ['PROFILE.ACHIEVEMENT.ACHIEVEMENT', 'Досягнення'],
  ['COMMON.POSITION', 'Посада'],
  ['COMMON.LOCATION', 'Місцезнаходження'],
  ['COMMON.COUNTRY', 'Країна'],
  ['JOB_TYPE.JOB_TYPE', 'Тип роботи'],
  ['JOB_TYPE.FULL_TIME', 'Повний робочий день'],
  ['JOB_TYPE.PART_TIME', 'Неповний робочий день'],
  ['JOB_TYPE.CONTRACT', 'Контракт'],
  ['JOB_TYPE.TEMPORARY', 'Тимчасово'],
  ['JOB_TYPE.INTERN', 'Стажування'],
  ['JOB_TYPE.VOLUNTEER', 'Волонтерство'],
  ['JOB_TYPE.FREELANCE', 'Фріланс'],
  ['JOB_TYPE.STARTUP', 'Стартап'],
  ['JOB_TYPE.OTHER', 'Інше'],
  ['JOB_TYPE.DISTANCE', 'Дистанційно'],
  ['JOB_TYPE.EVENING', 'Вечірня'],
  ['JOB_TYPE.ONLINE', 'Онлайн'],
  ['JOB_TYPE.MIXED', 'Змішана'],
  ['JOB_TYPE.EXCHANGE', 'Обмін'],
  ['JOB_TYPE.SELF_PACED', 'За власним графіком'],
  ['JOB_TYPE.IN_PERSON', 'Особисто'],
  ['JOB_TYPE.HYBRID', 'Гібридна'],
  ['JOB_TYPE.PROCTORED_ONLINE', 'Онлайн з наглядом'],
  ['JOB_TYPE.UNPROCTORED', 'Без нагляду'],
  ['WORK_ARRANGEMENT.WORK_ARRANGEMENT', 'Формат роботи'],
  ['WORK_ARRANGEMENT.ON_SITE', 'В офісі'],
  ['WORK_ARRANGEMENT.REMOTE', 'Віддалено'],
  ['WORK_ARRANGEMENT.HYBRID', 'Гібридна'],
  ['WORK_ARRANGEMENT.FLEXIBLE', 'Гнучка'],
  ['WORK_ARRANGEMENT.TRAVEL_REQUIRED', 'З переїздами'],
  ['WORK_ARRANGEMENT.SHIFT_BASED', 'Змінна'],
  ['COMMON.DESCRIPTION', 'Опис'],
  ['COMMON.SALARY_RANGE', 'Діапазон зарплати'],
  ['COMMON.FROM', 'Від'],
  ['COMMON.TO', 'До'],
  ['COMMON.SKILLS', 'Навички'],
  ['COMMON.SKILL', 'Навичка'],
  ['EXPERIENCE_LEVEL.EXPERIENCE_LEVEL', 'Рівень досвіду'],
  ['EXPERIENCE_LEVEL.INTERNSHIP', 'Стажування'],
  ['EXPERIENCE_LEVEL.ENTRY_LEVEL', 'Початковий рівень'],
  ['EXPERIENCE_LEVEL.JUNIOR', 'Молодший спеціаліст'],
  ['EXPERIENCE_LEVEL.MID_LEVEL', 'Середній рівень'],
  ['EXPERIENCE_LEVEL.SENIOR', 'Старший спеціаліст'],
  ['EXPERIENCE_LEVEL.LEADER', 'Лід'],
  ['EXPERIENCE_LEVEL.EXECUTIVE', 'Керівник'],
  ['EXPERIENCE_LEVEL.PRINCIPAL', 'Головний спеціаліст'],
  ['EXPERIENCE_LEVEL.STAFF', 'Персонал'],
  ['EXPERIENCE_LEVEL.OTHER', 'Інше'],
  ['EXPERIENCE_LEVEL.TIER_1', 'Рівень 1'],
  ['EXPERIENCE_LEVEL.TIER_2', 'Рівень 2'],
  ['EXPERIENCE_LEVEL.TIER_3', 'Рівень 3'],
  ['EXPERIENCE_LEVEL.TIER_4', 'Рівень 4'],
  ['EXPERIENCE_LEVEL.TIER_5', 'Рівень 5'],
  ['EXPERIENCE_LEVEL.TIER_6', 'Рівень 6'],
  ['EXPERIENCE_LEVEL.TIER_7', 'Рівень 7'],
  ['COMMON.LANGUAGES', 'Мови'],
  ['COMMON.LANGUAGE', 'Мова'],
  ['LANGUAGE_LEVEL.LANGUAGE_LEVEL', 'Рівень мови'],
  ['LANGUAGE_LEVEL.BEGINNER', 'Початківець'],
  ['LANGUAGE_LEVEL.ELEMENTARY', 'Елементарний'],
  ['LANGUAGE_LEVEL.INTERMEDIATE', 'Середній'],
  ['LANGUAGE_LEVEL.UPPER_INTERMEDIATE', 'Вище середнього'],
  ['LANGUAGE_LEVEL.ADVANCED', 'Просунутий'],
  ['LANGUAGE_LEVEL.PROFICIENT', 'Вільний'],
  ['LANGUAGE_LEVEL.NATIVE', 'Рідна'],
  ['PROFILE.SECTION.PRIMARY_INFO', 'Основна інформація'],
  ['PROFILE.SECTION.AUTH_SECTION', 'Розділ авторизації'],
  ['PROFILE.HEADLINE', 'Заголовок'],
  ['PROFILE.SECTION.SECONDARY_INFO', 'Додаткова інформація'],
  ['COMMON.CURRENCY', 'Валюта'],
  ['COMMON.TIME_ZONE', 'Часовий пояс'],
  ['COMMON.PHONE', 'Телефон'],
  ['PROFILE.LINKS', 'Посилання'],
  ['PROFILE.SECTION.AI', 'ШІ'],
  ['PROFILE.APPLICATION.AI_TEXTAREA', 'Текстове поле ШІ для заявки'],
  ['THEME.DARK', 'Темна тема'],
  ['THEME.LIGHT', 'Світла тема'],
  ['MENU.HOME', 'Головна'],
  ['MENU.JOBS', 'Вакансії'],
  ['MENU.COMPANIES', 'Компанії'],
  ['MENU.KARMA', 'Карма'],
  ['IN_DEVELOPMENT.OOPS_PAGE', 'Упс! Сторінка в розробці.'],
  ['COMMON.GO_HOME', 'На головну'],
  ['COMMON.BACK_TO_SIGN_IN', 'Повернутися до входу'],
  ['NOT_FOUND.PAGE_NOT_FOUND', 'Упс! Сторінка, яку ви шукаєте, не існує.'],
  ['MENU.ACTIVE_APPLICATIONS', 'Активні заявки'],
  ['MENU.TODOS', 'Завдання'],
  ['MENU.RESPONSE_RATE', 'Частота відповідей'],
  ['MENU.UPCOMING_INTERVIEWS', 'Майбутні співбесіди'],
  ['STATS.NEW_JOB_LISTINGS_PER_DAY', 'Нові вакансії за день'],
  ['STATS.JOB_APPLICATIONS_TREND', 'Тенденція заявок'],
  ['COMMON.JOB.NEW_APPLICATION', 'Заявка на роботу'],
  ['COMMON.JOB.NEW_APPLICATIONS', 'Заявки на роботу'],
  ['STATS.TOP_COMPANIES', 'Топ компаній'],
  ['STATS.APPLICATION_STATUS_DISTRIBUTION', 'Розподіл статусів заявок'],
  ['JOB_STATUS.APPLIED', 'Подано'],
  ['JOB_STATUS.IN_REVIEW', 'На розгляді'],
  ['JOB_STATUS.INTERVIEW', 'Співбесіда'],
  ['JOB_STATUS.OFFER', 'Пропозиція'],
  ['JOB_STATUS.REJECTED', 'Відхилено'],
  ['COMMON.WELCOME_BACK', 'З поверненням'],
  ['PROFILE.SECTION.WORK_EXPERIENCE', 'Досвід роботи'],
  ['PROFILE.SECTION.EDUCATION', 'Освіта'],
  ['PROFILE.SECTION.PROJECTS', 'Проекти'],
  ['PROFILE.SECTION.ACHIEVEMENTS', 'Досягнення'],
  ['PROFILE.SECTION.CERTIFICATIONS', 'Сертифікати'],
  ['COMMON.EMPTY_SECTION', 'Порожній розділ'],
  ['PROFILE.USER_PREFERENCES', 'Налаштування користувача'],
  ['ERROR.NOT_FOUND', 'Не знайдено'],
  ['ERROR.ENTITY_NOT_FOUND', 'Об\'єкт не знайдено'],
  ['ERROR.ENTITY_WITH_ID_NOT_FOUND', 'Об\'єкт з ID не знайдено'],
  ['ERROR.ENTITY_WITH_EMAIL_ALREADY_EXISTS', 'Об\'єкт з таким email вже існує'],
  ['ERROR.ENTITY_WITH_LOGIN_ALREADY_EXISTS', 'Об\'єкт з таким логіном вже існує'],
  ['ERROR.VALIDATION_ERROR', 'Помилка валідації'],
  ['ERROR.ENTITY_ALREADY_EXISTS', 'Об\'єкт вже існує'],
  ['ERROR.ALREADY_EXISTS', 'Вже існує'],
  ['ERROR.INTERNAL_SERVER_ERROR', 'Внутрішня помилка сервера'],
  ['ERROR.BLOCKED', 'Заблоковано'],
  ['ERROR.RESOURCE_NOT_FOUND', 'Ресурс не знайдено'],
  ['ERROR.ENTITY_BLOCKED', 'Об\'єкт заблоковано'],
  ['ERROR.ENTITY_PESSIMISTIC_LOCKED', 'Об\'єкт заблоковано'],
  ['ERROR.WRONG_AUTH', 'Неправильна автентифікація'],
  ['ERROR.FORBIDDEN', 'Заборонено'],
  ['ERROR.USER_BLOCKED', 'Користувач заблокований'],
  ['ERROR.POTENTIAL_HARMFUL_CONTENT', 'Потенційно шкідливий контент'],
  ['ERROR.JWT_MIN_LENGTH', 'Мінімальна довжина JWT'],
  ['ERROR.JWT_INVALID_FORMAT', 'Неправильний формат JWT'],
  ['ERROR.JWT_USER_CLAIM_NOT_FOUND', 'Клейм користувача JWT не знайдено'],
  ['ERROR.JWT_USER_CLAIM_INVALID_CONVERSION', 'Неправильне перетворення клейму користувача JWT'],
  ['ERROR.FORGOT_PASSWORD_REQUEST_TOO_SOON', 'Запит на відновлення паролю надто рано'],
  ['ERROR.RESTORE_PASSWORD_PROCESSING_ISSUE', 'Проблема з обробкою відновлення паролю'],
  ['ERROR.VERSION_NOT_SPECIFIED', 'Версія не вказана'],
  ['ERROR.VERSION_NOT_SUPPORTED', 'Версія не підтримується'],
  ['ERROR.UPDATE_ONLY_OWN_SETTINGS', 'Оновлюйте тільки свої налаштування'],
  ['ERROR.INVALID_URL', 'Неправильний URL'],
  ['ERROR.URL_NOT_HTTPS', 'URL не HTTPS'],
  ['ERROR.UNKNOWN_URL_TYPE', 'Невідомий тип URL'],
  ['ENTITY.STATUS.NEW', 'Новий'],
  ['ENTITY.STATUS.ACTIVE', 'Активний'],
  ['ENTITY.STATUS.INACTIVE', 'Неактивний'],
  ['ENTITY.STATUS.BLOCKED', 'Заблокований'],
  ['ENTITY.STATUS.DELETED', 'Видалений'],
  ['ENTITY.STATUS.PENDING', 'В очікуванні'],
  ['ENTITY.STATUS.APPROVED', 'Схвалено'],
  ['ENTITY.STATUS.REJECTED', 'Відхилено'],
  ['ENTITY.STATUS.COMPLETED', 'Завершено'],
  ['ENTITY.STATUS.CANCELLED', 'Скасовано'],
  ['ENTITY.STATUS.ARCHIVED', 'Архівовано'],
  ['MESSAGES.CHANGES_SUCCESSFULLY_SAVED', 'Зміни успішно збережено'],
  ['DATES.JANUARY_SHORT', 'Січ'],
  ['DATES.FEBRUARY_SHORT', 'Лют'],
  ['DATES.MARCH_SHORT', 'Бер'],
  ['DATES.APRIL_SHORT', 'Кві'],
  ['DATES.MAY_SHORT', 'Тра'],
  ['DATES.JUNE_SHORT', 'Чер'],
  ['DATES.JULY_SHORT', 'Лип'],
  ['DATES.AUGUST_SHORT', 'Сер'],
  ['DATES.SEPTEMBER_SHORT', 'Вер'],
  ['DATES.OCTOBER_SHORT', 'Жов'],
  ['DATES.NOVEMBER_SHORT', 'Лис'],
  ['DATES.DECEMBER_SHORT', 'Гру'],
  ['DATES.MONDAY_SHORT', 'Пн'],
  ['DATES.TUESDAY_SHORT', 'Вв'],
  ['DATES.WEDNESDAY_SHORT', 'Ср'],
  ['DATES.THURSDAY_SHORT', 'Чт'],
  ['DATES.FRIDAY_SHORT', 'Пт'],
  ['DATES.SATURDAY_SHORT', 'Сб'],
  ['DATES.SUNDAY_SHORT', 'Нд'],
  ['INPUT.TOO_MANY_ITEMS_START_TYPING', 'Занадто багато елементів, почніть вводити...'],
  ['ERROR.FIELD_REQUIRED', 'Поле обов\'язкове'],
  ['ERROR.CHECK_CHECKBOX', 'Відмітьте чекбокс'],
  ['ERROR.INVALID_EMAIL', 'Неправильний email'],
  ['JOB_SOURCE.JOB_BOARD', 'Дошка вакансій'],
  ['JOB_SOURCE.COMPANY_WEBSITE', 'Сайт компанії'],
  ['JOB_SOURCE.RECOMMENDATION', 'Рекомендація'],
  ['JOB_SOURCE.SOCIAL_MEDIA', 'Соціальні мережі'],
  ['JOB_SOURCE.OTHER', 'Інше'],
  ['ROLE.ROLE', 'Роль'],
  ['ROLE.USER', 'Користувач'],
  ['ROLE.TECHNICAL_SUPPORT', 'Технічна підтримка'],
  ['ROLE.ADMIN', 'Адміністратор'],
  ['ROLE.SUPER_ADMIN', 'Супер адміністратор'],
  ['COMMON.JOB_TITLE', 'Назва вакансії'],
  ['COMMON.SOURCE', 'Джерело'],
  ['COMMON.POSTED_DATE', 'Дата публікації'],
  ['COMMON.DEADLINE', 'Термін подання'],
  ['COMMON.CONTACT_EMAIL', 'Контактний email'],
  ['APPLICATION.APPLICATION_LINK', 'Посилання на заявку'],
  ['COMMON.NOTES', 'Примітки'],
  ['SKILL_LEVEL.SKILL_LEVEL', 'Рівень навички'],
  ['SKILL_LEVEL.BEGINNER', 'Початківець'],
  ['SKILL_LEVEL.BASIC', 'Базовий'],
  ['SKILL_LEVEL.INTERMEDIATE', 'Середній'],
  ['SKILL_LEVEL.ADVANCED', 'Просунутий'],
  ['SKILL_LEVEL.EXPERT', 'Експерт'],
  ['SKILL_LEVEL.MASTER', 'Майстер'],
  ['SKILL_LEVEL.WORLD_CLASS', 'Світовий клас'],
  ['PROFILE.SHOW_CURRENT_POSITION', 'Показати поточну посаду'],
  ['PROFILE.SHOW_HIGHEST_EDUCATION', 'Показати найвищу освіту'],
]);
