// Auto-generated file from a3-localizations_fr.csv

export const localization_fr: Map<string, string> = new Map<string, string>([
  [`AUTH.GREETINGS`, `Salutations, Honkler!`],
  [`AUTH.SIGN_IN.JOKE`, `Peut-être devons-nous revenir à`],
  [`COMMON.LOGIN_OR_EMAIL`, `Connexion ou Email`],
  [`COMMON.PASSWORD`, `Mot de passe`],
  [`COMMON.CONFIRM_PASSWORD`, `Confirmer le mot de passe`],
  [`COMMON.REMEMBER_ME`, `Se souvenir de moi`],
  [`COMMON.FORGOT`, `Mot de passe oublié`],
  [`COMMON.SIGN_IN`, `Se connecter`],
  [`COMMON.SIGN_UP`, `Sinscrire`],
  [`AUTH.NO_ACCOUNT.SIGN_UP`, `Vous n'avez pas de compte? Inscrivez-vous`],
  [`AUTH.HAS_ACCOUNT.SIGN_IN`, `Vous avez déjà un compte? Connectez-vous`],
  [`COMMON.LOGIN`, `Connexion`],
  [`COMMON.EMAIL`, `E-mail`],
  [`COMMON.CONFIRM_EMAIL`, `Confirmer l'e-mail`],
  [`COMMON.PROCEED`, `Continuer`],
  [`COMMON.FIRST_NAME`, `Prénom`],
  [`COMMON.LAST_NAME`, `Nom de famille`],
  [`COMMON.NO_COMPLAINTS`, `Aucune plainte`],
  [`COMMON.WE_ARE_HONKING`, `Nous klaxonnons depuis 2024!`],
  [`COMMON.DO_NOT_STORE_SENS_DATA`, `NE STOCKEZ AUCUNE DONNÉE SENSIBLE ICI!`],
  [`COMMON.LIGHT_THEME`, `Thème clair`],
  [`COMMON.DARK_THEME`, `Thème sombre`],
  [`ERROR.PASSWORDS_DO_NOT_MATCH`, `Les mots de passe ne correspondent pas`],
  [`ERROR.EMAILS_DO_NOT_MATCH`, `Les e-mails ne correspondent pas`],
  [`ERROR.FIELD_REQUIRED`, `Le champ est obligatoire!`],
  [`ERROR.CHECK_CHECKBOX`, `Veuillez cocher la case!`],
  [`ERROR.INVALID_EMAIL`, `Format d'email invalide!`],
  [`ERROR.UNEXPECTED_ERROR`, `Une erreur inattendue s'est produite!`],
  [`MENU.HOME`, `Accueil`],
  [`MENU.JOBS`, `Emplois`],
  [`MENU.COMPANIES`, `Entreprises`],
  [`MENU.KARMA`, `Karma`],
  [`COMMON.WELCOME_BACK`, `Bon retour`],
  [`MENU.ACTIVE_APPLICATIONS`, `Candidatures actives`],
  [`MENU.TODOS`, `Tâches`],
  [`MENU.RESPONSE_RATE`, `Taux de réponse`],
  [`MENU.UPCOMING_INTERVIEWS`, `Entretiens à venir`],
  [`COMMON.NEW_APPLICATION`, `Nouvelle candidature`],
  [`STATS.JOB_APPLICATIONS_TREND`, `Tendance des candidatures`],
  [`STATS.TOP_COMPANIES`, `Meilleures entreprises (Candidatures)`],
  [`STATS.NEW_JOB_LISTINGS_PER_DAY`, `Nouvelles offres d'emploi par jour`],
  [`STATS.APPLICATION_STATUS_DISTRIBUTION`, `Répartition des statuts de candidature`],
  [`STATUS.APPLIED`, `Postulé`],
  [`STATUS.REJECTED`, `Rejeté`],
  [`STATUS.OFFER`, `Offre`],
  [`STATUS.INTERVIEW`, `Entretien`],
  [`STATUS.IN_REVIEW`, `En cours d'examen`],
  [`COMMON.CREATE`, `Créer`],
  [`COMMON.EDIT`, `Modifier`],
  [`COMMON.APPLICATION_LINK`, `Lien de candidature`],
  [`COMMON.JOB_TITLE`, `Intitulé du poste`],
  [`COMMON.COMPANY`, `Entreprise`],
  [`COMMON.LOCATION`, `Lieu`],
  [`COMMON.EXPERIENCE_LEVEL`, `Niveau d'expérience`],
  [`COMMON.JOB_TYPE`, `Type d'emploi`],
  [`COMMON.SOURCE`, `Source`],
  [`COMMON.SALARY_RANGE`, `Échelle salariale`],
  [`COMMON.FROM`, `De`],
  [`COMMON.TO`, `À`],
  [`COMMON.CURRENCY`, `Devise`],
  [`COMMON.POSTED_DATE`, `Date de publication`],
  [`COMMON.APPLICATION_DEADLINE`, `Date limite de candidature`],
  [`COMMON.Contact_EMAIL`, `Email de contact`],
  [`COMMON.DESCRIPTION`, `Description`],
  [`COMMON.NOTES`, `Notes`],
  [`COMMON.CANCEL`, `Annuler`],
  [`COMMON.UPDATE`, `Mettre à jour`],
  [`COMMON.EDIT_PROFILE`, `Modifier le profil`],
  [`COMMON.EDIT_SKILLS`, `Modifier les compétences`],
  [`COMMON.ADD_EXPERIENCE`, `Ajouter une expérience`],
  [`COMMON.SKILLS`, `Compétences`],
  [`COMMON.EXPERIENCE`, `Expérience`],
  [`COMMON.EDUCATION`, `Éducation`],
  [`COMMON.CERTIFICATIONS`, `Certifications`],
  [`ROLE.USER`, `Utilisateur`],
  [`ROLE.TECHNICAL_SUPPORT`, `Support technique`],
  [`ROLE.ADMIN`, `Administrateur`],
  [`ROLE.SUPER_ADMIN`, `Super Administrateur`],
  [`JOB_TYPE.FULL_TIME`, `Temps plein`],
  [`JOB_TYPE.PART_TIME`, `Temps partiel`],
  [`JOB_TYPE.CONTRACT`, `Contrat`],
  [`JOB_TYPE.TEMPORARY`, `Temporaire`],
  [`JOB_TYPE.INTERN`, `Stagiaire`],
  [`JOB_TYPE.VOLUNTEER`, `Bénévole`],
  [`JOB_TYPE.FREELANCE`, `Freelance`],
  [`JOB_TYPE.STARTUP`, `Startup`],
  [`JOB_TYPE.OTHER`, `Autre`],
  [`JOB_SOURCE.JOB_BOARD`, `Site d'emploi`],
  [`JOB_SOURCE.COMPANY_WEBSITE`, `Site de l'entreprise`],
  [`JOB_SOURCE.RECOMMENDATION`, `Recommandation`],
  [`JOB_SOURCE.OTHER`, `Autre`],
  [`EXPERIENCE_LEVEL.INTERNSHIP`, `Stage`],
  [`EXPERIENCE_LEVEL.ENTRY_LEVEL`, `Débutant`],
  [`EXPERIENCE_LEVEL.JUNIOR`, `Junior`],
  [`EXPERIENCE_LEVEL.MID_LEVEL`, `Intermédiaire`],
  [`EXPERIENCE_LEVEL.SENIOR`, `Senior`],
  [`EXPERIENCE_LEVEL.EXECUTIVE`, `Cadre`],
  [`COMMON.APPLICATIONS`, `Applications`],
  [`DATES.JANUARY_SHORT`, `Janv`],
  [`DATES.FEBRUARY_SHORT`, `Févr`],
  [`DATES.MARCH_SHORT`, `Mars`],
  [`DATES.APRIL_SHORT`, `Avr`],
  [`DATES.MAY_SHORT`, `Mai`],
  [`DATES.JUNE_SHORT`, `Juin`],
  [`DATES.JULY_SHORT`, `Juil`],
  [`DATES.AUGUST_SHORT`, `Août`],
  [`DATES.SEPTEMBER_SHORT`, `Sept`],
  [`DATES.OCTOBER_SHORT`, `Oct`],
  [`DATES.NOVEMBER_SHORT`, `Nov`],
  [`DATES.DECEMBER_SHORT`, `Déc`],
  [`DATES.MONDAY_SHORT`, `Lun`],
  [`DATES.TUESDAY_SHORT`, `Mar`],
  [`DATES.WEDNESDAY_SHORT`, `Mer`],
  [`DATES.THURSDAY_SHORT`, `Jeu`],
  [`DATES.FRIDAY_SHORT`, `Ven`],
  [`DATES.SATURDAY_SHORT`, `Sam`],
  [`DATES.SUNDAY_SHORT`, `Dim`],
  [`ERROR.USER_NOT_FOUND`, `Utilisateur non trouvé`],
  [`COMMON.OK`, `Ok`],
  [`COMMON.USER_PREFERENCES`, `Préférences utilisateur`],
  [`ERROR.UPDATE_ONLY_OWN_SETTINGS`, `L'utilisateur ne peut mettre à jour que ses propres paramètres`],
  [`COMMON.FIRST_NAME`, `Prénom`],
  [`COMMON.LAST_NAME`, `Nom`],
  [`COMMON.LANGUAGE`, `Langue`],
  [`COMMON.TIME_ZONE`, `Fuseau horaire`],
  [`COMMON.COUNTRY`, `Pays`],
  [`COMMON.APPLICATION_AI_TEXTAREA`, `Zone de texte IA de l'application`],
  [`WORK_ARRANGEMENT.SHIFT_BASED`, `Por turnos`],
  [`MESSAGES.CHANGES_SUCCESSFULLY_SAVED`, `Les modifications ont été enregistrées avec succès`],
  [`INPUT.TO_MANY_ITEMS.START_TYPING`, `Trop d'éléments. Veuillez commencer à taper`],
  [`ERROR.INVALID_URL`, `Format d'URL invalide`],
  [`ERROR.URL_NOT_HTTPS`, `L'URL n'utilise pas HTTPS`],
  [`ERROR.UNKNOWN_URL_TYPE`, `L'URL est sûre mais ne correspond pas à un modèle de nom d'utilisateur connu`],
  [`COMMON.PHONE`, `Téléphone`],
  [`SKILL_LEVEL.BEGINNER`, `Débutant`],
  [`SKILL_LEVEL.BASIC`, `Basique`],
  [`SKILL_LEVEL.INTERMEDIATE`, `Intermédiaire`],
  [`SKILL_LEVEL.ADVANCED`, `Avancé`],
  [`SKILL_LEVEL.EXPERT`, `Expert`],
  [`SKILL_LEVEL.MASTER`, `Maître`],
  [`SKILL_LEVEL.WORLD_CLASS`, `De classe mondiale`],
  [`WORK_ARRANGEMENT.ON_SITE`, `Sur site`],
  [`WORK_ARRANGEMENT.REMOTE`, `À distance`],
  [`WORK_ARRANGEMENT.HYBRID`, `Hybride`],
  [`WORK_ARRANGEMENT.FLEXIBLE`, `Flexible`],
  [`WORK_ARRANGEMENT.TRAVEL_REQUIRED`, `Voyage requis`],
  [`WORK_ARRANGEMENT.SHIFT_BASED`, `Basé sur les quarts`],
]);
