// Auto-generated file from a4-localizations_ua.csv

export const localization_ua: Map<string, string> = new Map<string, string>([
  [`AUTH.GREETINGS`, `Привіт, Хонклер!`],
  [`AUTH.SIGN_IN.JOKE`, `Можливо, нам потрібно повернутися до`],
  [`COMMON.LOGIN_OR_EMAIL`, `Логін або електронна пошта`],
  [`COMMON.PASSWORD`, `Пароль`],
  [`COMMON.CONFIRM_PASSWORD`, `Підтвердіть пароль`],
  [`COMMON.REMEMBER_ME`, `Запамятати мене`],
  [`COMMON.FORGOT`, `Забули пароль`],
  [`COMMON.SIGN_IN`, `Увійти`],
  [`COMMON.SIGN_UP`, `Зареєструватися`],
  [`AUTH.NO_ACCOUNT.SIGN_UP`, `Немає облікового запису? Зареєструйтеся`],
  [`AUTH.HAS_ACCOUNT.SIGN_IN`, `Вже маєте обліковий запис? Увійдіть`],
  [`COMMON.LOGIN`, `Логін`],
  [`COMMON.EMAIL`, `Електронна пошта`],
  [`COMMON.CONFIRM_EMAIL`, `Підтвердити електронну пошту`],
  [`COMMON.PROCEED`, `Продовжити`],
  [`COMMON.FIRST_NAME`, `Ім'я`],
  [`COMMON.LAST_NAME`, `Прізвище`],
  [`COMMON.NO_COMPLAINTS`, `Немає скарг`],
  [`COMMON.WE_ARE_HONKING`, `Ми сигналимо з 2024 року!`],
  [`COMMON.DO_NOT_STORE_SENS_DATA`, `НЕ ЗБЕРІГАЙТЕ ЖОДНИХ КОНФІДЕНЦІЙНИХ ДАНИХ!`],
  [`COMMON.LIGHT_THEME`, `Світла тема`],
  [`COMMON.DARK_THEME`, `Темна тема`],
  [`ERROR.PASSWORDS_DO_NOT_MATCH`, `Паролі не співпадають`],
  [`ERROR.EMAILS_DO_NOT_MATCH`, `Електронні адреси не співпадають`],
  [`ERROR.FIELD_REQUIRED`, `Поле є обов’язковим!`],
  [`ERROR.CHECK_CHECKBOX`, `Будь ласка, відмітьте поле!`],
  [`ERROR.INVALID_EMAIL`, `Невірний формат електронної пошти!`],
  [`MENU.HOME`, `Головна`],
  [`MENU.JOBS`, `Робота`],
  [`MENU.COMPANIES`, `Компанії`],
  [`MENU.KARMA`, `Карма`],
  [`COMMON.WELCOME_BACK`, `Ласкаво просимо`],
  [`MENU.ACTIVE_APPLICATIONS`, `Активні заявки`],
  [`MENU.TODOS`, `Завдання`],
  [`MENU.RESPONSE_RATE`, `Рівень відгуку`],
  [`MENU.UPCOMING_INTERVIEWS`, `Майбутні співбесіди`],
  [`COMMON.NEW_APPLICATION`, `Нова заявка`],
  [`STATS.JOB_APPLICATIONS_TREND`, `Тенденція заявок`],
  [`STATS.TOP_COMPANIES`, `Найкращі компанії (Заявки)`],
  [`STATS.NEW_JOB_LISTINGS_PER_DAY`, `Нові вакансії за день`],
  [`STATS.APPLICATION_STATUS_DISTRIBUTION`, `Розподіл статусу заявок`],
  [`STATUS.APPLIED`, `Подано`],
  [`STATUS.REJECTED`, `Відхилено`],
  [`STATUS.OFFER`, `Пропозиція`],
  [`STATUS.INTERVIEW`, `Співбесіда`],
  [`STATUS.IN_REVIEW`, `На розгляді`],
  [`COMMON.CREATE`, `Створити`],
  [`COMMON.EDIT`, `Редагувати`],
  [`COMMON.APPLICATION_LINK`, `Посилання на заявку`],
  [`COMMON.JOB_TITLE`, `Назва вакансії`],
  [`COMMON.COMPANY`, `Компанія`],
  [`COMMON.LOCATION`, `Місцезнаходження`],
  [`COMMON.EXPERIENCE_LEVEL`, `Рівень досвіду`],
  [`COMMON.JOB_TYPE`, `Тип роботи`],
  [`COMMON.SOURCE`, `Джерело`],
  [`COMMON.SALARY_RANGE`, `Діапазон зарплат`],
  [`COMMON.FROM`, `Від`],
  [`COMMON.TO`, `До`],
  [`COMMON.CURRENCY`, `Валюта`],
  [`COMMON.POSTED_DATE`, `Дата публікації`],
  [`COMMON.APPLICATION_DEADLINE`, `Кінцевий термін подачі заявки`],
  [`COMMON.Contact_EMAIL`, `Контактний Email`],
  [`COMMON.DESCRIPTION`, `Опис`],
  [`COMMON.NOTES`, `Примітки`],
  [`COMMON.CANCEL`, `Скасувати`],
  [`COMMON.UPDATE`, `Оновити`],
  [`COMMON.EDIT_PROFILE`, `Редагувати профіль`],
  [`COMMON.EDIT_SKILLS`, `Редагувати навички`],
  [`COMMON.ADD_EXPERIENCE`, `Додати досвід`],
  [`COMMON.SKILLS`, `Навички`],
  [`COMMON.EXPERIENCE`, `Досвід`],
  [`COMMON.EDUCATION`, `Освіта`],
  [`COMMON.CERTIFICATIONS`, `Сертифікації`],
  [`ROLE.USER`, `Користувач`],
  [`ROLE.TECHNICAL_SUPPORT`, `Технічна підтримка`],
  [`ROLE.ADMIN`, `Адміністратор`],
  [`ROLE.SUPER_ADMIN`, `Супер Адміністратор`],
  [`JOB_TYPE.FULL_TIME`, `Повний робочий день`],
  [`JOB_TYPE.PART_TIME`, `Неповний робочий день`],
  [`JOB_TYPE.CONTRACT`, `Контракт`],
  [`JOB_TYPE.TEMPORARY`, `Тимчасова робота`],
  [`JOB_TYPE.INTERN`, `Стажування`],
  [`JOB_TYPE.VOLUNTEER`, `Волонтерство`],
  [`JOB_TYPE.FREELANCE`, `Фріланс`],
  [`JOB_TYPE.STARTUP`, `Стартап`],
  [`JOB_TYPE.OTHER`, `Інше`],
  [`JOB_SOURCE.JOB_BOARD`, `Дошка вакансій`],
  [`JOB_SOURCE.COMPANY_WEBSITE`, `Веб-сайт компанії`],
  [`JOB_SOURCE.RECOMMENDATION`, `Рекомендація`],
  [`JOB_SOURCE.OTHER`, `Інше`],
  [`EXPERIENCE_LEVEL.INTERNSHIP`, `Стажування`],
  [`EXPERIENCE_LEVEL.ENTRY_LEVEL`, `Початковий рівень`],
  [`EXPERIENCE_LEVEL.JUNIOR`, `Молодший`],
  [`EXPERIENCE_LEVEL.MID_LEVEL`, `Середній рівень`],
  [`EXPERIENCE_LEVEL.SENIOR`, `Старший`],
  [`EXPERIENCE_LEVEL.EXECUTIVE`, `Керівник`],
  [`COMMON.APPLICATIONS`, `Аплікації`],
  [`DATES.JANUARY_SHORT`, `Січ`],
  [`DATES.FEBRUARY_SHORT`, `Лют`],
  [`DATES.MARCH_SHORT`, `Бер`],
  [`DATES.APRIL_SHORT`, `Кві`],
  [`DATES.MAY_SHORT`, `Тра`],
  [`DATES.JUNE_SHORT`, `Чер`],
  [`DATES.JULY_SHORT`, `Лип`],
  [`DATES.AUGUST_SHORT`, `Сер`],
  [`DATES.SEPTEMBER_SHORT`, `Вер`],
  [`DATES.OCTOBER_SHORT`, `Жов`],
  [`DATES.NOVEMBER_SHORT`, `Лис`],
  [`DATES.DECEMBER_SHORT`, `Гру`],
  [`DATES.MONDAY_SHORT`, `Пн`],
  [`DATES.TUESDAY_SHORT`, `Вт`],
  [`DATES.WEDNESDAY_SHORT`, `Ср`],
  [`DATES.THURSDAY_SHORT`, `Чт`],
  [`DATES.FRIDAY_SHORT`, `Пт`],
  [`DATES.SATURDAY_SHORT`, `Сб`],
  [`DATES.SUNDAY_SHORT`, `Нд`],
  [`ERROR.USER_NOT_FOUND`, `Користувача не знайдено`],
  [`COMMON.OK`, `Ок`],
  [`COMMON.USER_PREFERENCES`, `Налаштування користувача`],
  [`ERROR.UPDATE_ONLY_OWN_SETTINGS`, `Користувач може змінювати лише свої налаштування`],
  [`COMMON.FIRST_NAME`, `Ім'я`],
  [`COMMON.LAST_NAME`, `Прізвище`],
  [`COMMON.LANGUAGE`, `Мова`],
  [`COMMON.TIME_ZONE`, `Часовий пояс`],
  [`COMMON.COUNTRY`, `Країна`],
  [`COMMON.APPLICATION_AI_TEXTAREA`, `Текстова область AI додатку`],
  [`MESSAGES.CHANGES_SUCCESSFULLY_SAVED`, `Зміни успішно збережено`],
  [`INPUT.TO_MANY_ITEMS.START_TYPING`, `Забагато елементів. Почніть вводити текст`],
  [`ERROR.INVALID_URL`, `Невірний формат URL`],
  [`ERROR.URL_NOT_HTTPS`, `URL не використовує HTTPS`],
  [`ERROR.UNKNOWN_URL_TYPE`, `URL безпечний, але не відповідає відомому шаблону імені користувача`],
  [`COMMON.PHONE`, `Телефон`],
  [`SKILL_LEVEL.BEGINNER`, `Початківець`],
  [`SKILL_LEVEL.BASIC`, `Базовий`],
  [`SKILL_LEVEL.INTERMEDIATE`, `Середній`],
  [`SKILL_LEVEL.ADVANCED`, `Просунутий`],
  [`SKILL_LEVEL.EXPERT`, `Експерт`],
  [`SKILL_LEVEL.MASTER`, `Майстер`],
  [`SKILL_LEVEL.WORLD_CLASS`, `Світового класу`],
  [`WORK_ARRANGEMENT.ON_SITE`, `На місці`],
  [`WORK_ARRANGEMENT.REMOTE`, `Віддалено`],
  [`WORK_ARRANGEMENT.HYBRID`, `Гібридний`],
  [`WORK_ARRANGEMENT.FLEXIBLE`, `Гнучкий`],
  [`WORK_ARRANGEMENT.TRAVEL_REQUIRED`, `Потрібні поїздки`],
  [`WORK_ARRANGEMENT.SHIFT_BASED`, `Позмінний графік`],
]);
