// Auto-generated file from a5-localizations_ru.csv

export const localization_ru: Map<string, string> = new Map<string, string>([
  ['AUTH.GREETINGS', 'Приветствуем тебя, Honkler!'],
  ['AUTH.SIGN_IN.JOKE', 'Может быть, нам нужно вернуться к'],
  ['AUTH.NO_ACCOUNT_SIGN_UP', 'Нет аккаунта? Зарегистрируйтесь сейчас!'],
  ['AUTH.HAS_ACCOUNT_SIGN_IN', 'Уже есть аккаунт? Войдите сейчас!'],
  ['COMMON.FIX_ERROR_BEFORE_CONTINUE', 'Пожалуйста, исправьте ошибку перед продолжением.'],
  ['COMMON.WE_ARE_HONKING', 'Мы honk\'аем с 2025 года!'],
  ['COMMON.BUTTON.OK', 'OK'],
  ['COMMON.BUTTON.CANCEL', 'Отмена'],
  ['COMMON.BUTTON.PROCEED', 'Продолжить'],
  ['COMMON.BUTTON.SAVE', 'Сохранить'],
  ['COMMON.BUTTON.UPDATE', 'Обновить'],
  ['COMMON.BUTTON.HONK', 'Honk'],
  ['COMMON.BUTTON.ADD', 'Добавить'],
  ['COMMON.BUTTON.REMOVE', 'Удалить'],
  ['COMMON.BUTTON.EDIT', 'Редактировать'],
  ['COMMON.BUTTON.CREATE', 'Создать'],
  ['COMMON.BUTTON.RESET', 'Сбросить'],
  ['AUTH.SIGN_IN.LOGIN_OR_EMAIL', 'Логин или email'],
  ['COMMON.PASSWORD', 'Пароль'],
  ['AUTH.SIGN_IN.REMEMBER_ME', 'Запомнить меня'],
  ['AUTH.FORGOT', 'Забыли?'],
  ['AUTH.SIGN_IN.SIGN_IN', 'Войти'],
  ['COMMON.EMAIL', 'Email'],
  ['COMMON.LOGIN', 'Логин'],
  ['AUTH.SIGN_UP.WELCOME', 'Добро пожаловать в сообщество Honkler!'],
  ['COMMON.FIRST_NAME', 'Имя'],
  ['COMMON.LAST_NAME', 'Фамилия'],
  ['COMMON.CONFIRM_EMAIL', 'Подтвердите email'],
  ['COMMON.CONFIRM_PASSWORD', 'Подтвердите пароль'],
  ['COMMON.NO_COMPLAINTS', 'Нет жалоб'],
  ['COMMON.SIGN_UP', 'Зарегистрироваться'],
  ['PROFILE.EDUCATION.FIELD_OF_STUDY', 'Специальность'],
  ['PROFILE.EDUCATION.INSTITUTION', 'Учебное заведение'],
  ['COMMON.DO_NOT_STORE_ANY_SENSITIVE_DATA', 'Не храните конфиденциальные данные'],
  ['COMMON.START_DATE', 'Дата начала'],
  ['COMMON.END_DATE', 'Дата окончания'],
  ['COMMON.ISSUE_DATE', 'Дата выдачи'],
  ['COMMON.EXPIRATION_DATE', 'Срок действия'],
  ['PROFILE.CERTIFICATION.CERTIFICATION', 'Сертификат'],
  ['PROFILE.CERTIFICATION.ISSUER', 'Выдающая организация'],
  ['PROFILE.PROJECT.PROJECT', 'Проект'],
  ['PROFILE.COMPANY.COMPANY', 'Компания'],
  ['PROFILE.ACHIEVEMENT.ACHIEVEMENT', 'Достижение'],
  ['COMMON.POSITION', 'Должность'],
  ['COMMON.LOCATION', 'Местоположение'],
  ['COMMON.COUNTRY', 'Страна'],
  ['JOB_TYPE.JOB_TYPE', 'Тип работы'],
  ['JOB_TYPE.FULL_TIME', 'Полный рабочий день'],
  ['JOB_TYPE.PART_TIME', 'Неполный рабочий день'],
  ['JOB_TYPE.CONTRACT', 'Контракт'],
  ['JOB_TYPE.TEMPORARY', 'Временная'],
  ['JOB_TYPE.INTERN', 'Стажировка'],
  ['JOB_TYPE.VOLUNTEER', 'Волонтерство'],
  ['JOB_TYPE.FREELANCE', 'Фриланс'],
  ['JOB_TYPE.STARTUP', 'Стартап'],
  ['JOB_TYPE.OTHER', 'Другое'],
  ['JOB_TYPE.DISTANCE', 'Дистанционно'],
  ['JOB_TYPE.EVENING', 'Вечерняя'],
  ['JOB_TYPE.ONLINE', 'Онлайн'],
  ['JOB_TYPE.MIXED', 'Смешанная'],
  ['JOB_TYPE.EXCHANGE', 'Обмен'],
  ['JOB_TYPE.SELF_PACED', 'По собственному графику'],
  ['JOB_TYPE.IN_PERSON', 'Лично'],
  ['JOB_TYPE.HYBRID', 'Гибридная'],
  ['JOB_TYPE.PROCTORED_ONLINE', 'Онлайн с прокторингом'],
  ['JOB_TYPE.UNPROCTORED', 'Без прокторинга'],
  ['WORK_ARRANGEMENT.WORK_ARRANGEMENT', 'Формат работы'],
  ['WORK_ARRANGEMENT.ON_SITE', 'В офисе'],
  ['WORK_ARRANGEMENT.REMOTE', 'Удаленно'],
  ['WORK_ARRANGEMENT.HYBRID', 'Гибридная'],
  ['WORK_ARRANGEMENT.FLEXIBLE', 'Гибкая'],
  ['WORK_ARRANGEMENT.TRAVEL_REQUIRED', 'С переездами'],
  ['WORK_ARRANGEMENT.SHIFT_BASED', 'Сменная'],
  ['COMMON.DESCRIPTION', 'Описание'],
  ['COMMON.SALARY_RANGE', 'Диапазон зарплаты'],
  ['COMMON.FROM', 'От'],
  ['COMMON.TO', 'До'],
  ['COMMON.SKILLS', 'Навыки'],
  ['COMMON.SKILL', 'Навык'],
  ['EXPERIENCE_LEVEL.EXPERIENCE_LEVEL', 'Уровень опыта'],
  ['EXPERIENCE_LEVEL.INTERNSHIP', 'Стажировка'],
  ['EXPERIENCE_LEVEL.ENTRY_LEVEL', 'Начальный уровень'],
  ['EXPERIENCE_LEVEL.JUNIOR', 'Младший специалист'],
  ['EXPERIENCE_LEVEL.MID_LEVEL', 'Средний уровень'],
  ['EXPERIENCE_LEVEL.SENIOR', 'Старший специалист'],
  ['EXPERIENCE_LEVEL.LEADER', 'Ведущий специалист'],
  ['EXPERIENCE_LEVEL.EXECUTIVE', 'Руководитель'],
  ['EXPERIENCE_LEVEL.PRINCIPAL', 'Главный специалист'],
  ['EXPERIENCE_LEVEL.STAFF', 'Персонал'],
  ['EXPERIENCE_LEVEL.OTHER', 'Другое'],
  ['EXPERIENCE_LEVEL.TIER_1', 'Уровень 1'],
  ['EXPERIENCE_LEVEL.TIER_2', 'Уровень 2'],
  ['EXPERIENCE_LEVEL.TIER_3', 'Уровень 3'],
  ['EXPERIENCE_LEVEL.TIER_4', 'Уровень 4'],
  ['EXPERIENCE_LEVEL.TIER_5', 'Уровень 5'],
  ['EXPERIENCE_LEVEL.TIER_6', 'Уровень 6'],
  ['EXPERIENCE_LEVEL.TIER_7', 'Уровень 7'],
  ['COMMON.LANGUAGES', 'Языки'],
  ['COMMON.LANGUAGE', 'Язык'],
  ['LANGUAGE_LEVEL.LANGUAGE_LEVEL', 'Уровень языка'],
  ['LANGUAGE_LEVEL.BEGINNER', 'Начинающий'],
  ['LANGUAGE_LEVEL.ELEMENTARY', 'Элементарный'],
  ['LANGUAGE_LEVEL.INTERMEDIATE', 'Средний'],
  ['LANGUAGE_LEVEL.UPPER_INTERMEDIATE', 'Выше среднего'],
  ['LANGUAGE_LEVEL.ADVANCED', 'Продвинутый'],
  ['LANGUAGE_LEVEL.PROFICIENT', 'Свободный'],
  ['LANGUAGE_LEVEL.NATIVE', 'Родной'],
  ['PROFILE.SECTION.PRIMARY_INFO', 'Основная информация'],
  ['PROFILE.SECTION.AUTH_SECTION', 'Раздел авторизации'],
  ['PROFILE.HEADLINE', 'Заголовок'],
  ['PROFILE.SECTION.SECONDARY_INFO', 'Дополнительная информация'],
  ['COMMON.CURRENCY', 'Валюта'],
  ['COMMON.TIME_ZONE', 'Часовой пояс'],
  ['COMMON.PHONE', 'Телефон'],
  ['PROFILE.LINKS', 'Ссылки'],
  ['PROFILE.SECTION.AI', 'ИИ'],
  ['PROFILE.APPLICATION.AI_TEXTAREA', 'Текстовое поле ИИ для заявки'],
  ['THEME.DARK', 'Темная тема'],
  ['THEME.LIGHT', 'Светлая тема'],
  ['MENU.HOME', 'Главная'],
  ['MENU.JOBS', 'Вакансии'],
  ['MENU.COMPANIES', 'Компании'],
  ['MENU.KARMA', 'Карма'],
  ['IN_DEVELOPMENT.OOPS_PAGE', 'Упс! Страница в разработке.'],
  ['COMMON.GO_HOME', 'На главную'],
  ['COMMON.BACK_TO_SIGN_IN', 'Вернуться к входу'],
  ['NOT_FOUND.PAGE_NOT_FOUND', 'Упс! Страница, которую вы ищете, не существует.'],
  ['MENU.ACTIVE_APPLICATIONS', 'Активные заявки'],
  ['MENU.TODOS', 'Задачи'],
  ['MENU.RESPONSE_RATE', 'Частота ответов'],
  ['MENU.UPCOMING_INTERVIEWS', 'Предстоящие собеседования'],
  ['STATS.NEW_JOB_LISTINGS_PER_DAY', 'Новые вакансии за день'],
  ['STATS.JOB_APPLICATIONS_TREND', 'Тенденция заявок'],
  ['COMMON.JOB.NEW_APPLICATION', 'Заявка на работу'],
  ['COMMON.JOB.NEW_APPLICATIONS', 'Заявки на работу'],
  ['STATS.TOP_COMPANIES', 'Топ компаний'],
  ['STATS.APPLICATION_STATUS_DISTRIBUTION', 'Распределение статусов заявок'],
  ['JOB_STATUS.APPLIED', 'Подано'],
  ['JOB_STATUS.IN_REVIEW', 'На рассмотрении'],
  ['JOB_STATUS.INTERVIEW', 'Собеседование'],
  ['JOB_STATUS.OFFER', 'Предложение'],
  ['JOB_STATUS.REJECTED', 'Отклонено'],
  ['COMMON.WELCOME_BACK', 'С возвращением'],
  ['PROFILE.SECTION.WORK_EXPERIENCE', 'Опыт работы'],
  ['PROFILE.SECTION.EDUCATION', 'Образование'],
  ['PROFILE.SECTION.PROJECTS', 'Проекты'],
  ['PROFILE.SECTION.ACHIEVEMENTS', 'Достижения'],
  ['PROFILE.SECTION.CERTIFICATIONS', 'Сертификаты'],
  ['COMMON.EMPTY_SECTION', 'Пустой раздел'],
  ['PROFILE.USER_PREFERENCES', 'Настройки пользователя'],
  ['ERROR.NOT_FOUND', 'Не найдено'],
  ['ERROR.ENTITY_NOT_FOUND', 'Объект не найден'],
  ['ERROR.ENTITY_WITH_ID_NOT_FOUND', 'Объект с ID не найден'],
  ['ERROR.ENTITY_WITH_EMAIL_ALREADY_EXISTS', 'Объект с таким email уже существует'],
  ['ERROR.ENTITY_WITH_LOGIN_ALREADY_EXISTS', 'Объект с таким логином уже существует'],
  ['ERROR.VALIDATION_ERROR', 'Ошибка валидации'],
  ['ERROR.ENTITY_ALREADY_EXISTS', 'Объект уже существует'],
  ['ERROR.ALREADY_EXISTS', 'Уже существует'],
  ['ERROR.INTERNAL_SERVER_ERROR', 'Внутренняя ошибка сервера'],
  ['ERROR.BLOCKED', 'Заблокировано'],
  ['ERROR.RESOURCE_NOT_FOUND', 'Ресурс не найден'],
  ['ERROR.ENTITY_BLOCKED', 'Объект заблокирован'],
  ['ERROR.ENTITY_PESSIMISTIC_LOCKED', 'Объект заблокирован'],
  ['ERROR.WRONG_AUTH', 'Неправильная аутентификация'],
  ['ERROR.FORBIDDEN', 'Запрещено'],
  ['ERROR.USER_BLOCKED', 'Пользователь заблокирован'],
  ['ERROR.POTENTIAL_HARMFUL_CONTENT', 'Потенциально вредоносный контент'],
  ['ERROR.JWT_MIN_LENGTH', 'Минимальная длина JWT'],
  ['ERROR.JWT_INVALID_FORMAT', 'Неправильный формат JWT'],
  ['ERROR.JWT_USER_CLAIM_NOT_FOUND', 'Клейм пользователя JWT не найден'],
  ['ERROR.JWT_USER_CLAIM_INVALID_CONVERSION', 'Неправильное преобразование клейма пользователя JWT'],
  ['ERROR.FORGOT_PASSWORD_REQUEST_TOO_SOON', 'Запрос на восстановление пароля слишком рано'],
  ['ERROR.RESTORE_PASSWORD_PROCESSING_ISSUE', 'Проблема с обработкой восстановления пароля'],
  ['ERROR.VERSION_NOT_SPECIFIED', 'Версия не указана'],
  ['ERROR.VERSION_NOT_SUPPORTED', 'Версия не поддерживается'],
  ['ERROR.UPDATE_ONLY_OWN_SETTINGS', 'Обновляйте только свои настройки'],
  ['ERROR.INVALID_URL', 'Неправильный URL'],
  ['ERROR.URL_NOT_HTTPS', 'URL не HTTPS'],
  ['ERROR.UNKNOWN_URL_TYPE', 'Неизвестный тип URL'],
  ['ENTITY.STATUS.NEW', 'Новый'],
  ['ENTITY.STATUS.ACTIVE', 'Активный'],
  ['ENTITY.STATUS.INACTIVE', 'Неактивный'],
  ['ENTITY.STATUS.BLOCKED', 'Заблокированный'],
  ['ENTITY.STATUS.DELETED', 'Удаленный'],
  ['ENTITY.STATUS.PENDING', 'В ожидании'],
  ['ENTITY.STATUS.APPROVED', 'Одобрено'],
  ['ENTITY.STATUS.REJECTED', 'Отклонено'],
  ['ENTITY.STATUS.COMPLETED', 'Завершено'],
  ['ENTITY.STATUS.CANCELLED', 'Отменено'],
  ['ENTITY.STATUS.ARCHIVED', 'Архивировано'],
  ['MESSAGES.CHANGES_SUCCESSFULLY_SAVED', 'Изменения успешно сохранены'],
  ['DATES.JANUARY_SHORT', 'Янв'],
  ['DATES.FEBRUARY_SHORT', 'Фев'],
  ['DATES.MARCH_SHORT', 'Мар'],
  ['DATES.APRIL_SHORT', 'Апр'],
  ['DATES.MAY_SHORT', 'Май'],
  ['DATES.JUNE_SHORT', 'Июн'],
  ['DATES.JULY_SHORT', 'Июл'],
  ['DATES.AUGUST_SHORT', 'Авг'],
  ['DATES.SEPTEMBER_SHORT', 'Сен'],
  ['DATES.OCTOBER_SHORT', 'Окт'],
  ['DATES.NOVEMBER_SHORT', 'Ноя'],
  ['DATES.DECEMBER_SHORT', 'Дек'],
  ['DATES.MONDAY_SHORT', 'Пн'],
  ['DATES.TUESDAY_SHORT', 'Вт'],
  ['DATES.WEDNESDAY_SHORT', 'Ср'],
  ['DATES.THURSDAY_SHORT', 'Чт'],
  ['DATES.FRIDAY_SHORT', 'Пт'],
  ['DATES.SATURDAY_SHORT', 'Сб'],
  ['DATES.SUNDAY_SHORT', 'Вс'],
  ['INPUT.TOO_MANY_ITEMS_START_TYPING', 'Слишком много элементов, начните вводить...'],
  ['ERROR.FIELD_REQUIRED', 'Поле обязательно'],
  ['ERROR.CHECK_CHECKBOX', 'Отметьте чекбокс'],
  ['ERROR.INVALID_EMAIL', 'Неправильный email'],
  ['JOB_SOURCE.JOB_BOARD', 'Доска вакансий'],
  ['JOB_SOURCE.COMPANY_WEBSITE', 'Сайт компании'],
  ['JOB_SOURCE.RECOMMENDATION', 'Рекомендация'],
  ['JOB_SOURCE.SOCIAL_MEDIA', 'Социальные сети'],
  ['JOB_SOURCE.OTHER', 'Другое'],
  ['ROLE.ROLE', 'Роль'],
  ['ROLE.USER', 'Пользователь'],
  ['ROLE.TECHNICAL_SUPPORT', 'Техническая поддержка'],
  ['ROLE.ADMIN', 'Администратор'],
  ['ROLE.SUPER_ADMIN', 'Супер администратор'],
]);
