// Auto-generated file from a1-localizations_en.csv

export const localization_en: Map<string, string> = new Map<string, string>([
  ['AUTH.GREETINGS', 'Greetings fellow, Honkler!'],
  ['AUTH.SIGN_IN.JOKE', 'Maybe we need back to'],
  ['AUTH.NO_ACCOUNT_SIGN_UP', 'Don\'t have an account? Sign up now!'],
  ['AUTH.HAS_ACCOUNT_SIGN_IN', 'Already have an account? Sign in now!'],
  ['COMMON.FIX_ERROR_BEFORE_CONTINUE', 'Please fix the error before continuing.'],
  ['COMMON.WE_ARE_HONKING', 'We are honking since 2024!'],
  ['COMMON.BUTTON.OK', 'OK'],
  ['COMMON.BUTTON.CANCEL', 'Cancel'],
  ['COMMON.BUTTON.PROCEED', 'Proceed'],
  ['COMMON.BUTTON.SAVE', 'Save'],
  ['COMMON.BUTTON.UPDATE', 'Update'],
  ['COMMON.BUTTON.HONK', 'Honk'],
  ['COMMON.BUTTON.ADD', 'Add'],
  ['COMMON.BUTTON.REMOVE', 'Remove'],
  ['COMMON.BUTTON.EDIT', 'Edit'],
  ['COMMON.BUTTON.CREATE', 'Create'],
  ['COMMON.BUTTON.RESET', 'Reset'],
  ['AUTH.SIGN_IN.LOGIN_OR_EMAIL', 'Login or email'],
  ['COMMON.PASSWORD', 'Password'],
  ['AUTH.SIGN_IN.REMEMBER_ME', 'Remember me'],
  ['AUTH.FORGOT', 'Forgot?'],
  ['AUTH.SIGN_IN.SIGN_IN', 'Sign in'],
  ['COMMON.EMAIL', 'Email'],
  ['COMMON.LOGIN', 'Login'],
  ['AUTH.SIGN_UP.WELCOME', 'Welcome to the Honkler community!'],
  ['COMMON.FIRST_NAME', 'First name'],
  ['COMMON.LAST_NAME', 'Last name'],
  ['COMMON.CONFIRM_EMAIL', 'Confirm email'],
  ['COMMON.CONFIRM_PASSWORD', 'Confirm password'],
  ['COMMON.NO_COMPLAINTS', 'No complaints'],
  ['COMMON.SIGN_UP', 'Sign up'],
  ['PROFILE.EDUCATION.FIELD_OF_STUDY', 'Field of study'],
  ['PROFILE.EDUCATION.INSTITUTION', 'Institution'],
  ['COMMON.DO_NOT_STORE_ANY_SENSITIVE_DATA', 'Do not store any sensitive data'],
  ['COMMON.START_DATE', 'Start date'],
  ['COMMON.END_DATE', 'End date'],
  ['COMMON.ISSUE_DATE', 'Issue date'],
  ['COMMON.EXPIRATION_DATE', 'Expiration date'],
  ['PROFILE.CERTIFICATION.CERTIFICATION', 'Certification'],
  ['PROFILE.CERTIFICATION.ISSUER', 'Issuer'],
  ['PROFILE.PROJECT.PROJECT', 'Project'],
  ['PROFILE.COMPANY.COMPANY', 'Company'],
  ['PROFILE.ACHIEVEMENT.ACHIEVEMENT', 'Achievement'],
  ['COMMON.POSITION', 'Position'],
  ['COMMON.LOCATION', 'Location'],
  ['COMMON.COUNTRY', 'Country'],
  ['JOB_TYPE.JOB_TYPE', 'Job type'],
  ['JOB_TYPE.FULL_TIME', 'Full-time'],
  ['JOB_TYPE.PART_TIME', 'Part-time'],
  ['JOB_TYPE.CONTRACT', 'Contract'],
  ['JOB_TYPE.TEMPORARY', 'Temporary'],
  ['JOB_TYPE.INTERN', 'Intern'],
  ['JOB_TYPE.VOLUNTEER', 'Volunteer'],
  ['JOB_TYPE.FREELANCE', 'Freelance'],
  ['JOB_TYPE.STARTUP', 'Startup'],
  ['JOB_TYPE.OTHER', 'Other'],
  ['JOB_TYPE.DISTANCE', 'Distance'],
  ['JOB_TYPE.EVENING', 'Evening'],
  ['JOB_TYPE.ONLINE', 'Online'],
  ['JOB_TYPE.MIXED', 'Mixed'],
  ['JOB_TYPE.EXCHANGE', 'Exchange'],
  ['JOB_TYPE.SELF_PACED', 'Self-paced'],
  ['JOB_TYPE.IN_PERSON', 'In-person'],
  ['JOB_TYPE.HYBRID', 'Hybrid'],
  ['JOB_TYPE.PROCTORED_ONLINE', 'Proctored online'],
  ['JOB_TYPE.UNPROCTORED', 'Unproctored'],
  ['WORK_ARRANGEMENT.WORK_ARRANGEMENT', 'Work arrangement'],
  ['WORK_ARRANGEMENT.ON_SITE', 'On-site'],
  ['WORK_ARRANGEMENT.REMOTE', 'Remote'],
  ['WORK_ARRANGEMENT.HYBRID', 'Hybrid'],
  ['WORK_ARRANGEMENT.FLEXIBLE', 'Flexible'],
  ['WORK_ARRANGEMENT.TRAVEL_REQUIRED', 'Travel Required'],
  ['WORK_ARRANGEMENT.SHIFT_BASED', 'Shift-based'],
  ['COMMON.DESCRIPTION', 'Description'],
  ['COMMON.SALARY_RANGE', 'Salary range'],
  ['COMMON.FROM', 'From'],
  ['COMMON.TO', 'To'],
  ['COMMON.SKILLS', 'Skills'],
  ['COMMON.SKILL', 'Skill'],
  ['EXPERIENCE_LEVEL.EXPERIENCE_LEVEL', 'Experience level'],
  ['EXPERIENCE_LEVEL.INTERNSHIP', 'Internship'],
  ['EXPERIENCE_LEVEL.ENTRY_LEVEL', 'Entry Level'],
  ['EXPERIENCE_LEVEL.JUNIOR', 'Junior'],
  ['EXPERIENCE_LEVEL.MID_LEVEL', 'Mid Level'],
  ['EXPERIENCE_LEVEL.SENIOR', 'Senior'],
  ['EXPERIENCE_LEVEL.LEADER', 'Lead'],
  ['EXPERIENCE_LEVEL.EXECUTIVE', 'Executive'],
  ['EXPERIENCE_LEVEL.PRINCIPAL', 'Principal'],
  ['EXPERIENCE_LEVEL.STAFF', 'Staff'],
  ['EXPERIENCE_LEVEL.OTHER', 'Other'],
  ['EXPERIENCE_LEVEL.TIER_1', 'Tier 1'],
  ['EXPERIENCE_LEVEL.TIER_2', 'Tier 2'],
  ['EXPERIENCE_LEVEL.TIER_3', 'Tier 3'],
  ['EXPERIENCE_LEVEL.TIER_4', 'Tier 4'],
  ['EXPERIENCE_LEVEL.TIER_5', 'Tier 5'],
  ['EXPERIENCE_LEVEL.TIER_6', 'Tier 6'],
  ['EXPERIENCE_LEVEL.TIER_7', 'Tier 7'],
  ['COMMON.LANGUAGES', 'Languages'],
  ['COMMON.LANGUAGE', 'Language'],
  ['LANGUAGE_LEVEL.LANGUAGE_LEVEL', 'Language level'],
  ['LANGUAGE_LEVEL.BEGINNER', 'Beginner'],
  ['LANGUAGE_LEVEL.ELEMENTARY', 'Elementary'],
  ['LANGUAGE_LEVEL.INTERMEDIATE', 'Intermediate'],
  ['LANGUAGE_LEVEL.UPPER_INTERMEDIATE', 'Upper Intermediate'],
  ['LANGUAGE_LEVEL.ADVANCED', 'Advanced'],
  ['LANGUAGE_LEVEL.PROFICIENT', 'Proficient'],
  ['LANGUAGE_LEVEL.NATIVE', 'Native'],
  ['PROFILE.SECTION.PRIMARY_INFO', 'Primary info'],
  ['PROFILE.SECTION.AUTH_SECTION', 'Auth section'],
  ['PROFILE.HEADLINE', 'Headline'],
  ['PROFILE.SECTION.SECONDARY_INFO', 'Secondary info'],
  ['COMMON.CURRENCY', 'Currency'],
  ['COMMON.TIME_ZONE', 'Time zone'],
  ['COMMON.PHONE', 'Phone'],
  ['PROFILE.LINKS', 'Links'],
  ['PROFILE.SECTION.AI', 'AI'],
  ['PROFILE.APPLICATION.AI_TEXTAREA', 'Application AI textarea'],
  ['THEME.DARK', 'Dark Theme'],
  ['THEME.LIGHT', 'Light Theme'],
  ['MENU.HOME', 'Home'],
  ['MENU.JOBS', 'Jobs'],
  ['MENU.COMPANIES', 'Companies'],
  ['MENU.KARMA', 'Karma'],
  ['IN_DEVELOPMENT.OOPS_PAGE', 'Oops! Page under construction.'],
  ['COMMON.GO_HOME', 'Go home'],
  ['COMMON.BACK_TO_SIGN_IN', 'Back to sign in'],
  ['NOT_FOUND.PAGE_NOT_FOUND', 'Oops! The page you\'re looking for doesn\'t exist.'],
  ['MENU.ACTIVE_APPLICATIONS', 'Active applications'],
  ['MENU.TODOS', 'To-dos'],
  ['MENU.RESPONSE_RATE', 'Response rate'],
  ['MENU.UPCOMING_INTERVIEWS', 'Upcoming interviews'],
  ['MENU.PROFILE', 'Profile'],
  ['MENU.LOGOUT', 'Logout'],
  ['STATS.NEW_JOB_LISTINGS_PER_DAY', 'New job listings per day'],
  ['STATS.JOB_APPLICATIONS_TREND', 'Job applications trend'],
  ['COMMON.JOB.NEW_APPLICATION', 'Job application'],
  ['COMMON.JOB.NEW_APPLICATIONS', 'Job applications'],
  ['STATS.TOP_COMPANIES', 'Top companies'],
  ['STATS.APPLICATION_STATUS_DISTRIBUTION', 'Application status distribution'],
  ['JOB_STATUS.APPLIED', 'Applied'],
  ['JOB_STATUS.IN_REVIEW', 'In review'],
  ['JOB_STATUS.INTERVIEW', 'Interview'],
  ['JOB_STATUS.OFFER', 'Offer'],
  ['JOB_STATUS.REJECTED', 'Rejected'],
  ['COMMON.WELCOME_BACK', 'Welcome back'],
  ['PROFILE.SECTION.WORK_EXPERIENCE', 'Work experience'],
  ['PROFILE.SECTION.EDUCATION', 'Education'],
  ['PROFILE.SECTION.PROJECTS', 'Projects'],
  ['PROFILE.SECTION.ACHIEVEMENTS', 'Achievements'],
  ['PROFILE.SECTION.CERTIFICATIONS', 'Certifications'],
  ['COMMON.EMPTY_SECTION', 'Empty section'],
  ['PROFILE.USER_PREFERENCES', 'User preferences'],
  ['ERROR.NOT_FOUND', 'Not found'],
  ['ERROR.ENTITY_NOT_FOUND', 'Entity not found'],
  ['ERROR.ENTITY_WITH_ID_NOT_FOUND', 'Entity with ID not found'],
  ['ERROR.ENTITY_WITH_EMAIL_ALREADY_EXISTS', 'Entity with email already exists'],
  ['ERROR.ENTITY_WITH_LOGIN_ALREADY_EXISTS', 'Entity with login already exists'],
  ['ERROR.VALIDATION_ERROR', 'Validation error'],
  ['ERROR.ENTITY_ALREADY_EXISTS', 'Entity already exists'],
  ['ERROR.ALREADY_EXISTS', 'Already exists'],
  ['ERROR.INTERNAL_SERVER_ERROR', 'Internal server error'],
  ['ERROR.BLOCKED', 'Blocked'],
  ['ERROR.RESOURCE_NOT_FOUND', 'Resource not found'],
  ['ERROR.ENTITY_BLOCKED', 'Entity blocked'],
  ['ERROR.ENTITY_PESSIMISTIC_LOCKED', 'Entity is locked'],
  ['ERROR.WRONG_AUTH', 'Wrong authentication'],
  ['ERROR.FORBIDDEN', 'Forbidden'],
  ['ERROR.USER_BLOCKED', 'User blocked'],
  ['ERROR.POTENTIAL_HARMFUL_CONTENT', 'Potential harmful content'],
  ['ERROR.JWT_MIN_LENGTH', 'JWT min length'],
  ['ERROR.JWT_INVALID_FORMAT', 'JWT invalid format'],
  ['ERROR.JWT_USER_CLAIM_NOT_FOUND', 'JWT user claim not found'],
  ['ERROR.JWT_USER_CLAIM_INVALID_CONVERSION', 'JWT user claim invalid conversion'],
  ['ERROR.FORGOT_PASSWORD_REQUEST_TOO_SOON', 'Forgot password request too soon'],
  ['ERROR.RESTORE_PASSWORD_PROCESSING_ISSUE', 'Restore password processing issue'],
  ['ERROR.VERSION_NOT_SPECIFIED', 'Version not specified'],
  ['ERROR.VERSION_NOT_SUPPORTED', 'Version not supported'],
  ['ERROR.UPDATE_ONLY_OWN_SETTINGS', 'Update only own settings'],
  ['ERROR.INVALID_URL', 'Invalid URL'],
  ['ERROR.URL_NOT_HTTPS', 'URL not HTTPS'],
  ['ERROR.UNKNOWN_URL_TYPE', 'Unknown URL type'],
  ['ENTITY.STATUS.NEW', 'New'],
  ['ENTITY.STATUS.ACTIVE', 'Active'],
  ['ENTITY.STATUS.INACTIVE', 'Inactive'],
  ['ENTITY.STATUS.BLOCKED', 'Blocked'],
  ['ENTITY.STATUS.DELETED', 'Deleted'],
  ['ENTITY.STATUS.PENDING', 'Pending'],
  ['ENTITY.STATUS.APPROVED', 'Approved'],
  ['ENTITY.STATUS.REJECTED', 'Rejected'],
  ['ENTITY.STATUS.COMPLETED', 'Completed'],
  ['ENTITY.STATUS.CANCELLED', 'Cancelled'],
  ['ENTITY.STATUS.ARCHIVED', 'Archived'],
  ['MESSAGES.CHANGES_SUCCESSFULLY_SAVED', 'Changes successfully saved'],
  ['DATES.JANUARY_SHORT', 'Jan'],
  ['DATES.FEBRUARY_SHORT', 'Feb'],
  ['DATES.MARCH_SHORT', 'Mar'],
  ['DATES.APRIL_SHORT', 'Apr'],
  ['DATES.MAY_SHORT', 'May'],
  ['DATES.JUNE_SHORT', 'Jun'],
  ['DATES.JULY_SHORT', 'Jul'],
  ['DATES.AUGUST_SHORT', 'Aug'],
  ['DATES.SEPTEMBER_SHORT', 'Sep'],
  ['DATES.OCTOBER_SHORT', 'Oct'],
  ['DATES.NOVEMBER_SHORT', 'Nov'],
  ['DATES.DECEMBER_SHORT', 'Dec'],
  ['DATES.MONDAY_SHORT', 'Mon'],
  ['DATES.TUESDAY_SHORT', 'Tue'],
  ['DATES.WEDNESDAY_SHORT', 'Wed'],
  ['DATES.THURSDAY_SHORT', 'Thu'],
  ['DATES.FRIDAY_SHORT', 'Fri'],
  ['DATES.SATURDAY_SHORT', 'Sat'],
  ['DATES.SUNDAY_SHORT', 'Sun'],
  ['INPUT.TOO_MANY_ITEMS_START_TYPING', 'Too many items, start typing...'],
  ['ERROR.FIELD_REQUIRED', 'Field is required'],
  ['ERROR.CHECK_CHECKBOX', 'Check checkbox'],
  ['ERROR.INVALID_EMAIL', 'Invalid email'],
  ['JOB_SOURCE.JOB_BOARD', 'Job board'],
  ['JOB_SOURCE.COMPANY_WEBSITE', 'Company website'],
  ['JOB_SOURCE.RECOMMENDATION', 'Recommendation'],
  ['JOB_SOURCE.SOCIAL_MEDIA', 'Social media'],
  ['JOB_SOURCE.OTHER', 'Other'],
  ['ROLE.ROLE', 'Role'],
  ['ROLE.USER', 'User'],
  ['ROLE.TECHNICAL_SUPPORT', 'Technical support'],
  ['ROLE.ADMIN', 'Admin'],
  ['ROLE.SUPER_ADMIN', 'Super admin'],
  ['COMMON.JOB_TITLE', 'Job title'],
  ['COMMON.SOURCE', 'Source'],
  ['COMMON.POSTED_DATE', 'Posted date'],
  ['COMMON.DEADLINE', 'Deadline'],
  ['COMMON.CONTACT_EMAIL', 'Contact email'],
  ['APPLICATION.APPLICATION_LINK', 'Application link'],
  ['COMMON.NOTES', 'Notes'],
  ['SKILL_LEVEL.SKILL_LEVEL', 'Skill level'],
  ['SKILL_LEVEL.BEGINNER', 'Beginner'],
  ['SKILL_LEVEL.BASIC', 'Basic'],
  ['SKILL_LEVEL.INTERMEDIATE', 'Intermediate'],
  ['SKILL_LEVEL.ADVANCED', 'Advanced'],
  ['SKILL_LEVEL.EXPERT', 'Expert'],
  ['SKILL_LEVEL.MASTER', 'Master'],
  ['SKILL_LEVEL.WORLD_CLASS', 'World-Class'],
  ['PROFILE.SHOW_CURRENT_POSITION', 'Show current position'],
  ['PROFILE.SHOW_HIGHEST_EDUCATION', 'Show highest education'],
]);
