// Auto-generated file from a6-localizations_de.csv

export const localization_de: Map<string, string> = new Map<string, string>([
  ['AUTH.GREETINGS', 'Sei gegrüßt, Honkler!'],
  ['AUTH.SIGN_IN.JOKE', 'Vielleicht müssen wir zurück zu'],
  ['COMMON.LOGIN_OR_EMAIL', 'Anmeldung oder E-Mail'],
  ['COMMON.PASSWORD', 'Kennwort'],
  ['COMMON.CONFIRM_PASSWORD', 'Kennwort'],
  ['COMMON.REMEMBER_ME', 'Erinnern Sie sich an mich'],
  ['COMMON.FORGOT', 'Vergessen'],
  ['COMMON.SIGN_IN', 'Anmelden'],
  ['COMMON.SIGN_UP', 'Anmelden'],
  ['AUTH.NO_ACCOUNT.SIGN_UP', 'Sie haben noch kein Konto? Anmelden'],
  ['AUTH.HAS_ACCOUNT.SIGN_IN', 'Haben Sie bereits ein Konto? Anmelden'],
  ['COMMON.LOGIN', 'Anmeldung'],
  ['COMMON.EMAIL', 'E-Mail'],
  ['COMMON.CONFIRM_EMAIL', 'Bestätigen Sie Ihre E-Mail'],
  ['COMMON.PROCEED', 'Fortfahren'],
  ['COMMON.NO_COMPLAINTS', 'Keine Beschwerden'],
  ['COMMON.WE_ARE_HONKING', 'Wir hupen seit 2024!'],
  ['COMMON.DO_NOT_STORE_SENS_DATA', 'SPEICHERN SIE HIER KEINE SENSIBLEN DATEN!'],
  ['COMMON.LIGHT_THEME', 'Helles Thema'],
  ['COMMON.DARK_THEME', 'Dunkles Thema'],
  ['ERROR.VALIDATION.PASSWORDS_DO_NOT_MATCH', 'Passwörter stimmen nicht überein'],
  ['ERROR.VALIDATION.EMAILS_DO_NOT_MATCH', 'E-Mails stimmen nicht überein'],
  ['ERROR.VALIDATION.FIELD_REQUIRED', 'Das Feld ist erforderlich!'],
  ['ERROR.VALIDATION.CHECK_CHECKBOX', 'Bitte kreuzen Sie das Kästchen an!'],
  ['ERROR.VALIDATION.INVALID_EMAIL', 'Ungültiges E-Mail-Format!'],
  ['MENU.HOME', 'Startseite'],
  ['MENU.JOBS', 'Stellenangebote'],
  ['MENU.COMPANIES', 'Unternehmen'],
  ['MENU.KARMA', 'Karma'],
  ['COMMON.WELCOME_BACK', 'Willkommen zurück'],
  ['MENU.ACTIVE_APPLICATIONS', 'Aktive Anwendungen'],
  ['MENU.TODOS', 'TODOs'],
  ['MENU.RESPONSE_RATE', 'Antwortrate'],
  ['MENU.UPCOMING_INTERVIEWS', 'Kommende Interviews'],
  ['COMMON.NEW_APPLICATION', 'Neue Bewerbung'],
  ['STATS.JOB_APPLICATIONS_TREND', 'Bewerbungen Trend'],
  ['STATS.TOP_COMPANIES', 'Top-Unternehmen (Bewerbungen)'],
  ['STATS.NEW_JOB_LISTINGS_PER_DAY', 'Neue Stellenausschreibungen pro Tag'],
  ['STATS.APPLICATION_STATUS_DISTRIBUTION', 'Verteilung des Bewerbungsstatus'],
  ['STATUS.APPLIED', 'Beworben'],
  ['STATUS.REJECTED', 'Abgelehnt'],
  ['STATUS.OFFER', 'Angebot'],
  ['STATUS.INTERVIEW', 'Vorstellungsgespräch'],
  ['STATUS.IN_REVIEW', 'In Prüfung'],
  ['COMMON.CREATE', 'erstellen'],
  ['COMMON.EDIT', 'Bearbeiten'],
  ['COMMON.APPLICATION_LINK', 'Bewerbung Link'],
  ['COMMON.JOB_TITLE', 'Job-Titel'],
  ['COMMON.COMPANY', 'Unternehmen'],
  ['COMMON.LOCATION', 'Standort'],
  ['COMMON.EXPERIENCE_LEVEL', 'Erfahrungsstufe'],
  ['COMMON.JOB_TYPE', 'Art der Tätigkeit'],
  ['COMMON.SOURCE', 'Quelle'],
  ['COMMON.SALARY_RANGE', 'Gehaltsbereich'],
  ['COMMON.FROM', 'Von'],
  ['COMMON.TO', 'bis'],
  ['COMMON.CURRENCY', 'Währung'],
  ['COMMON.POSTED_DATE', 'Datum der Veröffentlichung'],
  ['COMMON.APPLICATION_DEADLINE', 'Bewerbungsfrist'],
  ['COMMON.Contact_EMAIL', 'Kontakt E-Mail'],
  ['COMMON.DESCRIPTION', 'Beschreibung'],
  ['COMMON.NOTES', 'Anmerkungen'],
  ['COMMON.CANCEL', 'Abbrechen'],
  ['COMMON.UPDATE', 'aktualisieren'],
  ['COMMON.EDIT_PROFILE', 'Profil bearbeiten'],
  ['COMMON.EDIT_SKILLS', 'Fähigkeiten bearbeiten'],
  ['COMMON.ADD_EXPERIENCE', 'Erfahrung hinzufügen'],
  ['COMMON.SKILLS', 'Fertigkeiten'],
  ['COMMON.EXPERIENCE', 'Erfahrung'],
  ['COMMON.EDUCATION', 'Ausbildung'],
  ['COMMON.CERTIFICATIONS', 'Zertifizierungen'],
  ['ROLE.USER', 'Benutzer'],
  ['ROLE.TECHNICAL_SUPPORT', 'Technische Unterstützung'],
  ['ROLE.ADMIN', 'Verwaltung'],
  ['ROLE.SUPER_ADMIN', 'Super-Verwalter'],
  ['JOB_TYPE.FULL_TIME', 'Vollzeit'],
  ['JOB_TYPE.PART_TIME', 'Halbtags'],
  ['JOB_TYPE.CONTRACT', 'Vertrag'],
  ['JOB_TYPE.TEMPORARY', 'Vorübergehend'],
  ['JOB_TYPE.INTERN', 'Praktikant'],
  ['JOB_TYPE.VOLUNTEER', 'Ehrenamtlich'],
  ['JOB_TYPE.FREELANCE', 'Freiberuflich'],
  ['JOB_TYPE.STARTUP', 'Neugründung'],
  ['JOB_TYPE.OTHER', 'Sonstiges'],
  ['JOB_SOURCE.JOB_BOARD', 'Stellenbörse'],
  ['JOB_SOURCE.COMPANY_WEBSITE', 'Firmen-Website'],
  ['JOB_SOURCE.RECOMMENDATION', 'Empfehlung'],
  ['JOB_SOURCE.OTHER', 'Andere'],
  ['EXPERIENCE_LEVEL.INTERNSHIP', 'Praktikum'],
  ['EXPERIENCE_LEVEL.ENTRY_LEVEL', 'Einstiegsstufe'],
  ['EXPERIENCE_LEVEL.JUNIOR', 'Junior'],
  ['EXPERIENCE_LEVEL.MID_LEVEL', 'Mittlere Stufe'],
  ['EXPERIENCE_LEVEL.SENIOR', 'Senior'],
  ['EXPERIENCE_LEVEL.EXECUTIVE', 'Führungskraft'],
  ['COMMON.APPLICATIONS', 'Anwendungen'],
  ['DATES.JANUARY_SHORT', 'Jan'],
  ['DATES.FEBRUARY_SHORT', 'Feb'],
  ['DATES.MARCH_SHORT', 'März'],
  ['DATES.APRIL_SHORT', 'Apr'],
  ['DATES.MAY_SHORT', 'Mai'],
  ['DATES.JUNE_SHORT', 'Juni'],
  ['DATES.JULY_SHORT', 'Juli'],
  ['DATES.AUGUST_SHORT', 'Aug'],
  ['DATES.SEPTEMBER_SHORT', 'Sep'],
  ['DATES.OCTOBER_SHORT', 'Okt'],
  ['DATES.NOVEMBER_SHORT', 'Nov'],
  ['DATES.DECEMBER_SHORT', 'Dez'],
  ['DATES.MONDAY_SHORT', 'Mo'],
  ['DATES.TUESDAY_SHORT', 'Di'],
  ['DATES.WEDNESDAY_SHORT', 'Mi'],
  ['DATES.THURSDAY_SHORT', 'Do'],
  ['DATES.FRIDAY_SHORT', 'Fr'],
  ['DATES.SATURDAY_SHORT', 'Sa'],
  ['DATES.SUNDAY_SHORT', 'So'],
  ['ERROR.ENTITY.USER_NOT_FOUND', 'Benutzer nicht gefunden'],
  ['COMMON.OK', 'Ok'],
  ['COMMON.USER_PREFERENCES', 'Benutzereinstellungen'],
  ['ERROR.ENTITY.UPDATE_ONLY_OWN_SETTINGS', 'Benutzer kann nur eigene Einstellungen aktualisieren'],
  ['COMMON.FIRST_NAME', 'Vorname'],
  ['COMMON.LAST_NAME', 'Nachname'],
  ['COMMON.LANGUAGE', 'Sprache'],
  ['COMMON.TIME_ZONE', 'Zeitzone'],
  ['COMMON.COUNTRY', 'Land'],
  ['COMMON.APPLICATION_AI_TEXTAREA', 'Anwendung AI textarea'],
  ['MESSAGES.CHANGES_SUCCESSFULLY_SAVED', 'Änderungen wurden erfolgreich gespeichert'],
  ['INPUT.TO_MANY_ITEMS.START_TYPING', 'Zu viele Einträge. Bitte fangen Sie an zu tippen'],
  ['ERROR.VALIDATION.INVALID_URL', 'Ungültiges URL-Format'],
  ['ERROR.VALIDATION.URL_NOT_HTTPS', 'URL verwendet kein HTTPS'],
  ['ERROR.VALIDATION.UNKNOWN_URL_TYPE', 'URL ist sicher, entspricht aber keinem bekannten Benutzernamenmuster'],
  ['COMMON.PHONE', 'Telefon'],
  ['SKILL_LEVEL.BEGINNER', 'Anfänger'],
  ['SKILL_LEVEL.BASIC', 'Grundlegend'],
  ['SKILL_LEVEL.INTERMEDIATE', 'Fortgeschritten'],
  ['SKILL_LEVEL.ADVANCED', 'Fortgeschritten'],
  ['SKILL_LEVEL.EXPERT', 'Experte'],
  ['SKILL_LEVEL.MASTER', 'Meister'],
  ['SKILL_LEVEL.WORLD_CLASS', 'Weltklasse'],
  ['WORK_ARRANGEMENT.ON_SITE', 'Vor Ort'],
  ['WORK_ARRANGEMENT.REMOTE', 'Ferngesteuert'],
  ['WORK_ARRANGEMENT.HYBRID', 'Hybride'],
  ['WORK_ARRANGEMENT.FLEXIBLE', 'Flexibel'],
  ['WORK_ARRANGEMENT.TRAVEL_REQUIRED', 'Reisen erforderlich'],
  ['WORK_ARRANGEMENT.SHIFT_BASED', 'Schichtweise'],
  ['COMMON.ADD', 'hinzufügen'],
  ['COMMON.REMOVE', 'Entfernen'],
  ['COMMON.ALREADY_EXISTS', 'Bereits vorhanden'],
  ['COMMON.LANGUAGE_LEVEL', 'Sprachlevel'],
  ['COMMON.LANGUAGES', 'Sprachen'],
  ['COMMON.EDIT_LANGUAGES', 'Sprachen bearbeiten'],
  ['ERROR.SYSTEM.COMMON_ERROR', 'Ein unerwarteter Fehler ist aufgetreten.'],
  ['ERROR.ENTITY.NOT_FOUND', 'Nicht gefunden'],
  ['ERROR.ENTITY.ENTITY_NOT_FOUND', 'Entität nicht gefunden'],
  ['ERROR.ENTITY.ENTITY_WITH_ID_NOT_FOUND', 'Entität mit dieser ID nicht gefunden'],
  ['ERROR.ENTITY.ENTITY_WITH_EMAIL_ALREADY_EXISTS', 'Entität mit dieser E-Mail existiert bereits'],
  ['ERROR.ENTITY.ENTITY_WITH_LOGIN_ALREADY_EXISTS', 'Entität mit diesem Login existiert bereits'],
  ['ERROR.VALIDATION.VALIDATION_ERROR', 'Validierungsfehler'],
  ['ERROR.ENTITY.ENTITY_ALREADY_EXISTS', 'Entität existiert bereits'],
  ['ERROR.SYSTEM.INTERNAL_SERVER_ERROR', 'Interner Serverfehler'],
  ['ERROR.ENTITY.BLOCKED', 'Gesperrt'],
  ['ERROR.ENTITY.RESOURCE_NOT_FOUND', 'Ressource nicht gefunden'],
  ['ERROR.ENTITY.ENTITY_BLOCKED', 'Entität ist gesperrt'],
  ['ERROR.ENTITY.ENTITY_PESSIMISTIC_LOCKED', 'Entität ist pessimistisch gesperrt'],
  ['ERROR.AUTH.WRONG_CREDENTIALS', 'Falsche Anmeldedaten'],
  ['ERROR.AUTH.FORBIDDEN', 'Zugriff verweigert'],
  ['ERROR.ENTITY.USER_BLOCKED', 'Benutzer ist gesperrt'],
  ['ERROR.SYSTEM.POTENTIAL_HARMFUL_CONTENT', 'Potentiell schädlicher Inhalt erkannt'],
  ['ERROR.AUTH.JWT_MIN_LENGTH', 'JWT-Token ist zu kurz'],
  ['ERROR.AUTH.JWT_INVALID_FORMAT', 'Ungültiges JWT-Format'],
  ['ERROR.AUTH.JWT_USER_CLAIM_NOT_FOUND', 'Benutzeranspruch nicht in JWT gefunden'],
  ['ERROR.AUTH.JWT_USER_CLAIM_INVALID_CONVERSION', 'Benutzeranspruch in JWT kann nicht konvertiert werden'],
  ['ERROR.AUTH.FORGOT_PASSWORD_REQUEST_TOO_SOON', 'Passwort vergessen zu früh angefordert'],
  ['ERROR.AUTH.RESTORE_PASSWORD_PROCESSING_ISSUE', 'Ein Problem ist bei der Passwortwiederherstellung aufgetreten'],
  ['ERROR.SYSTEM.VERSION_NOT_SPECIFIED', 'Version nicht angegeben'],
  ['ERROR.ENTITY.USER_PROJECT_LIMIT_EXCEEDED', 'Benutzer hat das Projektlimit überschritten'],
  ['ERROR.ENTITY.ROLE_NOT_SUPPORTED', 'Diese Rolle wird nicht unterstützt'],
  ['STATUS.NEW', 'Neu'],
  ['STATUS.ACTIVE', 'Aktiv'],
  ['STATUS.INACTIVE', 'Inaktiv'],
  ['STATUS.BLOCKED', 'Gesperrt'],
  ['STATUS.DELETED', 'Gelöscht'],
  ['STATUS.PENDING', 'Ausstehend'],
  ['STATUS.APPROVED', 'Genehmigt'],
  ['STATUS.COMPLETED', 'Abgeschlossen'],
  ['STATUS.CANCELLED', 'Abgebrochen'],
  ['KARMA.TITLE', 'Dein Karma'],
  ['KARMA.POINTS', 'Karma-Punkte'],
  ['KARMA.STATS.ACTIVITY', 'Aktivität'],
  ['KARMA.STATS.ACTIVITY_DESC', 'Gemeinschaftsbeteiligungsniveau'],
  ['KARMA.STATS.HELP', 'Hilfe'],
  ['KARMA.STATS.HELP_DESC', 'Hat anderen Benutzern geholfen'],
  ['KARMA.STATS.ACHIEVEMENTS', 'Erfolge'],
  ['KARMA.STATS.ACHIEVEMENTS_DESC', 'Auszeichnungen erhalten'],
  ['KARMA.HISTORY.TITLE', 'Karma-Verlauf'],
  ['KARMA.HISTORY.DATE', 'Datum'],
  ['KARMA.HISTORY.EVENT', 'Ereignis'],
  ['KARMA.HISTORY.CHANGE', 'Änderung'],
  ['KARMA.HISTORY.EVENTS.TASK_HELP', 'Half bei der Lösung einer Aufgabe'],
  ['KARMA.HISTORY.EVENTS.DISCUSSION', 'Aktive Teilnahme an der Diskussion'],
  ['KARMA.HISTORY.EVENTS.MATERIAL', 'Nützliches Material veröffentlicht'],
]);
